
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr 14 2025 15:27:17 -03 (Apr 14 2025 18:27:17 UTC)

// Verification Directory fv/ripple_carry_adder_32bits 

module ripple_carry_adder_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire n_74, n_76, n_78, n_80, n_82, n_84, n_86, n_88;
  wire n_90, n_92, n_94, n_96, n_98, n_100, n_102, n_104;
  wire n_106, n_108, n_110, n_112, n_114, n_116, n_118, n_120;
  wire n_122, n_124, n_126, n_128, n_130, n_132, n_202;
  sky130_fd_sc_hd__fa_1 g2038__2398(.A (A[31]), .B (B[31]), .CIN
       (n_132), .COUT (Cout), .SUM (S[31]));
  sky130_fd_sc_hd__fa_1 g2039__5107(.A (A[30]), .B (B[30]), .CIN
       (n_130), .COUT (n_132), .SUM (S[30]));
  sky130_fd_sc_hd__fa_1 g2040__6260(.A (A[29]), .B (B[29]), .CIN
       (n_128), .COUT (n_130), .SUM (S[29]));
  sky130_fd_sc_hd__fa_1 g2041__4319(.A (A[28]), .B (B[28]), .CIN
       (n_126), .COUT (n_128), .SUM (S[28]));
  sky130_fd_sc_hd__fa_1 g2042__8428(.A (A[27]), .B (B[27]), .CIN
       (n_124), .COUT (n_126), .SUM (S[27]));
  sky130_fd_sc_hd__fa_1 g2043__5526(.A (A[26]), .B (B[26]), .CIN
       (n_122), .COUT (n_124), .SUM (S[26]));
  sky130_fd_sc_hd__fa_1 g2044__6783(.A (A[25]), .B (B[25]), .CIN
       (n_120), .COUT (n_122), .SUM (S[25]));
  sky130_fd_sc_hd__fa_1 g2045__3680(.A (A[24]), .B (B[24]), .CIN
       (n_118), .COUT (n_120), .SUM (S[24]));
  sky130_fd_sc_hd__fa_1 g2046__1617(.A (A[23]), .B (B[23]), .CIN
       (n_116), .COUT (n_118), .SUM (S[23]));
  sky130_fd_sc_hd__fa_1 g2047__2802(.A (A[22]), .B (B[22]), .CIN
       (n_114), .COUT (n_116), .SUM (S[22]));
  sky130_fd_sc_hd__fa_1 g2048__1705(.A (A[21]), .B (B[21]), .CIN
       (n_112), .COUT (n_114), .SUM (S[21]));
  sky130_fd_sc_hd__fa_1 g2049__5122(.A (A[20]), .B (B[20]), .CIN
       (n_110), .COUT (n_112), .SUM (S[20]));
  sky130_fd_sc_hd__fa_1 g2050__8246(.A (A[19]), .B (B[19]), .CIN
       (n_108), .COUT (n_110), .SUM (S[19]));
  sky130_fd_sc_hd__fa_1 g2051__7098(.A (A[18]), .B (B[18]), .CIN
       (n_106), .COUT (n_108), .SUM (S[18]));
  sky130_fd_sc_hd__fa_1 g2052__6131(.A (A[17]), .B (B[17]), .CIN
       (n_104), .COUT (n_106), .SUM (S[17]));
  sky130_fd_sc_hd__fa_1 g2053__1881(.A (A[16]), .B (B[16]), .CIN
       (n_102), .COUT (n_104), .SUM (S[16]));
  sky130_fd_sc_hd__fa_1 g2054__5115(.A (A[15]), .B (B[15]), .CIN
       (n_100), .COUT (n_102), .SUM (S[15]));
  sky130_fd_sc_hd__fa_1 g2055__7482(.A (A[14]), .B (B[14]), .CIN
       (n_98), .COUT (n_100), .SUM (S[14]));
  sky130_fd_sc_hd__fa_1 g2056__4733(.A (A[13]), .B (B[13]), .CIN
       (n_96), .COUT (n_98), .SUM (S[13]));
  sky130_fd_sc_hd__fa_1 g2057__6161(.A (A[12]), .B (B[12]), .CIN
       (n_94), .COUT (n_96), .SUM (S[12]));
  sky130_fd_sc_hd__fa_1 g2058__9315(.A (A[11]), .B (B[11]), .CIN
       (n_92), .COUT (n_94), .SUM (S[11]));
  sky130_fd_sc_hd__fa_1 g2059__9945(.A (A[10]), .B (B[10]), .CIN
       (n_90), .COUT (n_92), .SUM (S[10]));
  sky130_fd_sc_hd__fa_1 g2060__2883(.A (A[9]), .B (B[9]), .CIN (n_88),
       .COUT (n_90), .SUM (S[9]));
  sky130_fd_sc_hd__fa_1 g2061__2346(.A (A[8]), .B (B[8]), .CIN (n_86),
       .COUT (n_88), .SUM (S[8]));
  sky130_fd_sc_hd__fa_1 g2062__1666(.A (A[7]), .B (B[7]), .CIN (n_84),
       .COUT (n_86), .SUM (S[7]));
  sky130_fd_sc_hd__fa_1 g2063__7410(.A (A[6]), .B (B[6]), .CIN (n_82),
       .COUT (n_84), .SUM (S[6]));
  sky130_fd_sc_hd__fa_1 g2064__6417(.A (A[5]), .B (B[5]), .CIN (n_80),
       .COUT (n_82), .SUM (S[5]));
  sky130_fd_sc_hd__fa_1 g2065__5477(.A (A[4]), .B (B[4]), .CIN (n_78),
       .COUT (n_80), .SUM (S[4]));
  sky130_fd_sc_hd__fa_1 g2066__2398(.A (A[3]), .B (B[3]), .CIN (n_76),
       .COUT (n_78), .SUM (S[3]));
  sky130_fd_sc_hd__fa_1 g2067__5107(.A (A[2]), .B (B[2]), .CIN (n_74),
       .COUT (n_76), .SUM (S[2]));
  sky130_fd_sc_hd__fa_1 g2068__6260(.A (A[1]), .B (B[1]), .CIN (n_202),
       .COUT (n_74), .SUM (S[1]));
  sky130_fd_sc_hd__fa_1 g2(.A (Cin), .B (B[0]), .CIN (A[0]), .COUT
       (n_202), .SUM (S[0]));
endmodule

