
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr 14 2025 15:21:42 -03 (Apr 14 2025 18:21:42 UTC)

// Verification Directory fv/signal_32bits 

module signal_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire UNCONNECTED, addinc_add_7_30_n_0, addinc_add_7_30_n_2,
       addinc_add_7_30_n_3, addinc_add_7_30_n_6, addinc_add_7_30_n_7,
       addinc_add_7_30_n_9, addinc_add_7_30_n_10;
  wire addinc_add_7_30_n_11, addinc_add_7_30_n_12,
       addinc_add_7_30_n_13, addinc_add_7_30_n_14,
       addinc_add_7_30_n_15, addinc_add_7_30_n_17,
       addinc_add_7_30_n_18, addinc_add_7_30_n_19;
  wire addinc_add_7_30_n_21, addinc_add_7_30_n_22,
       addinc_add_7_30_n_23, addinc_add_7_30_n_24,
       addinc_add_7_30_n_25, addinc_add_7_30_n_27,
       addinc_add_7_30_n_28, addinc_add_7_30_n_29;
  wire addinc_add_7_30_n_30, addinc_add_7_30_n_31,
       addinc_add_7_30_n_33, addinc_add_7_30_n_39,
       addinc_add_7_30_n_46, addinc_add_7_30_n_49,
       addinc_add_7_30_n_51, addinc_add_7_30_n_52;
  wire addinc_add_7_30_n_55, addinc_add_7_30_n_56,
       addinc_add_7_30_n_58, addinc_add_7_30_n_67,
       addinc_add_7_30_n_69, addinc_add_7_30_n_72,
       addinc_add_7_30_n_81, addinc_add_7_30_n_84;
  wire addinc_add_7_30_n_85, addinc_add_7_30_n_86,
       addinc_add_7_30_n_93, addinc_add_7_30_n_94,
       addinc_add_7_30_n_95, addinc_add_7_30_n_96,
       addinc_add_7_30_n_97, addinc_add_7_30_n_99;
  wire addinc_add_7_30_n_100, addinc_add_7_30_n_101,
       addinc_add_7_30_n_102, addinc_add_7_30_n_103,
       addinc_add_7_30_n_104, addinc_add_7_30_n_105,
       addinc_add_7_30_n_106, addinc_add_7_30_n_107;
  wire addinc_add_7_30_n_109, addinc_add_7_30_n_110,
       addinc_add_7_30_n_111, addinc_add_7_30_n_112,
       addinc_add_7_30_n_113, addinc_add_7_30_n_115,
       addinc_add_7_30_n_116, addinc_add_7_30_n_117;
  wire addinc_add_7_30_n_118, addinc_add_7_30_n_119,
       addinc_add_7_30_n_120, addinc_add_7_30_n_121,
       addinc_add_7_30_n_122, addinc_add_7_30_n_123,
       addinc_add_7_30_n_124, addinc_add_7_30_n_128;
  wire addinc_add_7_30_n_129, addinc_add_7_30_n_130,
       addinc_add_7_30_n_132, addinc_add_7_30_n_133,
       addinc_add_7_30_n_135, addinc_add_7_30_n_138,
       addinc_add_7_30_n_140, addinc_add_7_30_n_142;
  wire addinc_add_7_30_n_144, addinc_add_7_30_n_146,
       addinc_add_7_30_n_147, addinc_add_7_30_n_148,
       addinc_add_7_30_n_149, addinc_add_7_30_n_151,
       addinc_add_7_30_n_152, addinc_add_7_30_n_153;
  wire addinc_add_7_30_n_154, addinc_add_7_30_n_155,
       addinc_add_7_30_n_156, addinc_add_7_30_n_157,
       addinc_add_7_30_n_158, addinc_add_7_30_n_159,
       addinc_add_7_30_n_160, addinc_add_7_30_n_161;
  wire addinc_add_7_30_n_162, addinc_add_7_30_n_164,
       addinc_add_7_30_n_165, addinc_add_7_30_n_167,
       addinc_add_7_30_n_168, addinc_add_7_30_n_169,
       addinc_add_7_30_n_170, addinc_add_7_30_n_171;
  wire addinc_add_7_30_n_172, addinc_add_7_30_n_173,
       addinc_add_7_30_n_174, addinc_add_7_30_n_175,
       addinc_add_7_30_n_176, addinc_add_7_30_n_177,
       addinc_add_7_30_n_178, addinc_add_7_30_n_179;
  wire addinc_add_7_30_n_180, addinc_add_7_30_n_182,
       addinc_add_7_30_n_183, addinc_add_7_30_n_184,
       addinc_add_7_30_n_185, addinc_add_7_30_n_186,
       addinc_add_7_30_n_187, addinc_add_7_30_n_188;
  wire addinc_add_7_30_n_189, addinc_add_7_30_n_190,
       addinc_add_7_30_n_191, addinc_add_7_30_n_192,
       addinc_add_7_30_n_193, addinc_add_7_30_n_194,
       addinc_add_7_30_n_195, addinc_add_7_30_n_196;
  wire addinc_add_7_30_n_197, addinc_add_7_30_n_198,
       addinc_add_7_30_n_199, addinc_add_7_30_n_200,
       addinc_add_7_30_n_201, addinc_add_7_30_n_202,
       addinc_add_7_30_n_203, addinc_add_7_30_n_207;
  wire addinc_add_7_30_n_208, addinc_add_7_30_n_209,
       addinc_add_7_30_n_210, addinc_add_7_30_n_211,
       addinc_add_7_30_n_212, addinc_add_7_30_n_213,
       addinc_add_7_30_n_214, addinc_add_7_30_n_215;
  wire addinc_add_7_30_n_216, addinc_add_7_30_n_217,
       addinc_add_7_30_n_218, addinc_add_7_30_n_220,
       addinc_add_7_30_n_221, addinc_add_7_30_n_222,
       addinc_add_7_30_n_223, addinc_add_7_30_n_224;
  wire addinc_add_7_30_n_225, addinc_add_7_30_n_226,
       addinc_add_7_30_n_227, addinc_add_7_30_n_230,
       addinc_add_7_30_n_231, addinc_add_7_30_n_232,
       addinc_add_7_30_n_233, addinc_add_7_30_n_237;
  wire addinc_add_7_30_n_239, addinc_add_7_30_n_242,
       addinc_add_7_30_n_244, addinc_add_7_30_n_247,
       addinc_add_7_30_n_248, addinc_add_7_30_n_249,
       addinc_add_7_30_n_250, addinc_add_7_30_n_251;
  wire addinc_add_7_30_n_253, addinc_add_7_30_n_254,
       addinc_add_7_30_n_256, addinc_add_7_30_n_260,
       addinc_add_7_30_n_261, addinc_add_7_30_n_262,
       addinc_add_7_30_n_263, addinc_add_7_30_n_264;
  wire addinc_add_7_30_n_265, addinc_add_7_30_n_267,
       addinc_add_7_30_n_268, addinc_add_7_30_n_269,
       addinc_add_7_30_n_271, addinc_add_7_30_n_272,
       addinc_add_7_30_n_274, addinc_add_7_30_n_275;
  wire addinc_add_7_30_n_276, addinc_add_7_30_n_279,
       addinc_add_7_30_n_280, addinc_add_7_30_n_281,
       addinc_add_7_30_n_282, addinc_add_7_30_n_283,
       addinc_add_7_30_n_284, addinc_add_7_30_n_286;
  wire addinc_add_7_30_n_287, addinc_add_7_30_n_290,
       addinc_add_7_30_n_291, addinc_add_7_30_n_293,
       addinc_add_7_30_n_294, addinc_add_7_30_n_296,
       addinc_add_7_30_n_297, addinc_add_7_30_n_298;
  wire addinc_add_7_30_n_299, addinc_add_7_30_n_300,
       addinc_add_7_30_n_301, addinc_add_7_30_n_302,
       addinc_add_7_30_n_303, addinc_add_7_30_n_304,
       addinc_add_7_30_n_306, addinc_add_7_30_n_307;
  wire addinc_add_7_30_n_308, addinc_add_7_30_n_309,
       addinc_add_7_30_n_311, addinc_add_7_30_n_313,
       addinc_add_7_30_n_314, addinc_add_7_30_n_315,
       addinc_add_7_30_n_316, addinc_add_7_30_n_317;
  wire addinc_add_7_30_n_320, addinc_add_7_30_n_323,
       addinc_add_7_30_n_325, addinc_add_7_30_n_326,
       addinc_add_7_30_n_327, addinc_add_7_30_n_328,
       addinc_add_7_30_n_329, addinc_add_7_30_n_330;
  wire addinc_add_7_30_n_331, addinc_add_7_30_n_332,
       addinc_add_7_30_n_333, addinc_add_7_30_n_334,
       addinc_add_7_30_n_336, addinc_add_7_30_n_337,
       addinc_add_7_30_n_338, addinc_add_7_30_n_341;
  wire addinc_add_7_30_n_342, addinc_add_7_30_n_343,
       addinc_add_7_30_n_344, addinc_add_7_30_n_351,
       addinc_add_7_30_n_352, addinc_add_7_30_n_353,
       addinc_add_7_30_n_354, addinc_add_7_30_n_356;
  wire addinc_add_7_30_n_357, addinc_add_7_30_n_359,
       addinc_add_7_30_n_360, addinc_add_7_30_n_361,
       addinc_add_7_30_n_362, addinc_add_7_30_n_363,
       addinc_add_7_30_n_364, addinc_add_7_30_n_365;
  wire addinc_add_7_30_n_367, addinc_add_7_30_n_370,
       addinc_add_7_30_n_372, addinc_add_7_30_n_373,
       addinc_add_7_30_n_374, addinc_add_7_30_n_375,
       addinc_add_7_30_n_376, addinc_add_7_30_n_377;
  wire addinc_add_7_30_n_379, addinc_add_7_30_n_380,
       addinc_add_7_30_n_383, addinc_add_7_30_n_384,
       addinc_add_7_30_n_387, addinc_add_7_30_n_389,
       addinc_add_7_30_n_391, addinc_add_7_30_n_394;
  wire addinc_add_7_30_n_402, addinc_add_7_30_n_403,
       addinc_add_7_30_n_404, addinc_add_7_30_n_405,
       addinc_add_7_30_n_406, addinc_add_7_30_n_407,
       addinc_add_7_30_n_408, addinc_add_7_30_n_409;
  wire addinc_add_7_30_n_410, addinc_add_7_30_n_411,
       addinc_add_7_30_n_412, addinc_add_7_30_n_413,
       addinc_add_7_30_n_414, addinc_add_7_30_n_415,
       addinc_add_7_30_n_416, addinc_add_7_30_n_417;
  wire addinc_add_7_30_n_418, addinc_add_7_30_n_419,
       addinc_add_7_30_n_420, addinc_add_7_30_n_421,
       addinc_add_7_30_n_422, addinc_add_7_30_n_423,
       addinc_add_7_30_n_424, addinc_add_7_30_n_425;
  wire addinc_add_7_30_n_426, n_11, n_14, n_22, n_23, n_25, n_27, n_32;
  wire n_33, n_38, n_39, n_42, n_45, n_64, n_507, n_511;
  wire n_513, n_516, n_520, n_529, n_532, n_535, n_536, n_539;
  wire n_542, n_547, n_548, n_550, n_553, n_556, n_561, n_562;
  wire n_567, n_576, n_579, n_582, n_585, n_587, n_592, n_594;
  wire n_607, n_608, n_615, n_618, n_620, n_622, n_624, n_627;
  wire n_629, n_631, n_633, n_636, n_640, n_641, n_645, n_647;
  wire n_650, n_651, n_654, n_657, n_661, n_700, n_701, n_702;
  wire n_703, n_706, n_707, n_710, n_711, n_712, n_713, n_714;
  wire n_715, n_716, n_770, n_773, n_776, n_777, n_778, n_779;
  wire n_780, n_781, n_784, n_787, n_788, n_789, n_790, n_792;
  wire n_793, n_794, n_795, n_796, n_797, n_800, n_803, n_805;
  wire n_807, n_808, n_809, n_810, n_811, n_812, n_813, n_814;
  wire n_815, n_816, n_817, n_818, n_819, n_820, n_821, n_822;
  wire n_823, n_824, n_825, n_826, n_827, n_829, n_834, n_835;
  wire n_836, n_837, n_838, n_839, n_840, n_841, n_842, n_843;
  wire n_844, n_845, n_846, n_847, n_849, n_850, n_852, n_853;
  wire n_854, n_855, n_856, n_859, n_860, n_861, n_863, n_864;
  wire n_865, n_866, n_867, n_868, n_869;
  sky130_fd_sc_hd__clkbuf_1 g53(.A (Cin), .X (n_64));
  sky130_fd_sc_hd__inv_2 g37(.A (A[18]), .Y (addinc_add_7_30_n_85));
  sky130_fd_sc_hd__clkbuf_1 g48(.A (A[28]), .X (n_45));
  sky130_fd_sc_hd__inv_2 g63(.A (B[16]), .Y (addinc_add_7_30_n_84));
  sky130_fd_sc_hd__clkbuf_1 g15(.A (A[0]), .X (n_42));
  sky130_fd_sc_hd__clkbuf_1 g16(.A (A[1]), .X (n_39));
  sky130_fd_sc_hd__buf_1 g75(.A (B[0]), .X (n_38));
  sky130_fd_sc_hd__inv_2 g28(.A (A[11]), .Y (addinc_add_7_30_n_52));
  sky130_fd_sc_hd__inv_2 g66(.A (B[11]), .Y (addinc_add_7_30_n_51));
  sky130_fd_sc_hd__clkbuf_1 g47(.A (A[27]), .X (n_33));
  sky130_fd_sc_hd__clkbuf_1 g39(.A (A[20]), .X (n_32));
  sky130_fd_sc_hd__inv_2 g70(.A (B[7]), .Y (addinc_add_7_30_n_67));
  sky130_fd_sc_hd__clkbuf_1 g42(.A (A[23]), .X (n_27));
  sky130_fd_sc_hd__clkbuf_1 g85(.A (B[28]), .X (n_25));
  sky130_fd_sc_hd__clkbuf_1 g41(.A (A[22]), .X (n_23));
  sky130_fd_sc_hd__clkbuf_1 g76(.A (B[27]), .X (n_22));
  sky130_fd_sc_hd__inv_2 g74(.A (B[1]), .Y (addinc_add_7_30_n_86));
  sky130_fd_sc_hd__clkbuf_1 g58(.A (B[22]), .X (n_14));
  sky130_fd_sc_hd__inv_4 g80(.A (B[17]), .Y (addinc_add_7_30_n_46));
  sky130_fd_sc_hd__clkbuf_1 g78(.A (B[20]), .X (n_11));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1796__2398(.A
       (addinc_add_7_30_n_412), .B (addinc_add_7_30_n_405), .Y (S[24]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1797__5107(.A
       (addinc_add_7_30_n_22), .B (addinc_add_7_30_n_421), .Y (S[29]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1798__6260(.A
       (addinc_add_7_30_n_411), .B (addinc_add_7_30_n_404), .Y (S[28]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1800__8428(.A
       (addinc_add_7_30_n_413), .B (addinc_add_7_30_n_414), .Y (S[26]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1801__5526(.A
       (addinc_add_7_30_n_406), .B (addinc_add_7_30_n_407), .Y (S[25]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1802__6783(.A
       (addinc_add_7_30_n_417), .B (addinc_add_7_30_n_418), .Y (S[31]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1803__3680(.A
       (addinc_add_7_30_n_18), .B (addinc_add_7_30_n_410), .Y (S[19]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1804__1617(.A
       (addinc_add_7_30_n_402), .B (addinc_add_7_30_n_403), .Y (S[22]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1805__2802(.A
       (addinc_add_7_30_n_415), .B (addinc_add_7_30_n_416), .Y (S[21]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1806__1705(.A
       (addinc_add_7_30_n_419), .B (addinc_add_7_30_n_420), .Y (S[20]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1807__5122(.A
       (addinc_add_7_30_n_21), .B (addinc_add_7_30_n_426), .Y (S[23]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1808__8246(.A
       (addinc_add_7_30_n_19), .B (addinc_add_7_30_n_424), .Y (S[18]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1809__7098(.A
       (addinc_add_7_30_n_422), .B (addinc_add_7_30_n_423), .Y (S[17]));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1810__6131(.A
       (addinc_add_7_30_n_409), .B (addinc_add_7_30_n_408), .Y (S[30]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1811__1881(.A
       (addinc_add_7_30_n_391), .B (addinc_add_7_30_n_218), .Y
       (addinc_add_7_30_n_426));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1814__5115(.A (n_700), .B
       (addinc_add_7_30_n_220), .Y (addinc_add_7_30_n_425));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1816__7482(.A
       (addinc_add_7_30_n_383), .B (addinc_add_7_30_n_186), .Y
       (addinc_add_7_30_n_424));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1817__4733(.A
       (addinc_add_7_30_n_194), .B (addinc_add_7_30_n_372), .Y
       (addinc_add_7_30_n_423));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1818__6161(.A
       (addinc_add_7_30_n_373), .B (addinc_add_7_30_n_195), .Y
       (addinc_add_7_30_n_422));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1820__9315(.A
       (addinc_add_7_30_n_394), .B (addinc_add_7_30_n_227), .Y
       (addinc_add_7_30_n_421));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1821__9945(.A
       (addinc_add_7_30_n_177), .B (addinc_add_7_30_n_379), .Y
       (addinc_add_7_30_n_420));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1822__2883(.A
       (addinc_add_7_30_n_380), .B (addinc_add_7_30_n_178), .Y
       (addinc_add_7_30_n_419));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1823__2346(.A
       (addinc_add_7_30_n_389), .B (addinc_add_7_30_n_213), .Y
       (addinc_add_7_30_n_418));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1824__1666(.A (n_620), .B
       (addinc_add_7_30_n_214), .Y (addinc_add_7_30_n_417));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1825__7410(.A
       (addinc_add_7_30_n_387), .B (addinc_add_7_30_n_190), .Y
       (addinc_add_7_30_n_416));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1826__6417(.A (n_633), .B
       (addinc_add_7_30_n_191), .Y (addinc_add_7_30_n_415));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1827__5477(.A (n_710), .B
       (addinc_add_7_30_n_232), .Y (addinc_add_7_30_n_414));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1828__2398(.A (n_618), .B
       (addinc_add_7_30_n_233), .Y (addinc_add_7_30_n_413));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1829__5107(.A
       (addinc_add_7_30_n_375), .B (addinc_add_7_30_n_222), .Y
       (addinc_add_7_30_n_412));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1830__6260(.A (n_629), .B
       (addinc_add_7_30_n_231), .Y (addinc_add_7_30_n_411));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1831__4319(.A
       (addinc_add_7_30_n_376), .B (addinc_add_7_30_n_189), .Y
       (addinc_add_7_30_n_410));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1833__8428(.A (n_627), .B
       (addinc_add_7_30_n_170), .Y (addinc_add_7_30_n_409));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1834__5526(.A
       (addinc_add_7_30_n_370), .B (addinc_add_7_30_n_169), .Y
       (addinc_add_7_30_n_408));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1835__6783(.A
       (addinc_add_7_30_n_384), .B (addinc_add_7_30_n_224), .Y
       (addinc_add_7_30_n_407));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1836__3680(.A (n_631), .B
       (addinc_add_7_30_n_225), .Y (addinc_add_7_30_n_406));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1837__1617(.A
       (addinc_add_7_30_n_374), .B (addinc_add_7_30_n_221), .Y
       (addinc_add_7_30_n_405));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1838__2802(.A
       (addinc_add_7_30_n_377), .B (addinc_add_7_30_n_230), .Y
       (addinc_add_7_30_n_404));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1839__1705(.A (n_716), .B
       (addinc_add_7_30_n_172), .Y (addinc_add_7_30_n_403));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1840__5122(.A (n_622), .B
       (addinc_add_7_30_n_173), .Y (addinc_add_7_30_n_402));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1841__8246(.A1_N
       (addinc_add_7_30_n_176), .A2_N (addinc_add_7_30_n_363), .B1
       (addinc_add_7_30_n_176), .B2 (addinc_add_7_30_n_363), .X
       (S[15]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1842__7098(.A1_N
       (addinc_add_7_30_n_187), .A2_N (addinc_add_7_30_n_364), .B1
       (addinc_add_7_30_n_187), .B2 (addinc_add_7_30_n_364), .X
       (S[14]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1843__6131(.A1_N
       (addinc_add_7_30_n_184), .A2_N (addinc_add_7_30_n_362), .B1
       (addinc_add_7_30_n_184), .B2 (addinc_add_7_30_n_362), .X
       (S[13]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1844__1881(.A1_N
       (addinc_add_7_30_n_182), .A2_N (addinc_add_7_30_n_365), .B1
       (addinc_add_7_30_n_182), .B2 (addinc_add_7_30_n_365), .X
       (S[12]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1845__5115(.A1_N
       (addinc_add_7_30_n_171), .A2_N (addinc_add_7_30_n_356), .B1
       (addinc_add_7_30_n_171), .B2 (addinc_add_7_30_n_356), .X
       (S[11]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1846__7482(.A1_N
       (addinc_add_7_30_n_174), .A2_N (n_867), .B1
       (addinc_add_7_30_n_174), .B2 (n_867), .X (S[9]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1847__4733(.A1_N
       (addinc_add_7_30_n_193), .A2_N (addinc_add_7_30_n_367), .B1
       (addinc_add_7_30_n_193), .B2 (addinc_add_7_30_n_367), .X
       (S[10]));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1856__6161(.A1 (n_711), .A2
       (addinc_add_7_30_n_299), .B1 (addinc_add_7_30_n_326), .Y
       (addinc_add_7_30_n_394));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1858__9945(.A1 (n_661), .A2
       (addinc_add_7_30_n_268), .B1 (addinc_add_7_30_n_308), .Y
       (addinc_add_7_30_n_391));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1859__2883(.A
       (addinc_add_7_30_n_357), .B (addinc_add_7_30_n_334), .Y
       (addinc_add_7_30_n_389));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1860__2346(.A
       (addinc_add_7_30_n_354), .B (addinc_add_7_30_n_314), .Y
       (addinc_add_7_30_n_387));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1862__7410(.A
       (addinc_add_7_30_n_351), .B (addinc_add_7_30_n_333), .Y
       (addinc_add_7_30_n_384));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1863__6417(.A1 (n_661), .A2
       (addinc_add_7_30_n_15), .B1 (addinc_add_7_30_n_30), .Y
       (addinc_add_7_30_n_383));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1865(.A
       (addinc_add_7_30_n_379), .Y (addinc_add_7_30_n_380));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1868(.A
       (addinc_add_7_30_n_374), .Y (addinc_add_7_30_n_375));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1869(.A
       (addinc_add_7_30_n_372), .Y (addinc_add_7_30_n_373));
  sky130_fd_sc_hd__mux2_2 addinc_add_7_30_g1871__5477(.A0 (n_711), .A1
       (n_608), .S (addinc_add_7_30_n_197), .X (S[16]));
  sky130_fd_sc_hd__a31o_2 addinc_add_7_30_g1872__2398(.A1 (n_607), .A2
       (addinc_add_7_30_n_276), .A3 (n_706), .B1
       (addinc_add_7_30_n_327), .X (Cout));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1874__6260(.A
       (addinc_add_7_30_n_359), .B (addinc_add_7_30_n_287), .Y
       (addinc_add_7_30_n_379));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1875__4319(.A
       (addinc_add_7_30_n_352), .B (addinc_add_7_30_n_331), .Y
       (addinc_add_7_30_n_377));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1876__8428(.A1 (n_711), .A2
       (addinc_add_7_30_n_253), .B1 (addinc_add_7_30_n_303), .Y
       (addinc_add_7_30_n_376));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1877__5526(.A
       (addinc_add_7_30_n_360), .B (addinc_add_7_30_n_311), .Y
       (addinc_add_7_30_n_374));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1878__6783(.A
       (addinc_add_7_30_n_361), .B (addinc_add_7_30_n_112), .Y
       (addinc_add_7_30_n_372));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1879__3680(.A
       (addinc_add_7_30_n_353), .B (addinc_add_7_30_n_325), .Y
       (addinc_add_7_30_n_370));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1880__1617(.A (n_711), .B
       (addinc_add_7_30_n_115), .Y (addinc_add_7_30_n_361));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1881__2802(.A (n_706), .B
       (n_661), .Y (addinc_add_7_30_n_360));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1882__1705(.A (n_711), .B
       (n_712), .Y (addinc_add_7_30_n_359));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1884__8246(.A (n_661), .B
       (addinc_add_7_30_n_274), .C (n_706), .Y (addinc_add_7_30_n_357));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1885__7098(.A1 (n_863), .A2
       (addinc_add_7_30_n_209), .B1 (addinc_add_7_30_n_247), .X
       (addinc_add_7_30_n_367));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1887__1881(.A1 (n_863), .A2
       (n_645), .B1 (n_640), .X (addinc_add_7_30_n_365));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1888__5115(.A
       (addinc_add_7_30_n_343), .B (addinc_add_7_30_n_313), .Y
       (addinc_add_7_30_n_364));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1889__7482(.A
       (addinc_add_7_30_n_344), .B (addinc_add_7_30_n_307), .Y
       (addinc_add_7_30_n_363));
  sky130_fd_sc_hd__o211ai_2 addinc_add_7_30_g1890__4733(.A1
       (addinc_add_7_30_n_95), .A2 (n_641), .B1
       (addinc_add_7_30_n_148), .C1 (addinc_add_7_30_n_342), .Y
       (addinc_add_7_30_n_362));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1892__9315(.A (n_661), .B
       (n_712), .C (n_827), .Y (addinc_add_7_30_n_354));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1893__9945(.A (n_711), .B
       (n_706), .C (addinc_add_7_30_n_275), .Y (addinc_add_7_30_n_353));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1894__2883(.A (n_661), .B
       (n_706), .C (n_651), .Y (addinc_add_7_30_n_352));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1895__2346(.A (n_661), .B
       (n_706), .C (addinc_add_7_30_n_133), .Y (addinc_add_7_30_n_351));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1896__1666(.A1_N
       (addinc_add_7_30_n_180), .A2_N (n_863), .B1
       (addinc_add_7_30_n_180), .B2 (n_863), .X (S[8]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1897__7410(.A1_N
       (addinc_add_7_30_n_179), .A2_N (addinc_add_7_30_n_329), .B1
       (addinc_add_7_30_n_179), .B2 (addinc_add_7_30_n_329), .X (S[7]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1898__6417(.A1_N
       (addinc_add_7_30_n_212), .A2_N (addinc_add_7_30_n_338), .B1
       (addinc_add_7_30_n_212), .B2 (addinc_add_7_30_n_338), .X (S[5]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1899__5477(.A1_N
       (addinc_add_7_30_n_183), .A2_N (addinc_add_7_30_n_337), .B1
       (addinc_add_7_30_n_183), .B2 (addinc_add_7_30_n_337), .X (S[3]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1900__2398(.A1_N
       (addinc_add_7_30_n_216), .A2_N (addinc_add_7_30_n_336), .B1
       (addinc_add_7_30_n_216), .B2 (addinc_add_7_30_n_336), .X (S[6]));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1901__5107(.A
       (addinc_add_7_30_n_341), .B (addinc_add_7_30_n_269), .C (n_636),
       .Y (addinc_add_7_30_n_356));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1903__4319(.A (n_863), .B
       (addinc_add_7_30_n_262), .C (n_645), .Y (addinc_add_7_30_n_344));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1904__8428(.A (n_863), .B
       (n_645), .C (n_529), .Y (addinc_add_7_30_n_343));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1905__5526(.A (n_863), .B
       (addinc_add_7_30_n_271), .Y (addinc_add_7_30_n_342));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1906__6783(.A (n_863), .B
       (addinc_add_7_30_n_209), .C (n_657), .Y (addinc_add_7_30_n_341));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1909__3680(.A1
       (addinc_add_7_30_n_274), .A2 (n_842), .B1
       (addinc_add_7_30_n_306), .Y (addinc_add_7_30_n_334));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1910__1617(.A1
       (addinc_add_7_30_n_133), .A2 (n_842), .B1_N
       (addinc_add_7_30_n_116), .Y (addinc_add_7_30_n_333));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1911__2802(.A1 (n_842), .A2
       (n_707), .B1 (n_796), .Y (addinc_add_7_30_n_332));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1912__1705(.A1 (n_842), .A2
       (n_651), .B1 (addinc_add_7_30_n_291), .Y
       (addinc_add_7_30_n_331));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1913__5122(.A1
       (addinc_add_7_30_n_144), .A2 (n_561), .B1
       (addinc_add_7_30_n_121), .Y (addinc_add_7_30_n_338));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1914__8246(.A1
       (addinc_add_7_30_n_97), .A2 (addinc_add_7_30_n_14), .B1
       (addinc_add_7_30_n_109), .Y (addinc_add_7_30_n_337));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1915__7098(.A1 (n_562), .A2
       (addinc_add_7_30_n_211), .B1 (addinc_add_7_30_n_29), .X
       (addinc_add_7_30_n_336));
  sky130_fd_sc_hd__inv_4 addinc_add_7_30_g1917(.A
       (addinc_add_7_30_n_323), .Y (addinc_add_7_30_n_330));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1918__1881(.A1
       (addinc_add_7_30_n_264), .A2 (addinc_add_7_30_n_311), .B1
       (addinc_add_7_30_n_301), .Y (addinc_add_7_30_n_328));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1919__5115(.A1
       (addinc_add_7_30_n_276), .A2 (n_842), .B1
       (addinc_add_7_30_n_309), .X (addinc_add_7_30_n_327));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1920__7482(.A1 (n_842), .A2
       (addinc_add_7_30_n_284), .B1 (addinc_add_7_30_n_316), .X
       (addinc_add_7_30_n_326));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1921__4733(.A1
       (addinc_add_7_30_n_275), .A2 (n_842), .B1
       (addinc_add_7_30_n_317), .Y (addinc_add_7_30_n_325));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1922__6161(.A1_N
       (addinc_add_7_30_n_223), .A2_N (addinc_add_7_30_n_14), .B1
       (addinc_add_7_30_n_223), .B2 (addinc_add_7_30_n_14), .X (S[2]));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1923__9315(.A (n_853), .B
       (addinc_add_7_30_n_17), .Y (addinc_add_7_30_n_323));
  sky130_fd_sc_hd__mux2_2 addinc_add_7_30_g1924__9945(.A0 (n_561), .A1
       (n_562), .S (addinc_add_7_30_n_162), .X (S[4]));
  sky130_fd_sc_hd__a31o_1 addinc_add_7_30_g1925__2883(.A1 (n_562), .A2
       (addinc_add_7_30_n_211), .A3 (n_803), .B1
       (addinc_add_7_30_n_297), .X (addinc_add_7_30_n_329));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1927__1666(.A (n_824), .B
       (addinc_add_7_30_n_254), .Y (addinc_add_7_30_n_320));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1929__7410(.A1
       (addinc_add_7_30_n_291), .A2 (addinc_add_7_30_n_207), .B1
       (addinc_add_7_30_n_260), .X (addinc_add_7_30_n_317));
  sky130_fd_sc_hd__o21ai_2 addinc_add_7_30_g1930__6417(.A1
       (addinc_add_7_30_n_103), .A2 (addinc_add_7_30_n_290), .B1
       (addinc_add_7_30_n_107), .Y (addinc_add_7_30_n_316));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1931__5477(.A1 (n_843), .A2
       (n_713), .B1 (n_592), .Y (addinc_add_7_30_n_315));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1932__2398(.A1 (n_843),
       .A2 (n_827), .B1_N (addinc_add_7_30_n_154), .Y
       (addinc_add_7_30_n_314));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1933__5107(.A1 (n_640), .A2
       (n_529), .B1 (addinc_add_7_30_n_250), .Y
       (addinc_add_7_30_n_313));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1937(.A (n_842), .Y
       (addinc_add_7_30_n_311));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1938__4319(.A1_N
       (addinc_add_7_30_n_192), .A2_N (addinc_add_7_30_n_293), .B1
       (addinc_add_7_30_n_192), .B2 (addinc_add_7_30_n_293), .X (S[1]));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1940__8428(.A1
       (addinc_add_7_30_n_261), .A2 (addinc_add_7_30_n_290), .B1
       (addinc_add_7_30_n_296), .Y (addinc_add_7_30_n_309));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1941__5526(.A1
       (addinc_add_7_30_n_265), .A2 (addinc_add_7_30_n_287), .B1
       (addinc_add_7_30_n_300), .Y (addinc_add_7_30_n_308));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1942__6783(.A1 (n_640), .A2
       (addinc_add_7_30_n_262), .B1 (addinc_add_7_30_n_298), .Y
       (addinc_add_7_30_n_307));
  sky130_fd_sc_hd__o211ai_1 addinc_add_7_30_g1943__3680(.A1
       (addinc_add_7_30_n_263), .A2 (addinc_add_7_30_n_290), .B1
       (addinc_add_7_30_n_119), .C1 (addinc_add_7_30_n_283), .Y
       (addinc_add_7_30_n_306));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1947__1705(.A
       (addinc_add_7_30_n_294), .B (addinc_add_7_30_n_280), .Y
       (addinc_add_7_30_n_304));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1949__5122(.A1
       (addinc_add_7_30_n_23), .A2 (addinc_add_7_30_n_248), .B1
       (addinc_add_7_30_n_118), .Y (addinc_add_7_30_n_303));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1950__8246(.A
       (addinc_add_7_30_n_264), .B (addinc_add_7_30_n_272), .Y
       (addinc_add_7_30_n_302));
  sky130_fd_sc_hd__a21boi_0 addinc_add_7_30_g1951__7098(.A1 (n_796),
       .A2 (addinc_add_7_30_n_132), .B1_N (n_846), .Y
       (addinc_add_7_30_n_301));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1952__6131(.A1 (n_592),
       .A2 (n_825), .B1_N (n_826), .Y (addinc_add_7_30_n_300));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1953__1881(.A
       (addinc_add_7_30_n_284), .B (n_706), .X (addinc_add_7_30_n_299));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1954__5115(.A1
       (addinc_add_7_30_n_93), .A2 (addinc_add_7_30_n_249), .B1
       (addinc_add_7_30_n_12), .Y (addinc_add_7_30_n_298));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1955__7482(.A1
       (addinc_add_7_30_n_29), .A2 (n_803), .B1
       (addinc_add_7_30_n_146), .X (addinc_add_7_30_n_297));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1956__4733(.A1
       (addinc_add_7_30_n_260), .A2 (addinc_add_7_30_n_215), .B1
       (addinc_add_7_30_n_237), .Y (addinc_add_7_30_n_296));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1959(.A (n_818), .Y
       (addinc_add_7_30_n_293));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1960(.A
       (addinc_add_7_30_n_291), .Y (addinc_add_7_30_n_290));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1963(.A (n_838), .Y
       (addinc_add_7_30_n_287));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1966__6161(.A1
       (addinc_add_7_30_n_250), .A2 (addinc_add_7_30_n_24), .B1
       (addinc_add_7_30_n_242), .Y (addinc_add_7_30_n_286));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1968__9945(.A
       (addinc_add_7_30_n_282), .B (n_855), .Y (addinc_add_7_30_n_294));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1970__2346(.A
       (addinc_add_7_30_n_279), .B (n_847), .Y (addinc_add_7_30_n_291));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1971__1666(.A
       (addinc_add_7_30_n_281), .B (addinc_add_7_30_n_239), .Y
       (addinc_add_7_30_n_33));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1973__6417(.A
       (addinc_add_7_30_n_260), .B (addinc_add_7_30_n_130), .Y
       (addinc_add_7_30_n_283));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1974__5477(.A
       (addinc_add_7_30_n_29), .B (n_864), .Y (addinc_add_7_30_n_282));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1975__2398(.A
       (addinc_add_7_30_n_247), .B (addinc_add_7_30_n_196), .Y
       (addinc_add_7_30_n_281));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1976__5107(.A
       (addinc_add_7_30_n_31), .B (addinc_add_7_30_n_267), .Y
       (addinc_add_7_30_n_280));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1977__6260(.A (n_796), .B
       (addinc_add_7_30_n_175), .Y (addinc_add_7_30_n_279));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1979__8428(.A
       (addinc_add_7_30_n_103), .B (addinc_add_7_30_n_256), .Y
       (addinc_add_7_30_n_284));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1982__5526(.A
       (addinc_add_7_30_n_95), .B (n_647), .Y (addinc_add_7_30_n_271));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1984__3680(.A
       (addinc_add_7_30_n_247), .B (n_657), .Y (addinc_add_7_30_n_269));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1985__1617(.A (n_850), .B
       (addinc_add_7_30_n_265), .Y (addinc_add_7_30_n_268));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1986__2802(.A
       (addinc_add_7_30_n_261), .B (n_650), .Y (addinc_add_7_30_n_276));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1987__1705(.A (n_651), .B
       (addinc_add_7_30_n_207), .X (addinc_add_7_30_n_275));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1988__5122(.A
       (addinc_add_7_30_n_263), .B (n_650), .Y (addinc_add_7_30_n_274));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1989__8246(.A (n_712), .B
       (n_840), .Y (addinc_add_7_30_n_272));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1996__7098(.A (n_864), .B
       (addinc_add_7_30_n_211), .X (addinc_add_7_30_n_254));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1997__6131(.A
       (addinc_add_7_30_n_23), .B_N (addinc_add_7_30_n_15), .Y
       (addinc_add_7_30_n_253));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1999__5115(.A
       (addinc_add_7_30_n_210), .B (addinc_add_7_30_n_208), .Y
       (addinc_add_7_30_n_251));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2000__7482(.A
       (addinc_add_7_30_n_24), .B (addinc_add_7_30_n_25), .Y
       (addinc_add_7_30_n_267));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2002__6161(.A (n_713), .B
       (n_825), .Y (addinc_add_7_30_n_265));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2003__9315(.A (n_707), .B
       (addinc_add_7_30_n_132), .Y (addinc_add_7_30_n_264));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2004__9945(.A
       (addinc_add_7_30_n_207), .B (addinc_add_7_30_n_130), .Y
       (addinc_add_7_30_n_263));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g2005__2883(.A
       (addinc_add_7_30_n_93), .B_N (n_529), .Y
       (addinc_add_7_30_n_262));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2006__2346(.A
       (addinc_add_7_30_n_215), .B (addinc_add_7_30_n_207), .Y
       (addinc_add_7_30_n_261));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g2007__1666(.A1
       (addinc_add_7_30_n_107), .A2 (addinc_add_7_30_n_138), .B1
       (addinc_add_7_30_n_160), .Y (addinc_add_7_30_n_260));
  sky130_fd_sc_hd__nand4_1 addinc_add_7_30_g2008__7410(.A
       (addinc_add_7_30_n_149), .B (addinc_add_7_30_n_157), .C
       (addinc_add_7_30_n_129), .D (n_776), .Y (addinc_add_7_30_n_31));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2010__5477(.A (n_707), .B
       (addinc_add_7_30_n_175), .Y (addinc_add_7_30_n_256));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2012(.A
       (addinc_add_7_30_n_250), .Y (addinc_add_7_30_n_249));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2014(.A
       (addinc_add_7_30_n_30), .Y (addinc_add_7_30_n_248));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2017__2398(.A
       (addinc_add_7_30_n_167), .B (addinc_add_7_30_n_202), .Y
       (addinc_add_7_30_n_244));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g2019__6260(.A1
       (addinc_add_7_30_n_101), .A2 (addinc_add_7_30_n_12), .B1
       (addinc_add_7_30_n_11), .Y (addinc_add_7_30_n_242));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g2022__5526(.A1
       (addinc_add_7_30_n_129), .A2 (addinc_add_7_30_n_113), .B1
       (addinc_add_7_30_n_122), .Y (addinc_add_7_30_n_239));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g2024__3680(.A1
       (addinc_add_7_30_n_110), .A2 (addinc_add_7_30_n_119), .B1
       (addinc_add_7_30_n_123), .Y (addinc_add_7_30_n_237));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2027__1705(.A
       (addinc_add_7_30_n_6), .B (addinc_add_7_30_n_198), .Y
       (addinc_add_7_30_n_250));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2028__5122(.A
       (addinc_add_7_30_n_164), .B (addinc_add_7_30_n_7), .Y
       (addinc_add_7_30_n_30));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2029__8246(.A
       (addinc_add_7_30_n_2), .B (addinc_add_7_30_n_165), .Y
       (addinc_add_7_30_n_247));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2032__1881(.A
       (addinc_add_7_30_n_199), .B (n_865), .Y (addinc_add_7_30_n_29));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2033(.A
       (addinc_add_7_30_n_232), .Y (addinc_add_7_30_n_233));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2034(.A
       (addinc_add_7_30_n_230), .Y (addinc_add_7_30_n_231));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2036(.A
       (addinc_add_7_30_n_226), .Y (addinc_add_7_30_n_227));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2037(.A
       (addinc_add_7_30_n_224), .Y (addinc_add_7_30_n_225));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2038(.A
       (addinc_add_7_30_n_221), .Y (addinc_add_7_30_n_222));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2039(.A (n_701), .Y
       (addinc_add_7_30_n_220));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2040(.A
       (addinc_add_7_30_n_217), .Y (addinc_add_7_30_n_218));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2041(.A
       (addinc_add_7_30_n_213), .Y (addinc_add_7_30_n_214));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2042(.A
       (addinc_add_7_30_n_210), .Y (addinc_add_7_30_n_211));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2043(.A
       (addinc_add_7_30_n_208), .Y (addinc_add_7_30_n_209));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2046__5115(.A
       (addinc_add_7_30_n_9), .B (addinc_add_7_30_n_153), .Y
       (addinc_add_7_30_n_203));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2047__7482(.A (n_776), .B
       (addinc_add_7_30_n_94), .Y (addinc_add_7_30_n_202));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2048__4733(.A
       (addinc_add_7_30_n_135), .B (n_854), .Y (addinc_add_7_30_n_201));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2049__6161(.A
       (addinc_add_7_30_n_129), .B (addinc_add_7_30_n_102), .Y
       (addinc_add_7_30_n_200));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2050__9315(.A
       (addinc_add_7_30_n_120), .B (addinc_add_7_30_n_104), .Y
       (addinc_add_7_30_n_199));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2051__9945(.A
       (addinc_add_7_30_n_135), .B (addinc_add_7_30_n_147), .Y
       (addinc_add_7_30_n_198));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2053__2346(.A (n_846), .B
       (addinc_add_7_30_n_132), .Y (addinc_add_7_30_n_232));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2054__1666(.A_N
       (addinc_add_7_30_n_103), .B (addinc_add_7_30_n_107), .Y
       (addinc_add_7_30_n_230));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g2056__6417(.A
       (addinc_add_7_30_n_112), .B (addinc_add_7_30_n_115), .X
       (addinc_add_7_30_n_197));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2057__5477(.A_N
       (addinc_add_7_30_n_138), .B (addinc_add_7_30_n_160), .Y
       (addinc_add_7_30_n_226));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2058__2398(.A_N
       (addinc_add_7_30_n_151), .B (n_795), .Y (addinc_add_7_30_n_224));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g2059__5107(.A
       (addinc_add_7_30_n_109), .B (n_809), .X (addinc_add_7_30_n_223));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2060__6260(.A
       (addinc_add_7_30_n_116), .B (addinc_add_7_30_n_133), .Y
       (addinc_add_7_30_n_221));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2062__8428(.A_N
       (addinc_add_7_30_n_140), .B (addinc_add_7_30_n_10), .Y
       (addinc_add_7_30_n_217));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2063__5526(.A_N
       (addinc_add_7_30_n_146), .B (n_803), .Y (addinc_add_7_30_n_216));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g2064__6783(.A
       (addinc_add_7_30_n_128), .B_N (n_776), .Y
       (addinc_add_7_30_n_196));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g2065__3680(.A
       (addinc_add_7_30_n_110), .B_N (addinc_add_7_30_n_130), .Y
       (addinc_add_7_30_n_215));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2066__1617(.A_N
       (addinc_add_7_30_n_110), .B (addinc_add_7_30_n_123), .Y
       (addinc_add_7_30_n_213));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2067__2802(.A (n_865), .B
       (addinc_add_7_30_n_104), .Y (addinc_add_7_30_n_212));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2068__1705(.A (n_787), .B
       (addinc_add_7_30_n_104), .Y (addinc_add_7_30_n_210));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2069__5122(.A
       (addinc_add_7_30_n_149), .B (addinc_add_7_30_n_157), .Y
       (addinc_add_7_30_n_208));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2070__8246(.A
       (addinc_add_7_30_n_103), .B (addinc_add_7_30_n_138), .Y
       (addinc_add_7_30_n_207));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2074(.A
       (addinc_add_7_30_n_194), .Y (addinc_add_7_30_n_195));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2075(.A
       (addinc_add_7_30_n_190), .Y (addinc_add_7_30_n_191));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2076(.A
       (addinc_add_7_30_n_188), .Y (addinc_add_7_30_n_189));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2077(.A
       (addinc_add_7_30_n_185), .Y (addinc_add_7_30_n_186));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2079(.A
       (addinc_add_7_30_n_177), .Y (addinc_add_7_30_n_178));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2080(.A
       (addinc_add_7_30_n_172), .Y (addinc_add_7_30_n_173));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2081(.A
       (addinc_add_7_30_n_169), .Y (addinc_add_7_30_n_170));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2082__1881(.A
       (addinc_add_7_30_n_155), .B (addinc_add_7_30_n_117), .Y
       (addinc_add_7_30_n_168));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2083__5115(.A
       (addinc_add_7_30_n_96), .B (n_803), .Y (addinc_add_7_30_n_167));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2085__4733(.A
       (addinc_add_7_30_n_157), .B (addinc_add_7_30_n_105), .Y
       (addinc_add_7_30_n_165));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2086__6161(.A
       (addinc_add_7_30_n_158), .B (addinc_add_7_30_n_111), .Y
       (addinc_add_7_30_n_164));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2088__9945(.A_N
       (addinc_add_7_30_n_159), .B (addinc_add_7_30_n_7), .Y
       (addinc_add_7_30_n_194));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2089__2883(.A (n_636), .B
       (n_657), .Y (addinc_add_7_30_n_193));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2090__2346(.A
       (addinc_add_7_30_n_28), .B (addinc_add_7_30_n_142), .Y
       (addinc_add_7_30_n_192));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2091__1666(.A
       (addinc_add_7_30_n_0), .B (addinc_add_7_30_n_9), .Y
       (addinc_add_7_30_n_190));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2092__7410(.A_N
       (addinc_add_7_30_n_156), .B (addinc_add_7_30_n_3), .Y
       (addinc_add_7_30_n_188));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2093__6417(.A
       (addinc_add_7_30_n_12), .B (addinc_add_7_30_n_94), .Y
       (addinc_add_7_30_n_187));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2094__5477(.A_N
       (addinc_add_7_30_n_23), .B (addinc_add_7_30_n_118), .Y
       (addinc_add_7_30_n_185));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2095__2398(.A
       (addinc_add_7_30_n_6), .B (addinc_add_7_30_n_135), .Y
       (addinc_add_7_30_n_184));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2096__5107(.A (n_812), .B
       (n_808), .Y (addinc_add_7_30_n_183));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2097__6260(.A
       (addinc_add_7_30_n_148), .B (addinc_add_7_30_n_96), .Y
       (addinc_add_7_30_n_182));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2100__8428(.A
       (addinc_add_7_30_n_106), .B (addinc_add_7_30_n_149), .Y
       (addinc_add_7_30_n_180));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2101__5526(.A_N
       (addinc_add_7_30_n_124), .B (n_854), .Y (addinc_add_7_30_n_179));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2102__6783(.A
       (addinc_add_7_30_n_154), .B (n_827), .Y (addinc_add_7_30_n_177));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2103__3680(.A
       (addinc_add_7_30_n_11), .B (addinc_add_7_30_n_102), .Y
       (addinc_add_7_30_n_176));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2104__1617(.A
       (addinc_add_7_30_n_121), .B (n_787), .Y (addinc_add_7_30_n_162));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2105__2802(.A (n_780), .B
       (addinc_add_7_30_n_152), .Y (addinc_add_7_30_n_175));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2106__1705(.A
       (addinc_add_7_30_n_2), .B (addinc_add_7_30_n_157), .Y
       (addinc_add_7_30_n_174));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2107__5122(.A (n_826), .B
       (n_825), .Y (addinc_add_7_30_n_172));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2108__8246(.A_N
       (addinc_add_7_30_n_122), .B (addinc_add_7_30_n_129), .Y
       (addinc_add_7_30_n_171));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2109__7098(.A
       (addinc_add_7_30_n_119), .B (addinc_add_7_30_n_130), .Y
       (addinc_add_7_30_n_169));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2111(.A
       (addinc_add_7_30_n_158), .Y (addinc_add_7_30_n_159));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2112(.A
       (addinc_add_7_30_n_155), .Y (addinc_add_7_30_n_156));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2113(.A
       (addinc_add_7_30_n_153), .Y (addinc_add_7_30_n_154));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2114(.A (n_790), .Y
       (addinc_add_7_30_n_151));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2115(.A
       (addinc_add_7_30_n_147), .Y (addinc_add_7_30_n_148));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2116(.A (n_787), .Y
       (addinc_add_7_30_n_144));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2117(.A (n_820), .Y
       (addinc_add_7_30_n_142));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2118(.A (n_859), .Y
       (addinc_add_7_30_n_140));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2120(.A
       (addinc_add_7_30_n_13), .Y (addinc_add_7_30_n_133));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2121(.A (n_780), .Y
       (addinc_add_7_30_n_132));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2123(.A
       (addinc_add_7_30_n_129), .Y (addinc_add_7_30_n_128));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2129__6131(.A (n_22), .B
       (n_33), .Y (addinc_add_7_30_n_161));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2131__1881(.A (B[29]), .B
       (A[29]), .Y (addinc_add_7_30_n_160));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2133__5115(.A (n_615), .B
       (addinc_add_7_30_n_46), .Y (addinc_add_7_30_n_158));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2135__7482(.A (n_536), .B
       (n_532), .Y (addinc_add_7_30_n_157));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2136__4733(.A (n_547), .B
       (n_516), .Y (addinc_add_7_30_n_155));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2137__6161(.A
       (addinc_add_7_30_n_81), .B (addinc_add_7_30_n_55), .Y
       (addinc_add_7_30_n_153));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2138__9315(.A (n_33), .B
       (n_22), .Y (addinc_add_7_30_n_152));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2140__2883(.A (n_579), .B
       (n_576), .Y (addinc_add_7_30_n_149));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2141__2346(.A (n_550), .B
       (n_553), .Y (addinc_add_7_30_n_147));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2142__1666(.A (n_797), .B
       (n_800), .Y (addinc_add_7_30_n_146));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2148__5107(.A (A[29]), .B
       (B[29]), .Y (addinc_add_7_30_n_138));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2150__4319(.A (n_594), .B
       (n_585), .Y (addinc_add_7_30_n_135));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2154__6783(.A
       (addinc_add_7_30_n_39), .B (addinc_add_7_30_n_58), .Y
       (addinc_add_7_30_n_130));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2155__3680(.A
       (addinc_add_7_30_n_52), .B (addinc_add_7_30_n_51), .Y
       (addinc_add_7_30_n_129));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2157(.A
       (addinc_add_7_30_n_120), .Y (addinc_add_7_30_n_121));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2158(.A
       (addinc_add_7_30_n_117), .Y (addinc_add_7_30_n_118));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2159(.A (n_793), .Y
       (addinc_add_7_30_n_116));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2162(.A
       (addinc_add_7_30_n_111), .Y (addinc_add_7_30_n_112));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2165(.A (n_807), .Y
       (addinc_add_7_30_n_109));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2166(.A
       (addinc_add_7_30_n_105), .Y (addinc_add_7_30_n_106));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2169(.A
       (addinc_add_7_30_n_102), .Y (addinc_add_7_30_n_101));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2170(.A (n_809), .Y
       (addinc_add_7_30_n_97));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2171(.A
       (addinc_add_7_30_n_96), .Y (addinc_add_7_30_n_95));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2172(.A
       (addinc_add_7_30_n_94), .Y (addinc_add_7_30_n_93));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2180__7098(.A
       (addinc_add_7_30_n_67), .B (n_535), .Y (addinc_add_7_30_n_124));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2181__6131(.A (B[31]), .B
       (A[31]), .Y (addinc_add_7_30_n_123));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2182__1881(.A
       (addinc_add_7_30_n_51), .B (addinc_add_7_30_n_52), .Y
       (addinc_add_7_30_n_122));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2184__5115(.A (n_781), .B
       (n_784), .Y (addinc_add_7_30_n_120));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2186__7482(.A (B[30]), .B
       (A[30]), .Y (addinc_add_7_30_n_119));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2187__4733(.A (n_654), .B
       (addinc_add_7_30_n_85), .Y (addinc_add_7_30_n_117));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2189__6161(.A
       (addinc_add_7_30_n_84), .B (n_567), .Y (addinc_add_7_30_n_115));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2190__9315(.A (n_770), .B
       (n_773), .Y (addinc_add_7_30_n_113));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2191__9945(.A (n_567), .B
       (addinc_add_7_30_n_84), .Y (addinc_add_7_30_n_111));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2192__2883(.A (A[31]), .B
       (B[31]), .Y (addinc_add_7_30_n_110));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2193__2346(.A
       (addinc_add_7_30_n_86), .B (addinc_add_7_30_n_72), .Y
       (addinc_add_7_30_n_28));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2195__7410(.A (n_25), .B
       (n_45), .Y (addinc_add_7_30_n_107));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2196__6417(.A (n_576), .B
       (n_579), .Y (addinc_add_7_30_n_105));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2197__5477(.A (n_520), .B
       (n_511), .Y (addinc_add_7_30_n_104));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2198__2398(.A (n_45), .B
       (n_25), .Y (addinc_add_7_30_n_103));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2200__5107(.A (n_513), .B
       (n_507), .Y (addinc_add_7_30_n_102));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2201__6260(.A
       (addinc_add_7_30_n_55), .B (addinc_add_7_30_n_81), .Y
       (addinc_add_7_30_n_100));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2202__4319(.A
       (addinc_add_7_30_n_69), .B (addinc_add_7_30_n_56), .Y
       (addinc_add_7_30_n_99));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2204__5526(.A (n_553), .B
       (n_550), .Y (addinc_add_7_30_n_96));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2205__6783(.A (n_624), .B
       (n_582), .Y (addinc_add_7_30_n_94));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2214(.A (n_11), .Y
       (addinc_add_7_30_n_81));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2228(.A (n_39), .Y
       (addinc_add_7_30_n_72));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2234(.A (n_23), .Y
       (addinc_add_7_30_n_69));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2250(.A (B[30]), .Y
       (addinc_add_7_30_n_58));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2255(.A (n_14), .Y
       (addinc_add_7_30_n_56));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2256(.A (n_32), .Y
       (addinc_add_7_30_n_55));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2264(.A (n_27), .Y
       (addinc_add_7_30_n_49));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2277(.A (A[30]), .Y
       (addinc_add_7_30_n_39));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g2__1617(.A
       (addinc_add_7_30_n_304), .B (addinc_add_7_30_n_286), .X
       (addinc_add_7_30_n_27));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g2286__1705(.A
       (addinc_add_7_30_n_135), .B (addinc_add_7_30_n_96), .X
       (addinc_add_7_30_n_25));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g2287__5122(.A
       (addinc_add_7_30_n_94), .B (addinc_add_7_30_n_102), .X
       (addinc_add_7_30_n_24));
  sky130_fd_sc_hd__and2_2 addinc_add_7_30_g2288__8246(.A
       (addinc_add_7_30_n_85), .B (n_654), .X (addinc_add_7_30_n_23));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2289__7098(.A_N
       (addinc_add_7_30_n_394), .B (addinc_add_7_30_n_226), .Y
       (addinc_add_7_30_n_22));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2290__6131(.A_N
       (addinc_add_7_30_n_391), .B (addinc_add_7_30_n_217), .Y
       (addinc_add_7_30_n_21));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2292__5115(.A_N
       (addinc_add_7_30_n_383), .B (addinc_add_7_30_n_185), .Y
       (addinc_add_7_30_n_19));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2293__7482(.A_N
       (addinc_add_7_30_n_376), .B (addinc_add_7_30_n_188), .Y
       (addinc_add_7_30_n_18));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2294__4733(.A_N
       (addinc_add_7_30_n_267), .B (addinc_add_7_30_n_33), .Y
       (addinc_add_7_30_n_17));
  sky130_fd_sc_hd__nor2b_4 addinc_add_7_30_g2296__9315(.A
       (addinc_add_7_30_n_159), .B_N (addinc_add_7_30_n_115), .Y
       (addinc_add_7_30_n_15));
  sky130_fd_sc_hd__o21ba_2 addinc_add_7_30_g2297__9945(.A1
       (addinc_add_7_30_n_142), .A2 (addinc_add_7_30_n_293), .B1_N
       (addinc_add_7_30_n_28), .X (addinc_add_7_30_n_14));
  sky130_fd_sc_hd__and2b_1 addinc_add_7_30_g2298__2883(.A_N (A[24]), .B
       (n_587), .X (addinc_add_7_30_n_13));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2299__2346(.A (n_582), .B
       (n_624), .X (addinc_add_7_30_n_12));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2300__1666(.A (n_507), .B
       (n_513), .X (addinc_add_7_30_n_11));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2301__7410(.A (n_856), .B
       (addinc_add_7_30_n_49), .X (addinc_add_7_30_n_10));
  sky130_fd_sc_hd__nand2b_4 addinc_add_7_30_g2302__6417(.A_N (A[21]),
       .B (n_539), .Y (addinc_add_7_30_n_9));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2306__2398(.A
       (addinc_add_7_30_n_46), .B (n_615), .X (addinc_add_7_30_n_7));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2307__5107(.A (n_585), .B
       (n_594), .X (addinc_add_7_30_n_6));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2310__8428(.A (n_516), .B
       (n_548), .X (addinc_add_7_30_n_3));
  sky130_fd_sc_hd__or2_2 addinc_add_7_30_g2311__5526(.A (n_532), .B
       (n_536), .X (addinc_add_7_30_n_2));
  sky130_fd_sc_hd__or2b_1 addinc_add_7_30_g2313__3680(.A (n_539), .B_N
       (A[21]), .X (addinc_add_7_30_n_0));
  sky130_fd_sc_hd__fa_1 addinc_add_7_30_g2315__1617(.A (n_64), .B
       (n_38), .CIN (n_42), .COUT (UNCONNECTED), .SUM (S[0]));
  sky130_fd_sc_hd__inv_2 fopt2316(.A (B[15]), .Y (n_507));
  sky130_fd_sc_hd__inv_2 fopt2318(.A (B[5]), .Y (n_511));
  sky130_fd_sc_hd__inv_2 fopt2320(.A (A[15]), .Y (n_513));
  sky130_fd_sc_hd__inv_1 fopt2321(.A (B[19]), .Y (n_516));
  sky130_fd_sc_hd__inv_2 fopt2324(.A (A[5]), .Y (n_520));
  sky130_fd_sc_hd__clkbuf_1 fopt1(.A (addinc_add_7_30_n_25), .X
       (n_529));
  sky130_fd_sc_hd__inv_2 fopt2331(.A (B[9]), .Y (n_532));
  sky130_fd_sc_hd__clkinv_2 fopt2333(.A (A[7]), .Y (n_535));
  sky130_fd_sc_hd__inv_2 fopt2334(.A (A[9]), .Y (n_536));
  sky130_fd_sc_hd__inv_2 fopt2337(.A (B[21]), .Y (n_539));
  sky130_fd_sc_hd__inv_2 fopt2338(.A (B[3]), .Y (n_542));
  sky130_fd_sc_hd__inv_1 fopt2341(.A (A[19]), .Y (n_547));
  sky130_fd_sc_hd__inv_2 fopt2342(.A (A[19]), .Y (n_548));
  sky130_fd_sc_hd__inv_2 fopt2343(.A (B[12]), .Y (n_550));
  sky130_fd_sc_hd__inv_2 fopt2346(.A (A[12]), .Y (n_553));
  sky130_fd_sc_hd__inv_2 fopt2347(.A (B[2]), .Y (n_556));
  sky130_fd_sc_hd__inv_2 fopt2(.A (n_562), .Y (n_561));
  sky130_fd_sc_hd__buf_2 fopt3(.A (n_824), .X (n_562));
  sky130_fd_sc_hd__inv_2 fopt2352(.A (A[16]), .Y (n_567));
  sky130_fd_sc_hd__inv_2 fopt2359(.A (B[8]), .Y (n_576));
  sky130_fd_sc_hd__inv_2 fopt2361(.A (A[8]), .Y (n_579));
  sky130_fd_sc_hd__inv_2 fopt2362(.A (B[14]), .Y (n_582));
  sky130_fd_sc_hd__inv_2 fopt2364(.A (B[13]), .Y (n_585));
  sky130_fd_sc_hd__inv_2 fopt2371(.A (A[13]), .Y (n_594));
  sky130_fd_sc_hd__inv_1 fopt2375(.A (n_608), .Y (n_607));
  sky130_fd_sc_hd__inv_2 fopt2376(.A (n_711), .Y (n_608));
  sky130_fd_sc_hd__inv_2 fopt2377(.A (A[17]), .Y (n_615));
  sky130_fd_sc_hd__clkinv_2 fopt2379(.A (n_710), .Y (n_618));
  sky130_fd_sc_hd__inv_2 fopt2380(.A (addinc_add_7_30_n_389), .Y
       (n_620));
  sky130_fd_sc_hd__inv_2 fopt2381(.A (n_716), .Y (n_622));
  sky130_fd_sc_hd__inv_2 fopt2382(.A (A[14]), .Y (n_624));
  sky130_fd_sc_hd__clkinv_2 fopt2384(.A (addinc_add_7_30_n_370), .Y
       (n_627));
  sky130_fd_sc_hd__inv_2 fopt2385(.A (addinc_add_7_30_n_377), .Y
       (n_629));
  sky130_fd_sc_hd__inv_2 fopt2386(.A (addinc_add_7_30_n_384), .Y
       (n_631));
  sky130_fd_sc_hd__inv_2 fopt2387(.A (addinc_add_7_30_n_387), .Y
       (n_633));
  sky130_fd_sc_hd__clkinv_1 fopt2390(.A (addinc_add_7_30_n_113), .Y
       (n_636));
  sky130_fd_sc_hd__inv_1 fopt2392(.A (n_640), .Y (n_641));
  sky130_fd_sc_hd__buf_1 fopt2393(.A (addinc_add_7_30_n_33), .X
       (n_640));
  sky130_fd_sc_hd__clkinv_1 fopt2395(.A (n_647), .Y (n_645));
  sky130_fd_sc_hd__buf_1 fopt2397(.A (addinc_add_7_30_n_31), .X
       (n_647));
  sky130_fd_sc_hd__clkbuf_1 fopt2398(.A (addinc_add_7_30_n_256), .X
       (n_650));
  sky130_fd_sc_hd__inv_2 fopt2400(.A (addinc_add_7_30_n_256), .Y
       (n_651));
  sky130_fd_sc_hd__inv_2 fopt2402(.A (B[18]), .Y (n_654));
  sky130_fd_sc_hd__buf_1 fopt2403(.A (n_776), .X (n_657));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1908_0__1705(.A
       (addinc_add_7_30_n_330), .B (addinc_add_7_30_n_27), .Y (n_661));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1861__2443(.A1 (n_661), .A2
       (addinc_add_7_30_n_302), .B1 (addinc_add_7_30_n_328), .Y
       (n_700));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2061__2444(.A_N
       (addinc_add_7_30_n_152), .B (addinc_add_7_30_n_161), .Y (n_701));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1799__2445(.A
       (addinc_add_7_30_n_425), .B (n_703), .Y (S[27]));
  sky130_fd_sc_hd__nand2_2 g1(.A (n_702), .B (n_701), .Y (n_703));
  sky130_fd_sc_hd__inv_1 g2(.A (n_700), .Y (n_702));
  sky130_fd_sc_hd__inv_4 addinc_add_7_30_g2448(.A
       (addinc_add_7_30_n_272), .Y (n_706));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2071__2449(.A
       (addinc_add_7_30_n_151), .B (addinc_add_7_30_n_13), .Y (n_707));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1857__2450(.A (n_868), .B
       (addinc_add_7_30_n_332), .Y (n_710));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g2405__2454(.A
       (addinc_add_7_30_n_330), .B (addinc_add_7_30_n_27), .Y (n_711));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2455(.A (n_850), .Y (n_712));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2456(.A (n_839), .Y (n_713));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1873__2457(.A (n_715), .B
       (addinc_add_7_30_n_315), .Y (n_716));
  sky130_fd_sc_hd__nand2_1 g2458(.A (n_711), .B (n_714), .Y (n_715));
  sky130_fd_sc_hd__and2_1 g2459(.A (n_712), .B (n_713), .X (n_714));
  sky130_fd_sc_hd__nand2_1 g9(.A (n_770), .B (n_773), .Y (n_776));
  sky130_fd_sc_hd__inv_2 g2518(.A (B[10]), .Y (n_770));
  sky130_fd_sc_hd__inv_2 g4(.A (A[10]), .Y (n_773));
  sky130_fd_sc_hd__inv_2 g2519(.A (A[3]), .Y (n_777));
  sky130_fd_sc_hd__nor2_1 g2520(.A (n_845), .B (n_779), .Y (n_780));
  sky130_fd_sc_hd__inv_1 g2521(.A (n_778), .Y (n_779));
  sky130_fd_sc_hd__clkinv_1 g2522(.A (A[26]), .Y (n_778));
  sky130_fd_sc_hd__nand2_1 g2523(.A (n_781), .B (n_784), .Y (n_787));
  sky130_fd_sc_hd__inv_2 g2526(.A (B[4]), .Y (n_781));
  sky130_fd_sc_hd__inv_2 g2529(.A (A[4]), .Y (n_784));
  sky130_fd_sc_hd__nand2_1 g2530(.A (n_794), .B (n_795), .Y (n_796));
  sky130_fd_sc_hd__nand2_1 g32(.A (n_790), .B (n_793), .Y (n_794));
  sky130_fd_sc_hd__nand2_1 g33(.A (n_788), .B (n_789), .Y (n_790));
  sky130_fd_sc_hd__inv_2 g2531(.A (B[25]), .Y (n_788));
  sky130_fd_sc_hd__inv_2 g2532(.A (A[25]), .Y (n_789));
  sky130_fd_sc_hd__nor2_1 g35(.A (n_587), .B (n_792), .Y (n_793));
  sky130_fd_sc_hd__inv_1 g2533(.A (B[24]), .Y (n_587));
  sky130_fd_sc_hd__clkinv_1 g40(.A (A[24]), .Y (n_792));
  sky130_fd_sc_hd__nand2_1 g34(.A (A[25]), .B (B[25]), .Y (n_795));
  sky130_fd_sc_hd__nand2_2 g2534(.A (n_797), .B (n_800), .Y (n_803));
  sky130_fd_sc_hd__inv_2 g5(.A (B[6]), .Y (n_797));
  sky130_fd_sc_hd__inv_2 g7(.A (A[6]), .Y (n_800));
  sky130_fd_sc_hd__nor2_1 g12(.A (n_805), .B (n_556), .Y (n_807));
  sky130_fd_sc_hd__inv_2 g2539(.A (A[2]), .Y (n_805));
  sky130_fd_sc_hd__nand2_4 g97(.A (n_814), .B (n_823), .Y (n_824));
  sky130_fd_sc_hd__inv_2 g99(.A (n_813), .Y (n_814));
  sky130_fd_sc_hd__nand3_2 g100(.A (n_810), .B (n_811), .C (n_812), .Y
       (n_813));
  sky130_fd_sc_hd__nand3_2 g101(.A (n_808), .B (addinc_add_7_30_n_28),
       .C (n_809), .Y (n_810));
  sky130_fd_sc_hd__nand2_1 g112(.A (n_777), .B (n_542), .Y (n_808));
  sky130_fd_sc_hd__nand2_1 g106(.A (n_805), .B (n_556), .Y (n_809));
  sky130_fd_sc_hd__nand2_1 g105(.A (n_807), .B (n_808), .Y (n_811));
  sky130_fd_sc_hd__or2_1 g113(.A (n_542), .B (n_777), .X (n_812));
  sky130_fd_sc_hd__nand2_2 g98(.A (n_818), .B (n_822), .Y (n_823));
  sky130_fd_sc_hd__nand3_2 g103(.A (n_815), .B (n_816), .C (n_817), .Y
       (n_818));
  sky130_fd_sc_hd__nand2_1 g109(.A (n_64), .B (n_42), .Y (n_815));
  sky130_fd_sc_hd__nand2_1 g107(.A (n_64), .B (n_38), .Y (n_816));
  sky130_fd_sc_hd__nand2_1 g108(.A (n_38), .B (n_42), .Y (n_817));
  sky130_fd_sc_hd__nor2_1 g102(.A (n_819), .B (n_821), .Y (n_822));
  sky130_fd_sc_hd__nand2_1 g104(.A (n_808), .B (n_809), .Y (n_819));
  sky130_fd_sc_hd__clkinv_1 g110(.A (n_820), .Y (n_821));
  sky130_fd_sc_hd__nand2_1 g111(.A (addinc_add_7_30_n_72), .B
       (addinc_add_7_30_n_86), .Y (n_820));
  sky130_fd_sc_hd__clkbuf_1 g2541(.A (addinc_add_7_30_n_99), .X
       (n_825));
  sky130_fd_sc_hd__clkbuf_1 g2543(.A (addinc_add_7_30_n_100), .X
       (n_827));
  sky130_fd_sc_hd__nand2_4 g77(.A (n_835), .B (n_841), .Y (n_842));
  sky130_fd_sc_hd__clkinv_2 g2544(.A (n_834), .Y (n_835));
  sky130_fd_sc_hd__nand3_2 g2545(.A (n_866), .B (n_861), .C
       (addinc_add_7_30_n_10), .Y (n_834));
  sky130_fd_sc_hd__nand2_2 g2546(.A (addinc_add_7_30_n_203), .B
       (addinc_add_7_30_n_0), .Y (n_592));
  sky130_fd_sc_hd__nand2_1 g89(.A (n_859), .B (addinc_add_7_30_n_99),
       .Y (n_829));
  sky130_fd_sc_hd__nand2_2 g2547(.A (n_838), .B (n_840), .Y (n_841));
  sky130_fd_sc_hd__nand2_2 g83(.A (n_836), .B (n_837), .Y (n_838));
  sky130_fd_sc_hd__nand2_1 g84(.A (addinc_add_7_30_n_30), .B (n_849),
       .Y (n_836));
  sky130_fd_sc_hd__and2_1 g86(.A (addinc_add_7_30_n_168), .B
       (addinc_add_7_30_n_3), .X (n_837));
  sky130_fd_sc_hd__nor2_1 g82(.A (n_829), .B (n_839), .Y (n_840));
  sky130_fd_sc_hd__nand2_1 g2548(.A (addinc_add_7_30_n_100), .B
       (addinc_add_7_30_n_9), .Y (n_839));
  sky130_fd_sc_hd__buf_1 fopt2549(.A (n_838), .X (n_843));
  sky130_fd_sc_hd__inv_2 g2550(.A (n_844), .Y (n_845));
  sky130_fd_sc_hd__inv_2 g2551(.A (B[26]), .Y (n_844));
  sky130_fd_sc_hd__o21a_1 g2552(.A1 (addinc_add_7_30_n_152), .A2
       (n_846), .B1 (addinc_add_7_30_n_161), .X (n_847));
  sky130_fd_sc_hd__nand2_1 g17(.A (n_845), .B (n_779), .Y (n_846));
  sky130_fd_sc_hd__nand2_1 g2554(.A (n_849), .B (addinc_add_7_30_n_15),
       .Y (n_850));
  sky130_fd_sc_hd__nor2_1 g2555(.A (addinc_add_7_30_n_156), .B
       (addinc_add_7_30_n_23), .Y (n_849));
  sky130_fd_sc_hd__nand2_2 g2556(.A (n_824), .B (n_852), .Y (n_853));
  sky130_fd_sc_hd__inv_1 g2557(.A (n_869), .Y (n_852));
  sky130_fd_sc_hd__a21oi_1 g21(.A1 (n_854), .A2
       (addinc_add_7_30_n_146), .B1 (addinc_add_7_30_n_124), .Y
       (n_855));
  sky130_fd_sc_hd__nand2_2 g22(.A (addinc_add_7_30_n_67), .B (n_535),
       .Y (n_854));
  sky130_fd_sc_hd__nand2_2 g8(.A (addinc_add_7_30_n_49), .B (n_856), .Y
       (n_859));
  sky130_fd_sc_hd__inv_2 g2561(.A (B[23]), .Y (n_856));
  sky130_fd_sc_hd__nand2b_1 g2562(.A_N (addinc_add_7_30_n_140), .B
       (n_860), .Y (n_861));
  sky130_fd_sc_hd__nor2_1 g2563(.A (addinc_add_7_30_n_69), .B
       (addinc_add_7_30_n_56), .Y (n_860));
  sky130_fd_sc_hd__inv_1 g2564(.A (n_860), .Y (n_826));
  sky130_fd_sc_hd__nand2b_4 g2565(.A_N (addinc_add_7_30_n_294), .B
       (addinc_add_7_30_n_320), .Y (n_863));
  sky130_fd_sc_hd__and2_4 g2566(.A (n_803), .B (n_854), .X (n_864));
  sky130_fd_sc_hd__nand2b_1 g2567(.A_N (n_520), .B (B[5]), .Y (n_865));
  sky130_fd_sc_hd__nand2b_2 g2568(.A_N (n_829), .B (n_592), .Y (n_866));
  sky130_fd_sc_hd__a21bo_1 g2569(.A1 (n_863), .A2
       (addinc_add_7_30_n_149), .B1_N (addinc_add_7_30_n_106), .X
       (n_867));
  sky130_fd_sc_hd__nand3_1 g2570(.A (n_711), .B (n_706), .C (n_707), .Y
       (n_868));
  sky130_fd_sc_hd__nand4bb_1 g2571(.A_N (addinc_add_7_30_n_201), .B_N
       (addinc_add_7_30_n_200), .C (addinc_add_7_30_n_251), .D
       (addinc_add_7_30_n_244), .Y (n_869));
endmodule

