
//input ports
add mapped point a[31] a[31] -type PI PI
add mapped point a[30] a[30] -type PI PI
add mapped point a[29] a[29] -type PI PI
add mapped point a[28] a[28] -type PI PI
add mapped point a[27] a[27] -type PI PI
add mapped point a[26] a[26] -type PI PI
add mapped point a[25] a[25] -type PI PI
add mapped point a[24] a[24] -type PI PI
add mapped point a[23] a[23] -type PI PI
add mapped point a[22] a[22] -type PI PI
add mapped point a[21] a[21] -type PI PI
add mapped point a[20] a[20] -type PI PI
add mapped point a[19] a[19] -type PI PI
add mapped point a[18] a[18] -type PI PI
add mapped point a[17] a[17] -type PI PI
add mapped point a[16] a[16] -type PI PI
add mapped point a[15] a[15] -type PI PI
add mapped point a[14] a[14] -type PI PI
add mapped point a[13] a[13] -type PI PI
add mapped point a[12] a[12] -type PI PI
add mapped point a[11] a[11] -type PI PI
add mapped point a[10] a[10] -type PI PI
add mapped point a[9] a[9] -type PI PI
add mapped point a[8] a[8] -type PI PI
add mapped point a[7] a[7] -type PI PI
add mapped point a[6] a[6] -type PI PI
add mapped point a[5] a[5] -type PI PI
add mapped point a[4] a[4] -type PI PI
add mapped point a[3] a[3] -type PI PI
add mapped point a[2] a[2] -type PI PI
add mapped point a[1] a[1] -type PI PI
add mapped point a[0] a[0] -type PI PI
add mapped point b[31] b[31] -type PI PI
add mapped point b[30] b[30] -type PI PI
add mapped point b[29] b[29] -type PI PI
add mapped point b[28] b[28] -type PI PI
add mapped point b[27] b[27] -type PI PI
add mapped point b[26] b[26] -type PI PI
add mapped point b[25] b[25] -type PI PI
add mapped point b[24] b[24] -type PI PI
add mapped point b[23] b[23] -type PI PI
add mapped point b[22] b[22] -type PI PI
add mapped point b[21] b[21] -type PI PI
add mapped point b[20] b[20] -type PI PI
add mapped point b[19] b[19] -type PI PI
add mapped point b[18] b[18] -type PI PI
add mapped point b[17] b[17] -type PI PI
add mapped point b[16] b[16] -type PI PI
add mapped point b[15] b[15] -type PI PI
add mapped point b[14] b[14] -type PI PI
add mapped point b[13] b[13] -type PI PI
add mapped point b[12] b[12] -type PI PI
add mapped point b[11] b[11] -type PI PI
add mapped point b[10] b[10] -type PI PI
add mapped point b[9] b[9] -type PI PI
add mapped point b[8] b[8] -type PI PI
add mapped point b[7] b[7] -type PI PI
add mapped point b[6] b[6] -type PI PI
add mapped point b[5] b[5] -type PI PI
add mapped point b[4] b[4] -type PI PI
add mapped point b[3] b[3] -type PI PI
add mapped point b[2] b[2] -type PI PI
add mapped point b[1] b[1] -type PI PI
add mapped point b[0] b[0] -type PI PI
add mapped point op[2] op[2] -type PI PI
add mapped point op[1] op[1] -type PI PI
add mapped point op[0] op[0] -type PI PI
add mapped point clock clock -type PI PI
add mapped point reset reset -type PI PI
add mapped point Start_signal Start_signal -type PI PI

//output ports
add mapped point done done -type PO PO
add mapped point result[31] result[31] -type PO PO
add mapped point result[30] result[30] -type PO PO
add mapped point result[29] result[29] -type PO PO
add mapped point result[28] result[28] -type PO PO
add mapped point result[27] result[27] -type PO PO
add mapped point result[26] result[26] -type PO PO
add mapped point result[25] result[25] -type PO PO
add mapped point result[24] result[24] -type PO PO
add mapped point result[23] result[23] -type PO PO
add mapped point result[22] result[22] -type PO PO
add mapped point result[21] result[21] -type PO PO
add mapped point result[20] result[20] -type PO PO
add mapped point result[19] result[19] -type PO PO
add mapped point result[18] result[18] -type PO PO
add mapped point result[17] result[17] -type PO PO
add mapped point result[16] result[16] -type PO PO
add mapped point result[15] result[15] -type PO PO
add mapped point result[14] result[14] -type PO PO
add mapped point result[13] result[13] -type PO PO
add mapped point result[12] result[12] -type PO PO
add mapped point result[11] result[11] -type PO PO
add mapped point result[10] result[10] -type PO PO
add mapped point result[9] result[9] -type PO PO
add mapped point result[8] result[8] -type PO PO
add mapped point result[7] result[7] -type PO PO
add mapped point result[6] result[6] -type PO PO
add mapped point result[5] result[5] -type PO PO
add mapped point result[4] result[4] -type PO PO
add mapped point result[3] result[3] -type PO PO
add mapped point result[2] result[2] -type PO PO
add mapped point result[1] result[1] -type PO PO
add mapped point result[0] result[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point out/q[31]/q out_q_reg[31]/Q -type DFF DFF
add mapped point out/q[15]/q out_q_reg[15]/Q -type DFF DFF
add mapped point out/q[30]/q out_q_reg[30]/Q -type DFF DFF
add mapped point out/q[24]/q out_q_reg[24]/Q -type DFF DFF
add mapped point out/q[20]/q out_q_reg[20]/Q -type DFF DFF
add mapped point out/q[28]/q out_q_reg[28]/Q -type DFF DFF
add mapped point out/q[21]/q out_q_reg[21]/Q -type DFF DFF
add mapped point out/q[27]/q out_q_reg[27]/Q -type DFF DFF
add mapped point out/q[22]/q out_q_reg[22]/Q -type DFF DFF
add mapped point out/q[25]/q out_q_reg[25]/Q -type DFF DFF
add mapped point out/q[29]/q out_q_reg[29]/Q -type DFF DFF
add mapped point out/q[23]/q out_q_reg[23]/Q -type DFF DFF
add mapped point out/q[26]/q out_q_reg[26]/Q -type DFF DFF
add mapped point out/q[19]/q out_q_reg[19]/Q -type DFF DFF
add mapped point out/q[17]/q out_q_reg[17]/Q -type DFF DFF
add mapped point out/q[13]/q out_q_reg[13]/Q -type DFF DFF
add mapped point out/q[11]/q out_q_reg[11]/Q -type DFF DFF
add mapped point out/q[7]/q out_q_reg[7]/Q -type DFF DFF
add mapped point out/q[18]/q out_q_reg[18]/Q -type DFF DFF
add mapped point out/q[14]/q out_q_reg[14]/Q -type DFF DFF
add mapped point out/q[12]/q out_q_reg[12]/Q -type DFF DFF
add mapped point out/q[9]/q out_q_reg[9]/Q -type DFF DFF
add mapped point out/q[16]/q out_q_reg[16]/Q -type DFF DFF
add mapped point out/q[6]/q out_q_reg[6]/Q -type DFF DFF
add mapped point out/q[10]/q out_q_reg[10]/Q -type DFF DFF
add mapped point out/q[8]/q out_q_reg[8]/Q -type DFF DFF
add mapped point out/q[5]/q out_q_reg[5]/Q -type DFF DFF
add mapped point out/q[3]/q out_q_reg[3]/Q -type DFF DFF
add mapped point out/q[4]/q out_q_reg[4]/Q -type DFF DFF
add mapped point out/q[2]/q out_q_reg[2]/Q -type DFF DFF
add mapped point out/q[1]/q out_q_reg[1]/Q -type DFF DFF
add mapped point out/q[0]/q out_q_reg[0]/Q -type DFF DFF
add mapped point state[2]/q state_reg[2]/Q -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q -type DFF DFF
add mapped point donee/q[0]/q donee_q_reg[0]/Q -type DFF DFF
add mapped point in2/q[0]/q in2_q_reg[0]/Q -type DFF DFF
add mapped point start/q[0]/q start_q_reg[0]/Q -type DFF DFF
add mapped point in2/q[12]/q in2_q_reg[12]/Q -type DFF DFF
add mapped point in2/q[31]/q in2_q_reg[31]/Q -type DFF DFF
add mapped point in2/q[11]/q in2_q_reg[11]/Q -type DFF DFF
add mapped point in2/q[7]/q in2_q_reg[7]/Q -type DFF DFF
add mapped point sel/q[2]/q sel_q_reg[2]/Q -type DFF DFF
add mapped point in1/q[4]/q in1_q_reg[4]/Q -type DFF DFF
add mapped point in2/q[16]/q in2_q_reg[16]/Q -type DFF DFF
add mapped point in1/q[19]/q in1_q_reg[19]/Q -type DFF DFF
add mapped point in1/q[9]/q in1_q_reg[9]/Q -type DFF DFF
add mapped point in2/q[15]/q in2_q_reg[15]/Q -type DFF DFF
add mapped point in2/q[13]/q in2_q_reg[13]/Q -type DFF DFF
add mapped point in1/q[13]/q in1_q_reg[13]/Q -type DFF DFF
add mapped point in2/q[1]/q in2_q_reg[1]/Q -type DFF DFF
add mapped point in1/q[17]/q in1_q_reg[17]/Q -type DFF DFF
add mapped point in1/q[14]/q in1_q_reg[14]/Q -type DFF DFF
add mapped point in1/q[12]/q in1_q_reg[12]/Q -type DFF DFF
add mapped point in1/q[30]/q in1_q_reg[30]/Q -type DFF DFF
add mapped point in1/q[2]/q in1_q_reg[2]/Q -type DFF DFF
add mapped point in1/q[1]/q in1_q_reg[1]/Q -type DFF DFF
add mapped point in2/q[29]/q in2_q_reg[29]/Q -type DFF DFF
add mapped point in1/q[8]/q in1_q_reg[8]/Q -type DFF DFF
add mapped point in2/q[19]/q in2_q_reg[19]/Q -type DFF DFF
add mapped point in1/q[26]/q in1_q_reg[26]/Q -type DFF DFF
add mapped point in2/q[23]/q in2_q_reg[23]/Q -type DFF DFF
add mapped point in2/q[27]/q in2_q_reg[27]/Q -type DFF DFF
add mapped point in1/q[29]/q in1_q_reg[29]/Q -type DFF DFF
add mapped point in2/q[18]/q in2_q_reg[18]/Q -type DFF DFF
add mapped point in1/q[6]/q in1_q_reg[6]/Q -type DFF DFF
add mapped point in1/q[22]/q in1_q_reg[22]/Q -type DFF DFF
add mapped point in1/q[0]/q in1_q_reg[0]/Q -type DFF DFF
add mapped point in1/q[3]/q in1_q_reg[3]/Q -type DFF DFF
add mapped point in1/q[7]/q in1_q_reg[7]/Q -type DFF DFF
add mapped point in1/q[15]/q in1_q_reg[15]/Q -type DFF DFF
add mapped point in2/q[10]/q in2_q_reg[10]/Q -type DFF DFF
add mapped point in1/q[31]/q in1_q_reg[31]/Q -type DFF DFF
add mapped point in2/q[14]/q in2_q_reg[14]/Q -type DFF DFF
add mapped point in1/q[21]/q in1_q_reg[21]/Q -type DFF DFF
add mapped point in2/q[6]/q in2_q_reg[6]/Q -type DFF DFF
add mapped point sel/q[0]/q sel_q_reg[0]/Q -type DFF DFF
add mapped point in2/q[3]/q in2_q_reg[3]/Q -type DFF DFF
add mapped point in1/q[28]/q in1_q_reg[28]/Q -type DFF DFF
add mapped point in1/q[18]/q in1_q_reg[18]/Q -type DFF DFF
add mapped point in1/q[5]/q in1_q_reg[5]/Q -type DFF DFF
add mapped point in2/q[17]/q in2_q_reg[17]/Q -type DFF DFF
add mapped point in1/q[27]/q in1_q_reg[27]/Q -type DFF DFF
add mapped point in2/q[2]/q in2_q_reg[2]/Q -type DFF DFF
add mapped point in1/q[20]/q in1_q_reg[20]/Q -type DFF DFF
add mapped point sel/q[1]/q sel_q_reg[1]/Q -type DFF DFF
add mapped point in2/q[26]/q in2_q_reg[26]/Q -type DFF DFF
add mapped point in2/q[21]/q in2_q_reg[21]/Q -type DFF DFF
add mapped point in2/q[5]/q in2_q_reg[5]/Q -type DFF DFF
add mapped point in2/q[28]/q in2_q_reg[28]/Q -type DFF DFF
add mapped point in1/q[16]/q in1_q_reg[16]/Q -type DFF DFF
add mapped point in1/q[10]/q in1_q_reg[10]/Q -type DFF DFF
add mapped point in2/q[20]/q in2_q_reg[20]/Q -type DFF DFF
add mapped point in2/q[8]/q in2_q_reg[8]/Q -type DFF DFF
add mapped point in2/q[30]/q in2_q_reg[30]/Q -type DFF DFF
add mapped point in1/q[23]/q in1_q_reg[23]/Q -type DFF DFF
add mapped point in1/q[24]/q in1_q_reg[24]/Q -type DFF DFF
add mapped point in1/q[11]/q in1_q_reg[11]/Q -type DFF DFF
add mapped point in2/q[4]/q in2_q_reg[4]/Q -type DFF DFF
add mapped point in2/q[24]/q in2_q_reg[24]/Q -type DFF DFF
add mapped point in2/q[22]/q in2_q_reg[22]/Q -type DFF DFF
add mapped point in2/q[9]/q in2_q_reg[9]/Q -type DFF DFF
add mapped point in2/q[25]/q in2_q_reg[25]/Q -type DFF DFF
add mapped point in1/q[25]/q in1_q_reg[25]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
