
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr 14 2025 14:24:29 -03 (Apr 14 2025 17:24:29 UTC)

// Verification Directory fv/signal_32bits 

module signal_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire addinc_add_7_30_n_0, addinc_add_7_30_n_1, addinc_add_7_30_n_2,
       addinc_add_7_30_n_3, addinc_add_7_30_n_4, addinc_add_7_30_n_5,
       addinc_add_7_30_n_6, addinc_add_7_30_n_7;
  wire addinc_add_7_30_n_8, addinc_add_7_30_n_9, addinc_add_7_30_n_10,
       addinc_add_7_30_n_11, addinc_add_7_30_n_12,
       addinc_add_7_30_n_13, addinc_add_7_30_n_14, addinc_add_7_30_n_15;
  wire addinc_add_7_30_n_16, addinc_add_7_30_n_17,
       addinc_add_7_30_n_18, addinc_add_7_30_n_19,
       addinc_add_7_30_n_20, addinc_add_7_30_n_21,
       addinc_add_7_30_n_22, addinc_add_7_30_n_23;
  wire addinc_add_7_30_n_25, addinc_add_7_30_n_26,
       addinc_add_7_30_n_27, addinc_add_7_30_n_28,
       addinc_add_7_30_n_29, addinc_add_7_30_n_30,
       addinc_add_7_30_n_31, addinc_add_7_30_n_33;
  wire addinc_add_7_30_n_34, addinc_add_7_30_n_35,
       addinc_add_7_30_n_36, addinc_add_7_30_n_37,
       addinc_add_7_30_n_38, addinc_add_7_30_n_39,
       addinc_add_7_30_n_40, addinc_add_7_30_n_41;
  wire addinc_add_7_30_n_42, addinc_add_7_30_n_43,
       addinc_add_7_30_n_44, addinc_add_7_30_n_45,
       addinc_add_7_30_n_46, addinc_add_7_30_n_47,
       addinc_add_7_30_n_48, addinc_add_7_30_n_49;
  wire addinc_add_7_30_n_50, addinc_add_7_30_n_51,
       addinc_add_7_30_n_52, addinc_add_7_30_n_53,
       addinc_add_7_30_n_54, addinc_add_7_30_n_55,
       addinc_add_7_30_n_56, addinc_add_7_30_n_57;
  wire addinc_add_7_30_n_58, addinc_add_7_30_n_59,
       addinc_add_7_30_n_60, addinc_add_7_30_n_61,
       addinc_add_7_30_n_62, addinc_add_7_30_n_63,
       addinc_add_7_30_n_64, addinc_add_7_30_n_65;
  wire addinc_add_7_30_n_66, addinc_add_7_30_n_67,
       addinc_add_7_30_n_68, addinc_add_7_30_n_69,
       addinc_add_7_30_n_70, addinc_add_7_30_n_71,
       addinc_add_7_30_n_72, addinc_add_7_30_n_73;
  wire addinc_add_7_30_n_74, addinc_add_7_30_n_75,
       addinc_add_7_30_n_76, addinc_add_7_30_n_77,
       addinc_add_7_30_n_78, addinc_add_7_30_n_79,
       addinc_add_7_30_n_80, addinc_add_7_30_n_81;
  wire addinc_add_7_30_n_82, addinc_add_7_30_n_83,
       addinc_add_7_30_n_84, addinc_add_7_30_n_85,
       addinc_add_7_30_n_86, addinc_add_7_30_n_87,
       addinc_add_7_30_n_89, addinc_add_7_30_n_90;
  wire addinc_add_7_30_n_91, addinc_add_7_30_n_92,
       addinc_add_7_30_n_93, addinc_add_7_30_n_94,
       addinc_add_7_30_n_95, addinc_add_7_30_n_96,
       addinc_add_7_30_n_97, addinc_add_7_30_n_98;
  wire addinc_add_7_30_n_99, addinc_add_7_30_n_100,
       addinc_add_7_30_n_101, addinc_add_7_30_n_102,
       addinc_add_7_30_n_103, addinc_add_7_30_n_104,
       addinc_add_7_30_n_105, addinc_add_7_30_n_106;
  wire addinc_add_7_30_n_107, addinc_add_7_30_n_109,
       addinc_add_7_30_n_110, addinc_add_7_30_n_111,
       addinc_add_7_30_n_112, addinc_add_7_30_n_113,
       addinc_add_7_30_n_114, addinc_add_7_30_n_115;
  wire addinc_add_7_30_n_117, addinc_add_7_30_n_120,
       addinc_add_7_30_n_121, addinc_add_7_30_n_124,
       addinc_add_7_30_n_125, addinc_add_7_30_n_126,
       addinc_add_7_30_n_128, addinc_add_7_30_n_129;
  wire addinc_add_7_30_n_131, addinc_add_7_30_n_134,
       addinc_add_7_30_n_135, addinc_add_7_30_n_137,
       addinc_add_7_30_n_138, addinc_add_7_30_n_139,
       addinc_add_7_30_n_141, addinc_add_7_30_n_144;
  wire addinc_add_7_30_n_145, addinc_add_7_30_n_146,
       addinc_add_7_30_n_147, addinc_add_7_30_n_151,
       addinc_add_7_30_n_152, addinc_add_7_30_n_154,
       addinc_add_7_30_n_155, addinc_add_7_30_n_156;
  wire addinc_add_7_30_n_158, addinc_add_7_30_n_159,
       addinc_add_7_30_n_160, addinc_add_7_30_n_164,
       addinc_add_7_30_n_165, addinc_add_7_30_n_166,
       addinc_add_7_30_n_168, addinc_add_7_30_n_169;
  wire addinc_add_7_30_n_170, addinc_add_7_30_n_171,
       addinc_add_7_30_n_175, addinc_add_7_30_n_176,
       addinc_add_7_30_n_180, addinc_add_7_30_n_181,
       addinc_add_7_30_n_185, n_255;
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1189__2398(.A
       (addinc_add_7_30_n_72), .B (addinc_add_7_30_n_185), .X (S[31]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1190__5107(.A
       (addinc_add_7_30_n_89), .B (addinc_add_7_30_n_181), .X (S[23]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1191__6260(.A
       (addinc_add_7_30_n_68), .B (addinc_add_7_30_n_180), .X (S[27]));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1192__4319(.A1
       (addinc_add_7_30_n_7), .A2 (addinc_add_7_30_n_175), .B1
       (addinc_add_7_30_n_53), .Y (addinc_add_7_30_n_185));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1193__8428(.A
       (addinc_add_7_30_n_70), .B (addinc_add_7_30_n_175), .X (S[30]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1194__5526(.A
       (addinc_add_7_30_n_87), .B (addinc_add_7_30_n_176), .X (S[29]));
  sky130_fd_sc_hd__o221ai_1 addinc_add_7_30_g1195__6783(.A1
       (addinc_add_7_30_n_92), .A2 (addinc_add_7_30_n_171), .B1
       (addinc_add_7_30_n_16), .B2 (addinc_add_7_30_n_115), .C1
       (addinc_add_7_30_n_30), .Y (Cout));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1196__3680(.A1
       (addinc_add_7_30_n_38), .A2 (addinc_add_7_30_n_170), .B1
       (addinc_add_7_30_n_43), .Y (addinc_add_7_30_n_181));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1197__1617(.A1
       (addinc_add_7_30_n_37), .A2 (addinc_add_7_30_n_168), .B1
       (addinc_add_7_30_n_50), .Y (addinc_add_7_30_n_180));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1198__2802(.A
       (addinc_add_7_30_n_63), .B (addinc_add_7_30_n_170), .X (S[22]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1199__1705(.A
       (addinc_add_7_30_n_84), .B (addinc_add_7_30_n_169), .X (S[19]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1200__5122(.A
       (addinc_add_7_30_n_65), .B (addinc_add_7_30_n_168), .X (S[26]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1201__8246(.A
       (addinc_add_7_30_n_171), .B (addinc_add_7_30_n_17), .Y
       (addinc_add_7_30_n_176));
  sky130_fd_sc_hd__a31oi_1 addinc_add_7_30_g1202__7098(.A1
       (addinc_add_7_30_n_164), .A2 (addinc_add_7_30_n_9), .A3
       (addinc_add_7_30_n_21), .B1 (addinc_add_7_30_n_99), .Y
       (addinc_add_7_30_n_175));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1203__6131(.A
       (addinc_add_7_30_n_86), .B (addinc_add_7_30_n_166), .X (S[21]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1204__1881(.A
       (addinc_add_7_30_n_69), .B (addinc_add_7_30_n_164), .X (S[28]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1205__5115(.A
       (addinc_add_7_30_n_64), .B (addinc_add_7_30_n_165), .X (S[25]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1206__7482(.A
       (addinc_add_7_30_n_164), .B (addinc_add_7_30_n_21), .Y
       (addinc_add_7_30_n_171));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1207__4733(.A1
       (addinc_add_7_30_n_160), .A2 (addinc_add_7_30_n_41), .B1
       (addinc_add_7_30_n_106), .Y (addinc_add_7_30_n_170));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1208__6161(.A1
       (addinc_add_7_30_n_11), .A2 (addinc_add_7_30_n_158), .B1
       (addinc_add_7_30_n_45), .Y (addinc_add_7_30_n_169));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1209__9315(.A1
       (addinc_add_7_30_n_159), .A2 (addinc_add_7_30_n_5), .B1
       (addinc_add_7_30_n_102), .Y (addinc_add_7_30_n_168));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1210__9945(.A
       (addinc_add_7_30_n_82), .B (addinc_add_7_30_n_158), .X (S[18]));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1211__2883(.A_N
       (addinc_add_7_30_n_160), .B (addinc_add_7_30_n_46), .Y
       (addinc_add_7_30_n_166));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1212__2346(.A_N
       (addinc_add_7_30_n_159), .B (addinc_add_7_30_n_12), .Y
       (addinc_add_7_30_n_165));
  sky130_fd_sc_hd__a221o_1 addinc_add_7_30_g1213__1666(.A1
       (addinc_add_7_30_n_155), .A2 (addinc_add_7_30_n_91), .B1
       (addinc_add_7_30_n_114), .B2 (addinc_add_7_30_n_42), .C1
       (addinc_add_7_30_n_60), .X (addinc_add_7_30_n_164));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1214__7410(.A
       (addinc_add_7_30_n_85), .B (addinc_add_7_30_n_154), .X (S[20]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1215__6417(.A
       (addinc_add_7_30_n_81), .B (addinc_add_7_30_n_156), .X (S[17]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1216__5477(.A
       (addinc_add_7_30_n_77), .B (addinc_add_7_30_n_155), .X (S[24]));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1217__2398(.A
       (addinc_add_7_30_n_49), .B (addinc_add_7_30_n_154), .Y
       (addinc_add_7_30_n_160));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1218__5107(.A
       (addinc_add_7_30_n_19), .B_N (addinc_add_7_30_n_155), .Y
       (addinc_add_7_30_n_159));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1219__6260(.A1
       (addinc_add_7_30_n_152), .A2 (addinc_add_7_30_n_35), .B1
       (addinc_add_7_30_n_100), .Y (addinc_add_7_30_n_158));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1220__4319(.A
       (addinc_add_7_30_n_79), .B (addinc_add_7_30_n_151), .X (S[15]));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1221__8428(.A_N
       (addinc_add_7_30_n_152), .B (addinc_add_7_30_n_18), .Y
       (addinc_add_7_30_n_156));
  sky130_fd_sc_hd__a31o_1 addinc_add_7_30_g1222__5526(.A1
       (addinc_add_7_30_n_147), .A2 (addinc_add_7_30_n_96), .A3
       (addinc_add_7_30_n_95), .B1 (addinc_add_7_30_n_120), .X
       (addinc_add_7_30_n_155));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1223__6783(.A1
       (addinc_add_7_30_n_147), .A2 (addinc_add_7_30_n_96), .B1
       (addinc_add_7_30_n_117), .Y (addinc_add_7_30_n_154));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1224__3680(.A
       (addinc_add_7_30_n_78), .B (addinc_add_7_30_n_147), .X (S[16]));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1225__1617(.A
       (addinc_add_7_30_n_20), .B_N (addinc_add_7_30_n_147), .Y
       (addinc_add_7_30_n_152));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1226__2802(.A1
       (addinc_add_7_30_n_6), .A2 (addinc_add_7_30_n_145), .B1
       (addinc_add_7_30_n_13), .Y (addinc_add_7_30_n_151));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1227__1705(.A
       (addinc_add_7_30_n_80), .B (addinc_add_7_30_n_145), .X (S[14]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1228__5122(.A
       (addinc_add_7_30_n_71), .B (addinc_add_7_30_n_146), .X (S[13]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1229__8246(.A
       (addinc_add_7_30_n_66), .B (addinc_add_7_30_n_144), .X (S[11]));
  sky130_fd_sc_hd__a221o_1 addinc_add_7_30_g1230__7098(.A1
       (addinc_add_7_30_n_141), .A2 (addinc_add_7_30_n_94), .B1
       (addinc_add_7_30_n_111), .B2 (addinc_add_7_30_n_15), .C1
       (addinc_add_7_30_n_26), .X (addinc_add_7_30_n_147));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1231__6131(.A_N
       (addinc_add_7_30_n_141), .B (addinc_add_7_30_n_56), .Y
       (addinc_add_7_30_n_146));
  sky130_fd_sc_hd__a31oi_1 addinc_add_7_30_g1232__1881(.A1
       (addinc_add_7_30_n_139), .A2 (addinc_add_7_30_n_33), .A3
       (addinc_add_7_30_n_55), .B1 (addinc_add_7_30_n_97), .Y
       (addinc_add_7_30_n_145));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1233__5115(.A1
       (addinc_add_7_30_n_39), .A2 (addinc_add_7_30_n_138), .B1
       (addinc_add_7_30_n_47), .Y (addinc_add_7_30_n_144));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1234__7482(.A
       (addinc_add_7_30_n_67), .B (addinc_add_7_30_n_139), .X (S[12]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1235__4733(.A
       (addinc_add_7_30_n_90), .B (addinc_add_7_30_n_138), .X (S[10]));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1236__6161(.A
       (addinc_add_7_30_n_139), .B (addinc_add_7_30_n_55), .X
       (addinc_add_7_30_n_141));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1237__9315(.A
       (addinc_add_7_30_n_73), .B (addinc_add_7_30_n_137), .X (S[9]));
  sky130_fd_sc_hd__a221o_1 addinc_add_7_30_g1238__9945(.A1
       (addinc_add_7_30_n_135), .A2 (addinc_add_7_30_n_93), .B1
       (addinc_add_7_30_n_113), .B2 (addinc_add_7_30_n_44), .C1
       (addinc_add_7_30_n_61), .X (addinc_add_7_30_n_139));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1239__2883(.A1
       (addinc_add_7_30_n_135), .A2 (addinc_add_7_30_n_2), .B1
       (addinc_add_7_30_n_104), .Y (addinc_add_7_30_n_138));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1240__2346(.A_N
       (addinc_add_7_30_n_135), .B (addinc_add_7_30_n_52), .Y
       (addinc_add_7_30_n_137));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1241__1666(.A
       (addinc_add_7_30_n_75), .B (addinc_add_7_30_n_134), .X (S[8]));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1242__7410(.A
       (addinc_add_7_30_n_58), .B_N (addinc_add_7_30_n_134), .Y
       (addinc_add_7_30_n_135));
  sky130_fd_sc_hd__fa_1 addinc_add_7_30_g1243__6417(.A (A[7]), .B
       (B[7]), .CIN (addinc_add_7_30_n_131), .COUT
       (addinc_add_7_30_n_134), .SUM (S[7]));
  sky130_fd_sc_hd__fa_1 addinc_add_7_30_g1244__5477(.A (A[6]), .B
       (B[6]), .CIN (addinc_add_7_30_n_129), .COUT
       (addinc_add_7_30_n_131), .SUM (S[6]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1245__2398(.A
       (addinc_add_7_30_n_74), .B (addinc_add_7_30_n_128), .X (S[5]));
  sky130_fd_sc_hd__o211ai_1 addinc_add_7_30_g1246__5107(.A1
       (addinc_add_7_30_n_14), .A2 (addinc_add_7_30_n_48), .B1
       (addinc_add_7_30_n_31), .C1 (addinc_add_7_30_n_126), .Y
       (addinc_add_7_30_n_129));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1247__6260(.A1
       (addinc_add_7_30_n_54), .A2 (addinc_add_7_30_n_125), .B1
       (addinc_add_7_30_n_14), .Y (addinc_add_7_30_n_128));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1248__4319(.A
       (addinc_add_7_30_n_83), .B (addinc_add_7_30_n_124), .X (S[4]));
  sky130_fd_sc_hd__or3_1 addinc_add_7_30_g1249__8428(.A
       (addinc_add_7_30_n_54), .B (addinc_add_7_30_n_48), .C
       (addinc_add_7_30_n_125), .X (addinc_add_7_30_n_126));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1250(.A
       (addinc_add_7_30_n_124), .Y (addinc_add_7_30_n_125));
  sky130_fd_sc_hd__fa_1 addinc_add_7_30_g1251__5526(.A (A[3]), .B
       (B[3]), .CIN (addinc_add_7_30_n_121), .COUT
       (addinc_add_7_30_n_124), .SUM (S[3]));
  sky130_fd_sc_hd__fa_1 addinc_add_7_30_g1252__6783(.A (A[2]), .B
       (B[2]), .CIN (n_255), .COUT (addinc_add_7_30_n_121), .SUM
       (S[2]));
  sky130_fd_sc_hd__a221o_1 addinc_add_7_30_g1253__3680(.A1
       (addinc_add_7_30_n_117), .A2 (addinc_add_7_30_n_95), .B1
       (addinc_add_7_30_n_110), .B2 (addinc_add_7_30_n_57), .C1
       (addinc_add_7_30_n_23), .X (addinc_add_7_30_n_120));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1256__1705(.A1
       (addinc_add_7_30_n_51), .A2 (addinc_add_7_30_n_112), .B1
       (addinc_add_7_30_n_25), .Y (addinc_add_7_30_n_117));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1258__5122(.A1
       (addinc_add_7_30_n_99), .A2 (addinc_add_7_30_n_8), .B1_N
       (addinc_add_7_30_n_53), .Y (addinc_add_7_30_n_115));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1259__8246(.A1
       (addinc_add_7_30_n_37), .A2 (addinc_add_7_30_n_103), .B1
       (addinc_add_7_30_n_50), .Y (addinc_add_7_30_n_114));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1260__7098(.A1
       (addinc_add_7_30_n_39), .A2 (addinc_add_7_30_n_105), .B1
       (addinc_add_7_30_n_47), .Y (addinc_add_7_30_n_113));
  sky130_fd_sc_hd__o21a_1 addinc_add_7_30_g1261__6131(.A1
       (addinc_add_7_30_n_11), .A2 (addinc_add_7_30_n_101), .B1
       (addinc_add_7_30_n_45), .X (addinc_add_7_30_n_112));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1262__1881(.A1
       (addinc_add_7_30_n_6), .A2 (addinc_add_7_30_n_98), .B1
       (addinc_add_7_30_n_13), .Y (addinc_add_7_30_n_111));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1263__5115(.A1
       (addinc_add_7_30_n_38), .A2 (addinc_add_7_30_n_107), .B1
       (addinc_add_7_30_n_43), .Y (addinc_add_7_30_n_110));
  sky130_fd_sc_hd__o2bb2ai_1 addinc_add_7_30_g1264__7482(.A1_N (B[0]),
       .A2_N (A[0]), .B1 (addinc_add_7_30_n_0), .B2
       (addinc_add_7_30_n_1), .Y (addinc_add_7_30_n_109));
  sky130_fd_sc_hd__xnor2_1 addinc_add_7_30_g1265__4733(.A
       (addinc_add_7_30_n_0), .B (addinc_add_7_30_n_76), .Y (S[0]));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1266(.A
       (addinc_add_7_30_n_106), .Y (addinc_add_7_30_n_107));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1267(.A
       (addinc_add_7_30_n_104), .Y (addinc_add_7_30_n_105));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1268(.A
       (addinc_add_7_30_n_102), .Y (addinc_add_7_30_n_103));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1269(.A
       (addinc_add_7_30_n_100), .Y (addinc_add_7_30_n_101));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1270(.A
       (addinc_add_7_30_n_97), .Y (addinc_add_7_30_n_98));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1271__6161(.A1
       (addinc_add_7_30_n_40), .A2 (addinc_add_7_30_n_46), .B1
       (addinc_add_7_30_n_62), .Y (addinc_add_7_30_n_106));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1272__9315(.A1
       (addinc_add_7_30_n_3), .A2 (addinc_add_7_30_n_52), .B1
       (addinc_add_7_30_n_59), .Y (addinc_add_7_30_n_104));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1273__9945(.A1
       (addinc_add_7_30_n_4), .A2 (addinc_add_7_30_n_12), .B1
       (addinc_add_7_30_n_27), .Y (addinc_add_7_30_n_102));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1274__2883(.A1
       (addinc_add_7_30_n_36), .A2 (addinc_add_7_30_n_18), .B1
       (addinc_add_7_30_n_22), .Y (addinc_add_7_30_n_100));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1275__2346(.A1
       (addinc_add_7_30_n_17), .A2 (addinc_add_7_30_n_10), .B1
       (addinc_add_7_30_n_28), .Y (addinc_add_7_30_n_99));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1276__1666(.A1
       (addinc_add_7_30_n_34), .A2 (addinc_add_7_30_n_56), .B1
       (addinc_add_7_30_n_29), .Y (addinc_add_7_30_n_97));
  sky130_fd_sc_hd__nor3b_1 addinc_add_7_30_g1277__7410(.A
       (addinc_add_7_30_n_34), .B (addinc_add_7_30_n_6), .C_N
       (addinc_add_7_30_n_15), .Y (addinc_add_7_30_n_94));
  sky130_fd_sc_hd__nor3b_1 addinc_add_7_30_g1278__6417(.A
       (addinc_add_7_30_n_3), .B (addinc_add_7_30_n_39), .C_N
       (addinc_add_7_30_n_44), .Y (addinc_add_7_30_n_93));
  sky130_fd_sc_hd__or3_1 addinc_add_7_30_g1279__5477(.A
       (addinc_add_7_30_n_16), .B (addinc_add_7_30_n_7), .C
       (addinc_add_7_30_n_10), .X (addinc_add_7_30_n_92));
  sky130_fd_sc_hd__nor4b_1 addinc_add_7_30_g1280__2398(.A
       (addinc_add_7_30_n_19), .B (addinc_add_7_30_n_4), .C
       (addinc_add_7_30_n_37), .D_N (addinc_add_7_30_n_42), .Y
       (addinc_add_7_30_n_91));
  sky130_fd_sc_hd__nor4_1 addinc_add_7_30_g1281__5107(.A
       (addinc_add_7_30_n_20), .B (addinc_add_7_30_n_36), .C
       (addinc_add_7_30_n_11), .D (addinc_add_7_30_n_51), .Y
       (addinc_add_7_30_n_96));
  sky130_fd_sc_hd__nor4b_1 addinc_add_7_30_g1282__6260(.A
       (addinc_add_7_30_n_49), .B (addinc_add_7_30_n_40), .C
       (addinc_add_7_30_n_38), .D_N (addinc_add_7_30_n_57), .Y
       (addinc_add_7_30_n_95));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1283__4319(.A_N
       (addinc_add_7_30_n_39), .B (addinc_add_7_30_n_47), .Y
       (addinc_add_7_30_n_90));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1284__8428(.A
       (addinc_add_7_30_n_23), .B_N (addinc_add_7_30_n_57), .Y
       (addinc_add_7_30_n_89));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1286__6783(.A
       (addinc_add_7_30_n_28), .B (addinc_add_7_30_n_9), .X
       (addinc_add_7_30_n_87));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1287__3680(.A
       (addinc_add_7_30_n_62), .B (addinc_add_7_30_n_41), .X
       (addinc_add_7_30_n_86));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1288__1617(.A_N
       (addinc_add_7_30_n_49), .B (addinc_add_7_30_n_46), .Y
       (addinc_add_7_30_n_85));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1289__2802(.A
       (addinc_add_7_30_n_51), .B_N (addinc_add_7_30_n_25), .Y
       (addinc_add_7_30_n_84));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1290__1705(.A
       (addinc_add_7_30_n_54), .B_N (addinc_add_7_30_n_14), .Y
       (addinc_add_7_30_n_83));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1291__5122(.A_N
       (addinc_add_7_30_n_11), .B (addinc_add_7_30_n_45), .Y
       (addinc_add_7_30_n_82));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1292__8246(.A
       (addinc_add_7_30_n_22), .B (addinc_add_7_30_n_35), .X
       (addinc_add_7_30_n_81));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1293__7098(.A_N
       (addinc_add_7_30_n_6), .B (addinc_add_7_30_n_13), .Y
       (addinc_add_7_30_n_80));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1294__6131(.A
       (addinc_add_7_30_n_26), .B_N (addinc_add_7_30_n_15), .Y
       (addinc_add_7_30_n_79));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1295__1881(.A
       (addinc_add_7_30_n_20), .B_N (addinc_add_7_30_n_18), .Y
       (addinc_add_7_30_n_78));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1296__5115(.A
       (addinc_add_7_30_n_19), .B_N (addinc_add_7_30_n_12), .Y
       (addinc_add_7_30_n_77));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1297__7482(.A (B[0]), .B
       (A[0]), .X (addinc_add_7_30_n_76));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1298__4733(.A
       (addinc_add_7_30_n_58), .B_N (addinc_add_7_30_n_52), .Y
       (addinc_add_7_30_n_75));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1299__6161(.A
       (addinc_add_7_30_n_48), .B_N (addinc_add_7_30_n_31), .Y
       (addinc_add_7_30_n_74));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1300__9315(.A
       (addinc_add_7_30_n_59), .B (addinc_add_7_30_n_2), .X
       (addinc_add_7_30_n_73));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1301__9945(.A
       (addinc_add_7_30_n_16), .B_N (addinc_add_7_30_n_30), .Y
       (addinc_add_7_30_n_72));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1302__2883(.A
       (addinc_add_7_30_n_29), .B (addinc_add_7_30_n_33), .X
       (addinc_add_7_30_n_71));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1303__2346(.A
       (addinc_add_7_30_n_53), .B (addinc_add_7_30_n_8), .Y
       (addinc_add_7_30_n_70));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1304__1666(.A
       (addinc_add_7_30_n_17), .B (addinc_add_7_30_n_21), .X
       (addinc_add_7_30_n_69));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1305__7410(.A
       (addinc_add_7_30_n_60), .B_N (addinc_add_7_30_n_42), .Y
       (addinc_add_7_30_n_68));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1306__6417(.A
       (addinc_add_7_30_n_56), .B (addinc_add_7_30_n_55), .X
       (addinc_add_7_30_n_67));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1307__5477(.A
       (addinc_add_7_30_n_61), .B_N (addinc_add_7_30_n_44), .Y
       (addinc_add_7_30_n_66));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1308__2398(.A_N
       (addinc_add_7_30_n_37), .B (addinc_add_7_30_n_50), .Y
       (addinc_add_7_30_n_65));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1309__5107(.A
       (addinc_add_7_30_n_27), .B (addinc_add_7_30_n_5), .X
       (addinc_add_7_30_n_64));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1310__6260(.A_N
       (addinc_add_7_30_n_38), .B (addinc_add_7_30_n_43), .Y
       (addinc_add_7_30_n_63));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1311(.A
       (addinc_add_7_30_n_40), .Y (addinc_add_7_30_n_41));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1312(.A
       (addinc_add_7_30_n_36), .Y (addinc_add_7_30_n_35));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1313(.A
       (addinc_add_7_30_n_34), .Y (addinc_add_7_30_n_33));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1314__4319(.A (B[21]), .B
       (A[21]), .Y (addinc_add_7_30_n_62));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1315__8428(.A (B[11]), .B
       (A[11]), .X (addinc_add_7_30_n_61));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1316__5526(.A (B[27]), .B
       (A[27]), .X (addinc_add_7_30_n_60));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1317__6783(.A (B[9]), .B
       (A[9]), .Y (addinc_add_7_30_n_59));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1318__3680(.A (A[8]), .B
       (B[8]), .Y (addinc_add_7_30_n_58));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1319__1617(.A (A[23]), .B
       (B[23]), .X (addinc_add_7_30_n_57));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1320__2802(.A (B[12]), .B
       (A[12]), .Y (addinc_add_7_30_n_56));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1321__1705(.A (A[12]), .B
       (B[12]), .X (addinc_add_7_30_n_55));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1322__5122(.A (A[4]), .B
       (B[4]), .Y (addinc_add_7_30_n_54));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1323__8246(.A (B[30]), .B
       (A[30]), .Y (addinc_add_7_30_n_53));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1324__7098(.A (B[8]), .B
       (A[8]), .Y (addinc_add_7_30_n_52));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1325__6131(.A (A[19]), .B
       (B[19]), .Y (addinc_add_7_30_n_51));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1326__1881(.A (B[26]), .B
       (A[26]), .Y (addinc_add_7_30_n_50));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1327__5115(.A (A[20]), .B
       (B[20]), .Y (addinc_add_7_30_n_49));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1328__7482(.A (A[5]), .B
       (B[5]), .Y (addinc_add_7_30_n_48));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1329__4733(.A (B[10]), .B
       (A[10]), .Y (addinc_add_7_30_n_47));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1330__6161(.A (B[20]), .B
       (A[20]), .Y (addinc_add_7_30_n_46));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1331__9315(.A (B[18]), .B
       (A[18]), .Y (addinc_add_7_30_n_45));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1332__9945(.A (A[11]), .B
       (B[11]), .X (addinc_add_7_30_n_44));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1333__2883(.A (B[22]), .B
       (A[22]), .Y (addinc_add_7_30_n_43));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1334__2346(.A (A[27]), .B
       (B[27]), .X (addinc_add_7_30_n_42));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1335__1666(.A (A[21]), .B
       (B[21]), .Y (addinc_add_7_30_n_40));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1336__7410(.A (A[10]), .B
       (B[10]), .Y (addinc_add_7_30_n_39));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1337__6417(.A (A[22]), .B
       (B[22]), .Y (addinc_add_7_30_n_38));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1338__5477(.A (A[26]), .B
       (B[26]), .Y (addinc_add_7_30_n_37));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1339__2398(.A (A[17]), .B
       (B[17]), .Y (addinc_add_7_30_n_36));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1340__5107(.A (A[13]), .B
       (B[13]), .Y (addinc_add_7_30_n_34));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1341(.A
       (addinc_add_7_30_n_10), .Y (addinc_add_7_30_n_9));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1342(.A
       (addinc_add_7_30_n_7), .Y (addinc_add_7_30_n_8));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1343(.A
       (addinc_add_7_30_n_4), .Y (addinc_add_7_30_n_5));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1344(.A
       (addinc_add_7_30_n_3), .Y (addinc_add_7_30_n_2));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1345__6260(.A (A[0]), .B
       (B[0]), .Y (addinc_add_7_30_n_1));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1347__8428(.A (B[5]), .B
       (A[5]), .Y (addinc_add_7_30_n_31));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1348__5526(.A (B[31]), .B
       (A[31]), .Y (addinc_add_7_30_n_30));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1349__6783(.A (B[13]), .B
       (A[13]), .Y (addinc_add_7_30_n_29));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1350__3680(.A (B[29]), .B
       (A[29]), .Y (addinc_add_7_30_n_28));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1351__1617(.A (B[25]), .B
       (A[25]), .Y (addinc_add_7_30_n_27));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1352__2802(.A (B[15]), .B
       (A[15]), .X (addinc_add_7_30_n_26));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1353__1705(.A (B[19]), .B
       (A[19]), .Y (addinc_add_7_30_n_25));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1355__8246(.A (B[23]), .B
       (A[23]), .X (addinc_add_7_30_n_23));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1356__7098(.A (B[17]), .B
       (A[17]), .Y (addinc_add_7_30_n_22));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1357__6131(.A (A[28]), .B
       (B[28]), .X (addinc_add_7_30_n_21));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1358__1881(.A (A[16]), .B
       (B[16]), .Y (addinc_add_7_30_n_20));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1359__5115(.A (A[24]), .B
       (B[24]), .Y (addinc_add_7_30_n_19));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1360__7482(.A (B[16]), .B
       (A[16]), .Y (addinc_add_7_30_n_18));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1361__4733(.A (B[28]), .B
       (A[28]), .Y (addinc_add_7_30_n_17));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1362__6161(.A (A[31]), .B
       (B[31]), .Y (addinc_add_7_30_n_16));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1363__9315(.A (A[15]), .B
       (B[15]), .X (addinc_add_7_30_n_15));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1364__9945(.A (B[4]), .B
       (A[4]), .Y (addinc_add_7_30_n_14));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1365__2883(.A (B[14]), .B
       (A[14]), .Y (addinc_add_7_30_n_13));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1366__2346(.A (B[24]), .B
       (A[24]), .Y (addinc_add_7_30_n_12));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1367__1666(.A (A[18]), .B
       (B[18]), .Y (addinc_add_7_30_n_11));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1368__7410(.A (A[29]), .B
       (B[29]), .Y (addinc_add_7_30_n_10));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1369__6417(.A (A[30]), .B
       (B[30]), .Y (addinc_add_7_30_n_7));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1370__5477(.A (A[14]), .B
       (B[14]), .Y (addinc_add_7_30_n_6));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1371__2398(.A (A[25]), .B
       (B[25]), .Y (addinc_add_7_30_n_4));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1372__5107(.A (A[9]), .B
       (B[9]), .Y (addinc_add_7_30_n_3));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1373(.A (Cin), .Y
       (addinc_add_7_30_n_0));
  sky130_fd_sc_hd__fa_1 g2(.A (A[1]), .B (B[1]), .CIN
       (addinc_add_7_30_n_109), .COUT (n_255), .SUM (S[1]));
endmodule

