
//input ports
add mapped point clock clock -type PI PI
add mapped point reset reset -type PI PI
add mapped point start start -type PI PI
add mapped point X[7] X[7] -type PI PI
add mapped point X[6] X[6] -type PI PI
add mapped point X[5] X[5] -type PI PI
add mapped point X[4] X[4] -type PI PI
add mapped point X[3] X[3] -type PI PI
add mapped point X[2] X[2] -type PI PI
add mapped point X[1] X[1] -type PI PI
add mapped point X[0] X[0] -type PI PI
add mapped point Y[3] Y[3] -type PI PI
add mapped point Y[2] Y[2] -type PI PI
add mapped point Y[1] Y[1] -type PI PI
add mapped point Y[0] Y[0] -type PI PI

//output ports
add mapped point end_expo end_expo -type PO PO
add mapped point resultado[127] resultado[127] -type PO PO
add mapped point resultado[126] resultado[126] -type PO PO
add mapped point resultado[125] resultado[125] -type PO PO
add mapped point resultado[124] resultado[124] -type PO PO
add mapped point resultado[123] resultado[123] -type PO PO
add mapped point resultado[122] resultado[122] -type PO PO
add mapped point resultado[121] resultado[121] -type PO PO
add mapped point resultado[120] resultado[120] -type PO PO
add mapped point resultado[119] resultado[119] -type PO PO
add mapped point resultado[118] resultado[118] -type PO PO
add mapped point resultado[117] resultado[117] -type PO PO
add mapped point resultado[116] resultado[116] -type PO PO
add mapped point resultado[115] resultado[115] -type PO PO
add mapped point resultado[114] resultado[114] -type PO PO
add mapped point resultado[113] resultado[113] -type PO PO
add mapped point resultado[112] resultado[112] -type PO PO
add mapped point resultado[111] resultado[111] -type PO PO
add mapped point resultado[110] resultado[110] -type PO PO
add mapped point resultado[109] resultado[109] -type PO PO
add mapped point resultado[108] resultado[108] -type PO PO
add mapped point resultado[107] resultado[107] -type PO PO
add mapped point resultado[106] resultado[106] -type PO PO
add mapped point resultado[105] resultado[105] -type PO PO
add mapped point resultado[104] resultado[104] -type PO PO
add mapped point resultado[103] resultado[103] -type PO PO
add mapped point resultado[102] resultado[102] -type PO PO
add mapped point resultado[101] resultado[101] -type PO PO
add mapped point resultado[100] resultado[100] -type PO PO
add mapped point resultado[99] resultado[99] -type PO PO
add mapped point resultado[98] resultado[98] -type PO PO
add mapped point resultado[97] resultado[97] -type PO PO
add mapped point resultado[96] resultado[96] -type PO PO
add mapped point resultado[95] resultado[95] -type PO PO
add mapped point resultado[94] resultado[94] -type PO PO
add mapped point resultado[93] resultado[93] -type PO PO
add mapped point resultado[92] resultado[92] -type PO PO
add mapped point resultado[91] resultado[91] -type PO PO
add mapped point resultado[90] resultado[90] -type PO PO
add mapped point resultado[89] resultado[89] -type PO PO
add mapped point resultado[88] resultado[88] -type PO PO
add mapped point resultado[87] resultado[87] -type PO PO
add mapped point resultado[86] resultado[86] -type PO PO
add mapped point resultado[85] resultado[85] -type PO PO
add mapped point resultado[84] resultado[84] -type PO PO
add mapped point resultado[83] resultado[83] -type PO PO
add mapped point resultado[82] resultado[82] -type PO PO
add mapped point resultado[81] resultado[81] -type PO PO
add mapped point resultado[80] resultado[80] -type PO PO
add mapped point resultado[79] resultado[79] -type PO PO
add mapped point resultado[78] resultado[78] -type PO PO
add mapped point resultado[77] resultado[77] -type PO PO
add mapped point resultado[76] resultado[76] -type PO PO
add mapped point resultado[75] resultado[75] -type PO PO
add mapped point resultado[74] resultado[74] -type PO PO
add mapped point resultado[73] resultado[73] -type PO PO
add mapped point resultado[72] resultado[72] -type PO PO
add mapped point resultado[71] resultado[71] -type PO PO
add mapped point resultado[70] resultado[70] -type PO PO
add mapped point resultado[69] resultado[69] -type PO PO
add mapped point resultado[68] resultado[68] -type PO PO
add mapped point resultado[67] resultado[67] -type PO PO
add mapped point resultado[66] resultado[66] -type PO PO
add mapped point resultado[65] resultado[65] -type PO PO
add mapped point resultado[64] resultado[64] -type PO PO
add mapped point resultado[63] resultado[63] -type PO PO
add mapped point resultado[62] resultado[62] -type PO PO
add mapped point resultado[61] resultado[61] -type PO PO
add mapped point resultado[60] resultado[60] -type PO PO
add mapped point resultado[59] resultado[59] -type PO PO
add mapped point resultado[58] resultado[58] -type PO PO
add mapped point resultado[57] resultado[57] -type PO PO
add mapped point resultado[56] resultado[56] -type PO PO
add mapped point resultado[55] resultado[55] -type PO PO
add mapped point resultado[54] resultado[54] -type PO PO
add mapped point resultado[53] resultado[53] -type PO PO
add mapped point resultado[52] resultado[52] -type PO PO
add mapped point resultado[51] resultado[51] -type PO PO
add mapped point resultado[50] resultado[50] -type PO PO
add mapped point resultado[49] resultado[49] -type PO PO
add mapped point resultado[48] resultado[48] -type PO PO
add mapped point resultado[47] resultado[47] -type PO PO
add mapped point resultado[46] resultado[46] -type PO PO
add mapped point resultado[45] resultado[45] -type PO PO
add mapped point resultado[44] resultado[44] -type PO PO
add mapped point resultado[43] resultado[43] -type PO PO
add mapped point resultado[42] resultado[42] -type PO PO
add mapped point resultado[41] resultado[41] -type PO PO
add mapped point resultado[40] resultado[40] -type PO PO
add mapped point resultado[39] resultado[39] -type PO PO
add mapped point resultado[38] resultado[38] -type PO PO
add mapped point resultado[37] resultado[37] -type PO PO
add mapped point resultado[36] resultado[36] -type PO PO
add mapped point resultado[35] resultado[35] -type PO PO
add mapped point resultado[34] resultado[34] -type PO PO
add mapped point resultado[33] resultado[33] -type PO PO
add mapped point resultado[32] resultado[32] -type PO PO
add mapped point resultado[31] resultado[31] -type PO PO
add mapped point resultado[30] resultado[30] -type PO PO
add mapped point resultado[29] resultado[29] -type PO PO
add mapped point resultado[28] resultado[28] -type PO PO
add mapped point resultado[27] resultado[27] -type PO PO
add mapped point resultado[26] resultado[26] -type PO PO
add mapped point resultado[25] resultado[25] -type PO PO
add mapped point resultado[24] resultado[24] -type PO PO
add mapped point resultado[23] resultado[23] -type PO PO
add mapped point resultado[22] resultado[22] -type PO PO
add mapped point resultado[21] resultado[21] -type PO PO
add mapped point resultado[20] resultado[20] -type PO PO
add mapped point resultado[19] resultado[19] -type PO PO
add mapped point resultado[18] resultado[18] -type PO PO
add mapped point resultado[17] resultado[17] -type PO PO
add mapped point resultado[16] resultado[16] -type PO PO
add mapped point resultado[15] resultado[15] -type PO PO
add mapped point resultado[14] resultado[14] -type PO PO
add mapped point resultado[13] resultado[13] -type PO PO
add mapped point resultado[12] resultado[12] -type PO PO
add mapped point resultado[11] resultado[11] -type PO PO
add mapped point resultado[10] resultado[10] -type PO PO
add mapped point resultado[9] resultado[9] -type PO PO
add mapped point resultado[8] resultado[8] -type PO PO
add mapped point resultado[7] resultado[7] -type PO PO
add mapped point resultado[6] resultado[6] -type PO PO
add mapped point resultado[5] resultado[5] -type PO PO
add mapped point resultado[4] resultado[4] -type PO PO
add mapped point resultado[3] resultado[3] -type PO PO
add mapped point resultado[2] resultado[2] -type PO PO
add mapped point resultado[1] resultado[1] -type PO PO
add mapped point resultado[0] resultado[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point MULT1/end_mul/q MULT1/end_mul_reg/Q -type DFF DFF
add mapped point MULT1/produto[0]/q MULT1/produto_reg[0]/Q -type DFF DFF
add mapped point MULT1/produto[1]/q MULT1/produto_reg[1]/Q -type DFF DFF
add mapped point MULT1/produto[2]/q MULT1/produto_reg[2]/Q -type DFF DFF
add mapped point MULT1/produto[3]/q MULT1/produto_reg[3]/Q -type DFF DFF
add mapped point MULT1/produto[4]/q MULT1/produto_reg[4]/Q -type DFF DFF
add mapped point MULT1/produto[5]/q MULT1/produto_reg[5]/Q -type DFF DFF
add mapped point MULT1/produto[6]/q MULT1/produto_reg[6]/Q -type DFF DFF
add mapped point MULT1/produto[7]/q MULT1/produto_reg[7]/Q -type DFF DFF
add mapped point MULT1/produto[8]/q MULT1/produto_reg[8]/Q -type DFF DFF
add mapped point MULT1/produto[9]/q MULT1/produto_reg[9]/Q -type DFF DFF
add mapped point MULT1/produto[10]/q MULT1/produto_reg[10]/Q -type DFF DFF
add mapped point MULT1/produto[11]/q MULT1/produto_reg[11]/Q -type DFF DFF
add mapped point MULT1/produto[12]/q MULT1/produto_reg[12]/Q -type DFF DFF
add mapped point MULT1/produto[13]/q MULT1/produto_reg[13]/Q -type DFF DFF
add mapped point MULT1/produto[14]/q MULT1/produto_reg[14]/Q -type DFF DFF
add mapped point MULT1/produto[15]/q MULT1/produto_reg[15]/Q -type DFF DFF
add mapped point MULT1/produto[16]/q MULT1/produto_reg[16]/Q -type DFF DFF
add mapped point MULT1/produto[17]/q MULT1/produto_reg[17]/Q -type DFF DFF
add mapped point MULT1/produto[18]/q MULT1/produto_reg[18]/Q -type DFF DFF
add mapped point MULT1/produto[19]/q MULT1/produto_reg[19]/Q -type DFF DFF
add mapped point MULT1/produto[20]/q MULT1/produto_reg[20]/Q -type DFF DFF
add mapped point MULT1/produto[21]/q MULT1/produto_reg[21]/Q -type DFF DFF
add mapped point MULT1/produto[22]/q MULT1/produto_reg[22]/Q -type DFF DFF
add mapped point MULT1/produto[23]/q MULT1/produto_reg[23]/Q -type DFF DFF
add mapped point MULT1/produto[24]/q MULT1/produto_reg[24]/Q -type DFF DFF
add mapped point MULT1/produto[25]/q MULT1/produto_reg[25]/Q -type DFF DFF
add mapped point MULT1/produto[26]/q MULT1/produto_reg[26]/Q -type DFF DFF
add mapped point MULT1/produto[27]/q MULT1/produto_reg[27]/Q -type DFF DFF
add mapped point MULT1/produto[28]/q MULT1/produto_reg[28]/Q -type DFF DFF
add mapped point MULT1/produto[29]/q MULT1/produto_reg[29]/Q -type DFF DFF
add mapped point MULT1/produto[30]/q MULT1/produto_reg[30]/Q -type DFF DFF
add mapped point MULT1/produto[31]/q MULT1/produto_reg[31]/Q -type DFF DFF
add mapped point MULT1/produto[32]/q MULT1/produto_reg[32]/Q -type DFF DFF
add mapped point MULT1/produto[33]/q MULT1/produto_reg[33]/Q -type DFF DFF
add mapped point MULT1/produto[34]/q MULT1/produto_reg[34]/Q -type DFF DFF
add mapped point MULT1/produto[35]/q MULT1/produto_reg[35]/Q -type DFF DFF
add mapped point MULT1/produto[36]/q MULT1/produto_reg[36]/Q -type DFF DFF
add mapped point MULT1/produto[37]/q MULT1/produto_reg[37]/Q -type DFF DFF
add mapped point MULT1/produto[38]/q MULT1/produto_reg[38]/Q -type DFF DFF
add mapped point MULT1/produto[39]/q MULT1/produto_reg[39]/Q -type DFF DFF
add mapped point MULT1/produto[40]/q MULT1/produto_reg[40]/Q -type DFF DFF
add mapped point MULT1/produto[41]/q MULT1/produto_reg[41]/Q -type DFF DFF
add mapped point MULT1/produto[42]/q MULT1/produto_reg[42]/Q -type DFF DFF
add mapped point MULT1/produto[43]/q MULT1/produto_reg[43]/Q -type DFF DFF
add mapped point MULT1/produto[44]/q MULT1/produto_reg[44]/Q -type DFF DFF
add mapped point MULT1/produto[45]/q MULT1/produto_reg[45]/Q -type DFF DFF
add mapped point MULT1/produto[46]/q MULT1/produto_reg[46]/Q -type DFF DFF
add mapped point MULT1/produto[47]/q MULT1/produto_reg[47]/Q -type DFF DFF
add mapped point MULT1/produto[48]/q MULT1/produto_reg[48]/Q -type DFF DFF
add mapped point MULT1/produto[49]/q MULT1/produto_reg[49]/Q -type DFF DFF
add mapped point MULT1/produto[50]/q MULT1/produto_reg[50]/Q -type DFF DFF
add mapped point MULT1/produto[51]/q MULT1/produto_reg[51]/Q -type DFF DFF
add mapped point MULT1/produto[52]/q MULT1/produto_reg[52]/Q -type DFF DFF
add mapped point MULT1/produto[53]/q MULT1/produto_reg[53]/Q -type DFF DFF
add mapped point MULT1/produto[54]/q MULT1/produto_reg[54]/Q -type DFF DFF
add mapped point MULT1/produto[55]/q MULT1/produto_reg[55]/Q -type DFF DFF
add mapped point MULT1/produto[56]/q MULT1/produto_reg[56]/Q -type DFF DFF
add mapped point MULT1/produto[57]/q MULT1/produto_reg[57]/Q -type DFF DFF
add mapped point MULT1/produto[58]/q MULT1/produto_reg[58]/Q -type DFF DFF
add mapped point MULT1/produto[59]/q MULT1/produto_reg[59]/Q -type DFF DFF
add mapped point MULT1/produto[60]/q MULT1/produto_reg[60]/Q -type DFF DFF
add mapped point MULT1/produto[61]/q MULT1/produto_reg[61]/Q -type DFF DFF
add mapped point MULT1/produto[62]/q MULT1/produto_reg[62]/Q -type DFF DFF
add mapped point MULT1/produto[63]/q MULT1/produto_reg[63]/Q -type DFF DFF
add mapped point MULT1/produto[64]/q MULT1/produto_reg[64]/Q -type DFF DFF
add mapped point MULT1/produto[65]/q MULT1/produto_reg[65]/Q -type DFF DFF
add mapped point MULT1/produto[66]/q MULT1/produto_reg[66]/Q -type DFF DFF
add mapped point MULT1/produto[67]/q MULT1/produto_reg[67]/Q -type DFF DFF
add mapped point MULT1/produto[68]/q MULT1/produto_reg[68]/Q -type DFF DFF
add mapped point MULT1/produto[69]/q MULT1/produto_reg[69]/Q -type DFF DFF
add mapped point MULT1/produto[70]/q MULT1/produto_reg[70]/Q -type DFF DFF
add mapped point MULT1/produto[71]/q MULT1/produto_reg[71]/Q -type DFF DFF
add mapped point MULT1/produto[72]/q MULT1/produto_reg[72]/Q -type DFF DFF
add mapped point MULT1/produto[73]/q MULT1/produto_reg[73]/Q -type DFF DFF
add mapped point MULT1/produto[74]/q MULT1/produto_reg[74]/Q -type DFF DFF
add mapped point MULT1/produto[75]/q MULT1/produto_reg[75]/Q -type DFF DFF
add mapped point MULT1/produto[76]/q MULT1/produto_reg[76]/Q -type DFF DFF
add mapped point MULT1/produto[77]/q MULT1/produto_reg[77]/Q -type DFF DFF
add mapped point MULT1/produto[78]/q MULT1/produto_reg[78]/Q -type DFF DFF
add mapped point MULT1/produto[79]/q MULT1/produto_reg[79]/Q -type DFF DFF
add mapped point MULT1/produto[80]/q MULT1/produto_reg[80]/Q -type DFF DFF
add mapped point MULT1/produto[81]/q MULT1/produto_reg[81]/Q -type DFF DFF
add mapped point MULT1/produto[82]/q MULT1/produto_reg[82]/Q -type DFF DFF
add mapped point MULT1/produto[83]/q MULT1/produto_reg[83]/Q -type DFF DFF
add mapped point MULT1/produto[84]/q MULT1/produto_reg[84]/Q -type DFF DFF
add mapped point MULT1/produto[85]/q MULT1/produto_reg[85]/Q -type DFF DFF
add mapped point MULT1/produto[86]/q MULT1/produto_reg[86]/Q -type DFF DFF
add mapped point MULT1/produto[87]/q MULT1/produto_reg[87]/Q -type DFF DFF
add mapped point MULT1/produto[88]/q MULT1/produto_reg[88]/Q -type DFF DFF
add mapped point MULT1/produto[89]/q MULT1/produto_reg[89]/Q -type DFF DFF
add mapped point MULT1/produto[90]/q MULT1/produto_reg[90]/Q -type DFF DFF
add mapped point MULT1/produto[91]/q MULT1/produto_reg[91]/Q -type DFF DFF
add mapped point MULT1/produto[92]/q MULT1/produto_reg[92]/Q -type DFF DFF
add mapped point MULT1/produto[93]/q MULT1/produto_reg[93]/Q -type DFF DFF
add mapped point MULT1/produto[94]/q MULT1/produto_reg[94]/Q -type DFF DFF
add mapped point MULT1/produto[95]/q MULT1/produto_reg[95]/Q -type DFF DFF
add mapped point MULT1/produto[96]/q MULT1/produto_reg[96]/Q -type DFF DFF
add mapped point MULT1/produto[97]/q MULT1/produto_reg[97]/Q -type DFF DFF
add mapped point MULT1/produto[98]/q MULT1/produto_reg[98]/Q -type DFF DFF
add mapped point MULT1/produto[99]/q MULT1/produto_reg[99]/Q -type DFF DFF
add mapped point MULT1/produto[100]/q MULT1/produto_reg[100]/Q -type DFF DFF
add mapped point MULT1/produto[101]/q MULT1/produto_reg[101]/Q -type DFF DFF
add mapped point MULT1/produto[102]/q MULT1/produto_reg[102]/Q -type DFF DFF
add mapped point MULT1/produto[103]/q MULT1/produto_reg[103]/Q -type DFF DFF
add mapped point MULT1/produto[104]/q MULT1/produto_reg[104]/Q -type DFF DFF
add mapped point MULT1/produto[105]/q MULT1/produto_reg[105]/Q -type DFF DFF
add mapped point MULT1/produto[106]/q MULT1/produto_reg[106]/Q -type DFF DFF
add mapped point MULT1/produto[107]/q MULT1/produto_reg[107]/Q -type DFF DFF
add mapped point MULT1/produto[108]/q MULT1/produto_reg[108]/Q -type DFF DFF
add mapped point MULT1/produto[109]/q MULT1/produto_reg[109]/Q -type DFF DFF
add mapped point MULT1/produto[110]/q MULT1/produto_reg[110]/Q -type DFF DFF
add mapped point MULT1/produto[111]/q MULT1/produto_reg[111]/Q -type DFF DFF
add mapped point MULT1/produto[112]/q MULT1/produto_reg[112]/Q -type DFF DFF
add mapped point MULT1/produto[113]/q MULT1/produto_reg[113]/Q -type DFF DFF
add mapped point MULT1/produto[114]/q MULT1/produto_reg[114]/Q -type DFF DFF
add mapped point MULT1/produto[115]/q MULT1/produto_reg[115]/Q -type DFF DFF
add mapped point MULT1/produto[116]/q MULT1/produto_reg[116]/Q -type DFF DFF
add mapped point MULT1/produto[117]/q MULT1/produto_reg[117]/Q -type DFF DFF
add mapped point MULT1/produto[118]/q MULT1/produto_reg[118]/Q -type DFF DFF
add mapped point MULT1/produto[119]/q MULT1/produto_reg[119]/Q -type DFF DFF
add mapped point MULT1/produto[120]/q MULT1/produto_reg[120]/Q -type DFF DFF
add mapped point MULT1/produto[121]/q MULT1/produto_reg[121]/Q -type DFF DFF
add mapped point MULT1/produto[122]/q MULT1/produto_reg[122]/Q -type DFF DFF
add mapped point MULT1/produto[123]/q MULT1/produto_reg[123]/Q -type DFF DFF
add mapped point MULT1/produto[124]/q MULT1/produto_reg[124]/Q -type DFF DFF
add mapped point MULT1/produto[125]/q MULT1/produto_reg[125]/Q -type DFF DFF
add mapped point MULT1/produto[126]/q MULT1/produto_reg[126]/Q -type DFF DFF
add mapped point MULT1/produto[127]/q MULT1/produto_reg[127]/Q -type DFF DFF
add mapped point MULT1/regP[0]/q MULT1/regP_reg[0]/Q -type DFF DFF
add mapped point MULT1/regP[1]/q MULT1/regP_reg[1]/Q -type DFF DFF
add mapped point MULT1/regP[2]/q MULT1/regP_reg[2]/Q -type DFF DFF
add mapped point MULT1/regP[3]/q MULT1/regP_reg[3]/Q -type DFF DFF
add mapped point MULT1/regP[4]/q MULT1/regP_reg[4]/Q -type DFF DFF
add mapped point MULT1/regP[5]/q MULT1/regP_reg[5]/Q -type DFF DFF
add mapped point MULT1/regP[6]/q MULT1/regP_reg[6]/Q -type DFF DFF
add mapped point MULT1/regP[7]/q MULT1/regP_reg[7]/Q -type DFF DFF
add mapped point MULT1/cont[0]/q MULT1/cont_reg[0]/Q -type DFF DFF
add mapped point MULT1/cont[1]/q MULT1/cont_reg[1]/Q -type DFF DFF
add mapped point MULT1/cont[2]/q MULT1/cont_reg[2]/Q -type DFF DFF
add mapped point MULT1/regP[8]/q MULT1/regP_reg[8]/Q -type DFF DFF
add mapped point MULT1/regP[9]/q MULT1/regP_reg[9]/Q -type DFF DFF
add mapped point MULT1/regP[10]/q MULT1/regP_reg[10]/Q -type DFF DFF
add mapped point MULT1/regP[11]/q MULT1/regP_reg[11]/Q -type DFF DFF
add mapped point MULT1/regP[12]/q MULT1/regP_reg[12]/Q -type DFF DFF
add mapped point MULT1/regP[13]/q MULT1/regP_reg[13]/Q -type DFF DFF
add mapped point MULT1/regP[14]/q MULT1/regP_reg[14]/Q -type DFF DFF
add mapped point MULT1/regP[15]/q MULT1/regP_reg[15]/Q -type DFF DFF
add mapped point MULT1/regP[16]/q MULT1/regP_reg[16]/Q -type DFF DFF
add mapped point MULT1/regP[17]/q MULT1/regP_reg[17]/Q -type DFF DFF
add mapped point MULT1/regP[18]/q MULT1/regP_reg[18]/Q -type DFF DFF
add mapped point MULT1/regP[19]/q MULT1/regP_reg[19]/Q -type DFF DFF
add mapped point MULT1/regP[20]/q MULT1/regP_reg[20]/Q -type DFF DFF
add mapped point MULT1/regP[21]/q MULT1/regP_reg[21]/Q -type DFF DFF
add mapped point MULT1/regP[22]/q MULT1/regP_reg[22]/Q -type DFF DFF
add mapped point MULT1/regP[23]/q MULT1/regP_reg[23]/Q -type DFF DFF
add mapped point MULT1/regP[24]/q MULT1/regP_reg[24]/Q -type DFF DFF
add mapped point MULT1/regP[25]/q MULT1/regP_reg[25]/Q -type DFF DFF
add mapped point MULT1/regP[26]/q MULT1/regP_reg[26]/Q -type DFF DFF
add mapped point MULT1/regP[27]/q MULT1/regP_reg[27]/Q -type DFF DFF
add mapped point MULT1/regP[28]/q MULT1/regP_reg[28]/Q -type DFF DFF
add mapped point MULT1/regP[29]/q MULT1/regP_reg[29]/Q -type DFF DFF
add mapped point MULT1/regP[30]/q MULT1/regP_reg[30]/Q -type DFF DFF
add mapped point MULT1/regP[31]/q MULT1/regP_reg[31]/Q -type DFF DFF
add mapped point MULT1/regP[32]/q MULT1/regP_reg[32]/Q -type DFF DFF
add mapped point MULT1/regP[33]/q MULT1/regP_reg[33]/Q -type DFF DFF
add mapped point MULT1/regP[34]/q MULT1/regP_reg[34]/Q -type DFF DFF
add mapped point MULT1/regP[35]/q MULT1/regP_reg[35]/Q -type DFF DFF
add mapped point MULT1/regP[36]/q MULT1/regP_reg[36]/Q -type DFF DFF
add mapped point MULT1/regP[37]/q MULT1/regP_reg[37]/Q -type DFF DFF
add mapped point MULT1/regP[38]/q MULT1/regP_reg[38]/Q -type DFF DFF
add mapped point MULT1/regP[39]/q MULT1/regP_reg[39]/Q -type DFF DFF
add mapped point MULT1/regP[40]/q MULT1/regP_reg[40]/Q -type DFF DFF
add mapped point MULT1/regP[41]/q MULT1/regP_reg[41]/Q -type DFF DFF
add mapped point MULT1/regP[42]/q MULT1/regP_reg[42]/Q -type DFF DFF
add mapped point MULT1/regP[43]/q MULT1/regP_reg[43]/Q -type DFF DFF
add mapped point MULT1/regP[44]/q MULT1/regP_reg[44]/Q -type DFF DFF
add mapped point MULT1/regP[45]/q MULT1/regP_reg[45]/Q -type DFF DFF
add mapped point MULT1/regP[46]/q MULT1/regP_reg[46]/Q -type DFF DFF
add mapped point MULT1/regP[47]/q MULT1/regP_reg[47]/Q -type DFF DFF
add mapped point MULT1/regP[48]/q MULT1/regP_reg[48]/Q -type DFF DFF
add mapped point MULT1/regP[49]/q MULT1/regP_reg[49]/Q -type DFF DFF
add mapped point MULT1/regP[50]/q MULT1/regP_reg[50]/Q -type DFF DFF
add mapped point MULT1/regP[51]/q MULT1/regP_reg[51]/Q -type DFF DFF
add mapped point MULT1/regP[52]/q MULT1/regP_reg[52]/Q -type DFF DFF
add mapped point MULT1/regP[53]/q MULT1/regP_reg[53]/Q -type DFF DFF
add mapped point MULT1/regP[54]/q MULT1/regP_reg[54]/Q -type DFF DFF
add mapped point MULT1/regP[55]/q MULT1/regP_reg[55]/Q -type DFF DFF
add mapped point MULT1/regP[56]/q MULT1/regP_reg[56]/Q -type DFF DFF
add mapped point MULT1/regP[57]/q MULT1/regP_reg[57]/Q -type DFF DFF
add mapped point MULT1/regP[58]/q MULT1/regP_reg[58]/Q -type DFF DFF
add mapped point MULT1/regP[59]/q MULT1/regP_reg[59]/Q -type DFF DFF
add mapped point MULT1/regP[60]/q MULT1/regP_reg[60]/Q -type DFF DFF
add mapped point MULT1/regP[61]/q MULT1/regP_reg[61]/Q -type DFF DFF
add mapped point MULT1/regP[62]/q MULT1/regP_reg[62]/Q -type DFF DFF
add mapped point MULT1/regP[63]/q MULT1/regP_reg[63]/Q -type DFF DFF
add mapped point MULT1/regP[64]/q MULT1/regP_reg[64]/Q -type DFF DFF
add mapped point MULT1/regP[65]/q MULT1/regP_reg[65]/Q -type DFF DFF
add mapped point MULT1/regP[66]/q MULT1/regP_reg[66]/Q -type DFF DFF
add mapped point MULT1/regP[67]/q MULT1/regP_reg[67]/Q -type DFF DFF
add mapped point MULT1/regP[68]/q MULT1/regP_reg[68]/Q -type DFF DFF
add mapped point MULT1/regP[69]/q MULT1/regP_reg[69]/Q -type DFF DFF
add mapped point MULT1/regP[70]/q MULT1/regP_reg[70]/Q -type DFF DFF
add mapped point MULT1/regP[71]/q MULT1/regP_reg[71]/Q -type DFF DFF
add mapped point MULT1/regP[72]/q MULT1/regP_reg[72]/Q -type DFF DFF
add mapped point MULT1/regP[73]/q MULT1/regP_reg[73]/Q -type DFF DFF
add mapped point MULT1/regP[74]/q MULT1/regP_reg[74]/Q -type DFF DFF
add mapped point MULT1/regP[75]/q MULT1/regP_reg[75]/Q -type DFF DFF
add mapped point MULT1/regP[76]/q MULT1/regP_reg[76]/Q -type DFF DFF
add mapped point MULT1/regP[77]/q MULT1/regP_reg[77]/Q -type DFF DFF
add mapped point MULT1/regP[78]/q MULT1/regP_reg[78]/Q -type DFF DFF
add mapped point MULT1/regP[79]/q MULT1/regP_reg[79]/Q -type DFF DFF
add mapped point MULT1/regP[80]/q MULT1/regP_reg[80]/Q -type DFF DFF
add mapped point MULT1/regP[81]/q MULT1/regP_reg[81]/Q -type DFF DFF
add mapped point MULT1/regP[82]/q MULT1/regP_reg[82]/Q -type DFF DFF
add mapped point MULT1/regP[83]/q MULT1/regP_reg[83]/Q -type DFF DFF
add mapped point MULT1/regP[84]/q MULT1/regP_reg[84]/Q -type DFF DFF
add mapped point MULT1/regP[85]/q MULT1/regP_reg[85]/Q -type DFF DFF
add mapped point MULT1/regP[86]/q MULT1/regP_reg[86]/Q -type DFF DFF
add mapped point MULT1/regP[87]/q MULT1/regP_reg[87]/Q -type DFF DFF
add mapped point MULT1/regP[88]/q MULT1/regP_reg[88]/Q -type DFF DFF
add mapped point MULT1/regP[89]/q MULT1/regP_reg[89]/Q -type DFF DFF
add mapped point MULT1/regP[90]/q MULT1/regP_reg[90]/Q -type DFF DFF
add mapped point MULT1/regP[91]/q MULT1/regP_reg[91]/Q -type DFF DFF
add mapped point MULT1/regP[92]/q MULT1/regP_reg[92]/Q -type DFF DFF
add mapped point MULT1/regP[93]/q MULT1/regP_reg[93]/Q -type DFF DFF
add mapped point MULT1/regP[94]/q MULT1/regP_reg[94]/Q -type DFF DFF
add mapped point MULT1/regP[95]/q MULT1/regP_reg[95]/Q -type DFF DFF
add mapped point MULT1/regP[96]/q MULT1/regP_reg[96]/Q -type DFF DFF
add mapped point MULT1/regP[97]/q MULT1/regP_reg[97]/Q -type DFF DFF
add mapped point MULT1/regP[98]/q MULT1/regP_reg[98]/Q -type DFF DFF
add mapped point MULT1/regP[99]/q MULT1/regP_reg[99]/Q -type DFF DFF
add mapped point MULT1/regP[100]/q MULT1/regP_reg[100]/Q -type DFF DFF
add mapped point MULT1/regP[101]/q MULT1/regP_reg[101]/Q -type DFF DFF
add mapped point MULT1/regP[102]/q MULT1/regP_reg[102]/Q -type DFF DFF
add mapped point MULT1/regP[103]/q MULT1/regP_reg[103]/Q -type DFF DFF
add mapped point MULT1/regP[104]/q MULT1/regP_reg[104]/Q -type DFF DFF
add mapped point MULT1/regP[105]/q MULT1/regP_reg[105]/Q -type DFF DFF
add mapped point MULT1/regP[106]/q MULT1/regP_reg[106]/Q -type DFF DFF
add mapped point MULT1/regP[107]/q MULT1/regP_reg[107]/Q -type DFF DFF
add mapped point MULT1/regP[108]/q MULT1/regP_reg[108]/Q -type DFF DFF
add mapped point MULT1/regP[109]/q MULT1/regP_reg[109]/Q -type DFF DFF
add mapped point MULT1/regP[110]/q MULT1/regP_reg[110]/Q -type DFF DFF
add mapped point MULT1/regP[111]/q MULT1/regP_reg[111]/Q -type DFF DFF
add mapped point MULT1/regP[112]/q MULT1/regP_reg[112]/Q -type DFF DFF
add mapped point MULT1/regP[113]/q MULT1/regP_reg[113]/Q -type DFF DFF
add mapped point MULT1/regP[114]/q MULT1/regP_reg[114]/Q -type DFF DFF
add mapped point MULT1/regP[115]/q MULT1/regP_reg[115]/Q -type DFF DFF
add mapped point MULT1/regP[116]/q MULT1/regP_reg[116]/Q -type DFF DFF
add mapped point MULT1/regP[117]/q MULT1/regP_reg[117]/Q -type DFF DFF
add mapped point MULT1/regP[118]/q MULT1/regP_reg[118]/Q -type DFF DFF
add mapped point MULT1/regP[119]/q MULT1/regP_reg[119]/Q -type DFF DFF
add mapped point MULT1/regP[120]/q MULT1/regP_reg[120]/Q -type DFF DFF
add mapped point MULT1/regP[121]/q MULT1/regP_reg[121]/Q -type DFF DFF
add mapped point MULT1/regP[122]/q MULT1/regP_reg[122]/Q -type DFF DFF
add mapped point MULT1/regP[123]/q MULT1/regP_reg[123]/Q -type DFF DFF
add mapped point MULT1/regP[124]/q MULT1/regP_reg[124]/Q -type DFF DFF
add mapped point MULT1/regP[125]/q MULT1/regP_reg[125]/Q -type DFF DFF
add mapped point MULT1/regP[126]/q MULT1/regP_reg[126]/Q -type DFF DFF
add mapped point MULT1/regP[127]/q MULT1/regP_reg[127]/Q -type DFF DFF
add mapped point MULT1/regP[128]/q MULT1/regP_reg[128]/Q -type DFF DFF
add mapped point MULT1/state[0]/q MULT1/state_reg[0]/Q -type DFF DFF
add mapped point MULT1/state[1]/q MULT1/state_reg[1]/Q -type DFF DFF
add mapped point op2[127]/q op2_reg[127]/Q -type DFF DFF
add mapped point op2[126]/q op2_reg[126]/Q -type DFF DFF
add mapped point op2[125]/q op2_reg[125]/Q -type DFF DFF
add mapped point op2[124]/q op2_reg[124]/Q -type DFF DFF
add mapped point op2[123]/q op2_reg[123]/Q -type DFF DFF
add mapped point op2[122]/q op2_reg[122]/Q -type DFF DFF
add mapped point op2[120]/q op2_reg[120]/Q -type DFF DFF
add mapped point op2[121]/q op2_reg[121]/Q -type DFF DFF
add mapped point cont[3]/q cont_reg[3]/Q -type DFF DFF
add mapped point cont[2]/q cont_reg[2]/Q -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q -type DFF DFF
add mapped point state[2]/q state_reg[2]/Q -type DFF DFF
add mapped point cont[1]/q cont_reg[1]/Q -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q -type DFF DFF
add mapped point cont[0]/q cont_reg[0]/Q -type DFF DFF
add mapped point end_expo/q end_expo_reg/Q -type DFF DFF
add mapped point op1[0]/q op1_reg[0]/Q -type DFF DFF
add mapped point op1[1]/q op1_reg[1]/Q -type DFF DFF
add mapped point op1[2]/q op1_reg[2]/Q -type DFF DFF
add mapped point op1[3]/q op1_reg[3]/Q -type DFF DFF
add mapped point op1[4]/q op1_reg[4]/Q -type DFF DFF
add mapped point op1[5]/q op1_reg[5]/Q -type DFF DFF
add mapped point op1[6]/q op1_reg[6]/Q -type DFF DFF
add mapped point op1[7]/q op1_reg[7]/Q -type DFF DFF
add mapped point op2[0]/q op2_reg[0]/Q -type DFF DFF
add mapped point op2[1]/q op2_reg[1]/Q -type DFF DFF
add mapped point op2[2]/q op2_reg[2]/Q -type DFF DFF
add mapped point op2[3]/q op2_reg[3]/Q -type DFF DFF
add mapped point op2[4]/q op2_reg[4]/Q -type DFF DFF
add mapped point op2[5]/q op2_reg[5]/Q -type DFF DFF
add mapped point op2[6]/q op2_reg[6]/Q -type DFF DFF
add mapped point op2[7]/q op2_reg[7]/Q -type DFF DFF
add mapped point op2[8]/q op2_reg[8]/Q -type DFF DFF
add mapped point op2[9]/q op2_reg[9]/Q -type DFF DFF
add mapped point op2[10]/q op2_reg[10]/Q -type DFF DFF
add mapped point op2[11]/q op2_reg[11]/Q -type DFF DFF
add mapped point op2[12]/q op2_reg[12]/Q -type DFF DFF
add mapped point op2[13]/q op2_reg[13]/Q -type DFF DFF
add mapped point op2[14]/q op2_reg[14]/Q -type DFF DFF
add mapped point op2[15]/q op2_reg[15]/Q -type DFF DFF
add mapped point op2[16]/q op2_reg[16]/Q -type DFF DFF
add mapped point op2[17]/q op2_reg[17]/Q -type DFF DFF
add mapped point op2[18]/q op2_reg[18]/Q -type DFF DFF
add mapped point op2[19]/q op2_reg[19]/Q -type DFF DFF
add mapped point op2[20]/q op2_reg[20]/Q -type DFF DFF
add mapped point op2[21]/q op2_reg[21]/Q -type DFF DFF
add mapped point op2[22]/q op2_reg[22]/Q -type DFF DFF
add mapped point op2[23]/q op2_reg[23]/Q -type DFF DFF
add mapped point op2[24]/q op2_reg[24]/Q -type DFF DFF
add mapped point op2[25]/q op2_reg[25]/Q -type DFF DFF
add mapped point op2[26]/q op2_reg[26]/Q -type DFF DFF
add mapped point op2[27]/q op2_reg[27]/Q -type DFF DFF
add mapped point op2[28]/q op2_reg[28]/Q -type DFF DFF
add mapped point op2[29]/q op2_reg[29]/Q -type DFF DFF
add mapped point op2[30]/q op2_reg[30]/Q -type DFF DFF
add mapped point op2[31]/q op2_reg[31]/Q -type DFF DFF
add mapped point op2[32]/q op2_reg[32]/Q -type DFF DFF
add mapped point op2[33]/q op2_reg[33]/Q -type DFF DFF
add mapped point op2[34]/q op2_reg[34]/Q -type DFF DFF
add mapped point op2[35]/q op2_reg[35]/Q -type DFF DFF
add mapped point op2[36]/q op2_reg[36]/Q -type DFF DFF
add mapped point op2[37]/q op2_reg[37]/Q -type DFF DFF
add mapped point op2[38]/q op2_reg[38]/Q -type DFF DFF
add mapped point op2[39]/q op2_reg[39]/Q -type DFF DFF
add mapped point op2[40]/q op2_reg[40]/Q -type DFF DFF
add mapped point op2[41]/q op2_reg[41]/Q -type DFF DFF
add mapped point op2[42]/q op2_reg[42]/Q -type DFF DFF
add mapped point op2[43]/q op2_reg[43]/Q -type DFF DFF
add mapped point op2[44]/q op2_reg[44]/Q -type DFF DFF
add mapped point op2[45]/q op2_reg[45]/Q -type DFF DFF
add mapped point op2[46]/q op2_reg[46]/Q -type DFF DFF
add mapped point op2[47]/q op2_reg[47]/Q -type DFF DFF
add mapped point op2[48]/q op2_reg[48]/Q -type DFF DFF
add mapped point op2[49]/q op2_reg[49]/Q -type DFF DFF
add mapped point op2[50]/q op2_reg[50]/Q -type DFF DFF
add mapped point op2[51]/q op2_reg[51]/Q -type DFF DFF
add mapped point op2[52]/q op2_reg[52]/Q -type DFF DFF
add mapped point op2[53]/q op2_reg[53]/Q -type DFF DFF
add mapped point op2[54]/q op2_reg[54]/Q -type DFF DFF
add mapped point op2[55]/q op2_reg[55]/Q -type DFF DFF
add mapped point op2[56]/q op2_reg[56]/Q -type DFF DFF
add mapped point op2[57]/q op2_reg[57]/Q -type DFF DFF
add mapped point op2[58]/q op2_reg[58]/Q -type DFF DFF
add mapped point op2[59]/q op2_reg[59]/Q -type DFF DFF
add mapped point op2[60]/q op2_reg[60]/Q -type DFF DFF
add mapped point op2[61]/q op2_reg[61]/Q -type DFF DFF
add mapped point op2[62]/q op2_reg[62]/Q -type DFF DFF
add mapped point op2[63]/q op2_reg[63]/Q -type DFF DFF
add mapped point op2[64]/q op2_reg[64]/Q -type DFF DFF
add mapped point op2[65]/q op2_reg[65]/Q -type DFF DFF
add mapped point op2[66]/q op2_reg[66]/Q -type DFF DFF
add mapped point op2[67]/q op2_reg[67]/Q -type DFF DFF
add mapped point op2[68]/q op2_reg[68]/Q -type DFF DFF
add mapped point op2[69]/q op2_reg[69]/Q -type DFF DFF
add mapped point op2[70]/q op2_reg[70]/Q -type DFF DFF
add mapped point op2[71]/q op2_reg[71]/Q -type DFF DFF
add mapped point op2[72]/q op2_reg[72]/Q -type DFF DFF
add mapped point op2[73]/q op2_reg[73]/Q -type DFF DFF
add mapped point op2[74]/q op2_reg[74]/Q -type DFF DFF
add mapped point op2[75]/q op2_reg[75]/Q -type DFF DFF
add mapped point op2[76]/q op2_reg[76]/Q -type DFF DFF
add mapped point op2[77]/q op2_reg[77]/Q -type DFF DFF
add mapped point op2[78]/q op2_reg[78]/Q -type DFF DFF
add mapped point op2[79]/q op2_reg[79]/Q -type DFF DFF
add mapped point op2[80]/q op2_reg[80]/Q -type DFF DFF
add mapped point op2[81]/q op2_reg[81]/Q -type DFF DFF
add mapped point op2[82]/q op2_reg[82]/Q -type DFF DFF
add mapped point op2[83]/q op2_reg[83]/Q -type DFF DFF
add mapped point op2[84]/q op2_reg[84]/Q -type DFF DFF
add mapped point op2[85]/q op2_reg[85]/Q -type DFF DFF
add mapped point op2[86]/q op2_reg[86]/Q -type DFF DFF
add mapped point op2[87]/q op2_reg[87]/Q -type DFF DFF
add mapped point op2[88]/q op2_reg[88]/Q -type DFF DFF
add mapped point op2[89]/q op2_reg[89]/Q -type DFF DFF
add mapped point op2[90]/q op2_reg[90]/Q -type DFF DFF
add mapped point op2[91]/q op2_reg[91]/Q -type DFF DFF
add mapped point op2[92]/q op2_reg[92]/Q -type DFF DFF
add mapped point op2[93]/q op2_reg[93]/Q -type DFF DFF
add mapped point op2[94]/q op2_reg[94]/Q -type DFF DFF
add mapped point op2[95]/q op2_reg[95]/Q -type DFF DFF
add mapped point op2[96]/q op2_reg[96]/Q -type DFF DFF
add mapped point op2[97]/q op2_reg[97]/Q -type DFF DFF
add mapped point op2[98]/q op2_reg[98]/Q -type DFF DFF
add mapped point op2[99]/q op2_reg[99]/Q -type DFF DFF
add mapped point op2[100]/q op2_reg[100]/Q -type DFF DFF
add mapped point op2[101]/q op2_reg[101]/Q -type DFF DFF
add mapped point op2[102]/q op2_reg[102]/Q -type DFF DFF
add mapped point op2[103]/q op2_reg[103]/Q -type DFF DFF
add mapped point op2[104]/q op2_reg[104]/Q -type DFF DFF
add mapped point op2[105]/q op2_reg[105]/Q -type DFF DFF
add mapped point op2[106]/q op2_reg[106]/Q -type DFF DFF
add mapped point op2[107]/q op2_reg[107]/Q -type DFF DFF
add mapped point op2[108]/q op2_reg[108]/Q -type DFF DFF
add mapped point op2[109]/q op2_reg[109]/Q -type DFF DFF
add mapped point op2[110]/q op2_reg[110]/Q -type DFF DFF
add mapped point op2[111]/q op2_reg[111]/Q -type DFF DFF
add mapped point op2[112]/q op2_reg[112]/Q -type DFF DFF
add mapped point op2[113]/q op2_reg[113]/Q -type DFF DFF
add mapped point op2[114]/q op2_reg[114]/Q -type DFF DFF
add mapped point op2[115]/q op2_reg[115]/Q -type DFF DFF
add mapped point op2[116]/q op2_reg[116]/Q -type DFF DFF
add mapped point op2[117]/q op2_reg[117]/Q -type DFF DFF
add mapped point op2[118]/q op2_reg[118]/Q -type DFF DFF
add mapped point op2[119]/q op2_reg[119]/Q -type DFF DFF
add mapped point resultado[0]/q resultado_reg[0]/Q -type DFF DFF
add mapped point resultado[1]/q resultado_reg[1]/Q -type DFF DFF
add mapped point resultado[2]/q resultado_reg[2]/Q -type DFF DFF
add mapped point resultado[3]/q resultado_reg[3]/Q -type DFF DFF
add mapped point resultado[4]/q resultado_reg[4]/Q -type DFF DFF
add mapped point resultado[5]/q resultado_reg[5]/Q -type DFF DFF
add mapped point resultado[6]/q resultado_reg[6]/Q -type DFF DFF
add mapped point resultado[7]/q resultado_reg[7]/Q -type DFF DFF
add mapped point resultado[8]/q resultado_reg[8]/Q -type DFF DFF
add mapped point resultado[9]/q resultado_reg[9]/Q -type DFF DFF
add mapped point resultado[10]/q resultado_reg[10]/Q -type DFF DFF
add mapped point resultado[11]/q resultado_reg[11]/Q -type DFF DFF
add mapped point resultado[12]/q resultado_reg[12]/Q -type DFF DFF
add mapped point resultado[13]/q resultado_reg[13]/Q -type DFF DFF
add mapped point resultado[14]/q resultado_reg[14]/Q -type DFF DFF
add mapped point resultado[15]/q resultado_reg[15]/Q -type DFF DFF
add mapped point resultado[16]/q resultado_reg[16]/Q -type DFF DFF
add mapped point resultado[17]/q resultado_reg[17]/Q -type DFF DFF
add mapped point resultado[18]/q resultado_reg[18]/Q -type DFF DFF
add mapped point resultado[19]/q resultado_reg[19]/Q -type DFF DFF
add mapped point resultado[20]/q resultado_reg[20]/Q -type DFF DFF
add mapped point resultado[21]/q resultado_reg[21]/Q -type DFF DFF
add mapped point resultado[22]/q resultado_reg[22]/Q -type DFF DFF
add mapped point resultado[23]/q resultado_reg[23]/Q -type DFF DFF
add mapped point resultado[24]/q resultado_reg[24]/Q -type DFF DFF
add mapped point resultado[25]/q resultado_reg[25]/Q -type DFF DFF
add mapped point resultado[26]/q resultado_reg[26]/Q -type DFF DFF
add mapped point resultado[27]/q resultado_reg[27]/Q -type DFF DFF
add mapped point resultado[28]/q resultado_reg[28]/Q -type DFF DFF
add mapped point resultado[29]/q resultado_reg[29]/Q -type DFF DFF
add mapped point resultado[30]/q resultado_reg[30]/Q -type DFF DFF
add mapped point resultado[31]/q resultado_reg[31]/Q -type DFF DFF
add mapped point resultado[32]/q resultado_reg[32]/Q -type DFF DFF
add mapped point resultado[33]/q resultado_reg[33]/Q -type DFF DFF
add mapped point resultado[34]/q resultado_reg[34]/Q -type DFF DFF
add mapped point resultado[35]/q resultado_reg[35]/Q -type DFF DFF
add mapped point resultado[36]/q resultado_reg[36]/Q -type DFF DFF
add mapped point resultado[37]/q resultado_reg[37]/Q -type DFF DFF
add mapped point resultado[38]/q resultado_reg[38]/Q -type DFF DFF
add mapped point resultado[39]/q resultado_reg[39]/Q -type DFF DFF
add mapped point resultado[40]/q resultado_reg[40]/Q -type DFF DFF
add mapped point resultado[41]/q resultado_reg[41]/Q -type DFF DFF
add mapped point resultado[42]/q resultado_reg[42]/Q -type DFF DFF
add mapped point resultado[43]/q resultado_reg[43]/Q -type DFF DFF
add mapped point resultado[44]/q resultado_reg[44]/Q -type DFF DFF
add mapped point resultado[45]/q resultado_reg[45]/Q -type DFF DFF
add mapped point resultado[46]/q resultado_reg[46]/Q -type DFF DFF
add mapped point resultado[47]/q resultado_reg[47]/Q -type DFF DFF
add mapped point resultado[48]/q resultado_reg[48]/Q -type DFF DFF
add mapped point resultado[49]/q resultado_reg[49]/Q -type DFF DFF
add mapped point resultado[50]/q resultado_reg[50]/Q -type DFF DFF
add mapped point resultado[51]/q resultado_reg[51]/Q -type DFF DFF
add mapped point resultado[52]/q resultado_reg[52]/Q -type DFF DFF
add mapped point resultado[53]/q resultado_reg[53]/Q -type DFF DFF
add mapped point resultado[54]/q resultado_reg[54]/Q -type DFF DFF
add mapped point resultado[55]/q resultado_reg[55]/Q -type DFF DFF
add mapped point resultado[56]/q resultado_reg[56]/Q -type DFF DFF
add mapped point resultado[57]/q resultado_reg[57]/Q -type DFF DFF
add mapped point resultado[58]/q resultado_reg[58]/Q -type DFF DFF
add mapped point resultado[59]/q resultado_reg[59]/Q -type DFF DFF
add mapped point resultado[60]/q resultado_reg[60]/Q -type DFF DFF
add mapped point resultado[61]/q resultado_reg[61]/Q -type DFF DFF
add mapped point resultado[62]/q resultado_reg[62]/Q -type DFF DFF
add mapped point resultado[63]/q resultado_reg[63]/Q -type DFF DFF
add mapped point resultado[64]/q resultado_reg[64]/Q -type DFF DFF
add mapped point resultado[65]/q resultado_reg[65]/Q -type DFF DFF
add mapped point resultado[66]/q resultado_reg[66]/Q -type DFF DFF
add mapped point resultado[67]/q resultado_reg[67]/Q -type DFF DFF
add mapped point resultado[68]/q resultado_reg[68]/Q -type DFF DFF
add mapped point resultado[69]/q resultado_reg[69]/Q -type DFF DFF
add mapped point resultado[70]/q resultado_reg[70]/Q -type DFF DFF
add mapped point resultado[71]/q resultado_reg[71]/Q -type DFF DFF
add mapped point resultado[72]/q resultado_reg[72]/Q -type DFF DFF
add mapped point resultado[73]/q resultado_reg[73]/Q -type DFF DFF
add mapped point resultado[74]/q resultado_reg[74]/Q -type DFF DFF
add mapped point resultado[75]/q resultado_reg[75]/Q -type DFF DFF
add mapped point resultado[76]/q resultado_reg[76]/Q -type DFF DFF
add mapped point resultado[77]/q resultado_reg[77]/Q -type DFF DFF
add mapped point resultado[78]/q resultado_reg[78]/Q -type DFF DFF
add mapped point resultado[79]/q resultado_reg[79]/Q -type DFF DFF
add mapped point resultado[80]/q resultado_reg[80]/Q -type DFF DFF
add mapped point resultado[81]/q resultado_reg[81]/Q -type DFF DFF
add mapped point resultado[82]/q resultado_reg[82]/Q -type DFF DFF
add mapped point resultado[83]/q resultado_reg[83]/Q -type DFF DFF
add mapped point resultado[84]/q resultado_reg[84]/Q -type DFF DFF
add mapped point resultado[85]/q resultado_reg[85]/Q -type DFF DFF
add mapped point resultado[86]/q resultado_reg[86]/Q -type DFF DFF
add mapped point resultado[87]/q resultado_reg[87]/Q -type DFF DFF
add mapped point resultado[88]/q resultado_reg[88]/Q -type DFF DFF
add mapped point resultado[89]/q resultado_reg[89]/Q -type DFF DFF
add mapped point resultado[90]/q resultado_reg[90]/Q -type DFF DFF
add mapped point resultado[91]/q resultado_reg[91]/Q -type DFF DFF
add mapped point resultado[92]/q resultado_reg[92]/Q -type DFF DFF
add mapped point resultado[93]/q resultado_reg[93]/Q -type DFF DFF
add mapped point resultado[94]/q resultado_reg[94]/Q -type DFF DFF
add mapped point resultado[95]/q resultado_reg[95]/Q -type DFF DFF
add mapped point resultado[96]/q resultado_reg[96]/Q -type DFF DFF
add mapped point resultado[97]/q resultado_reg[97]/Q -type DFF DFF
add mapped point resultado[98]/q resultado_reg[98]/Q -type DFF DFF
add mapped point resultado[99]/q resultado_reg[99]/Q -type DFF DFF
add mapped point resultado[100]/q resultado_reg[100]/Q -type DFF DFF
add mapped point resultado[101]/q resultado_reg[101]/Q -type DFF DFF
add mapped point resultado[102]/q resultado_reg[102]/Q -type DFF DFF
add mapped point resultado[103]/q resultado_reg[103]/Q -type DFF DFF
add mapped point resultado[104]/q resultado_reg[104]/Q -type DFF DFF
add mapped point resultado[105]/q resultado_reg[105]/Q -type DFF DFF
add mapped point resultado[106]/q resultado_reg[106]/Q -type DFF DFF
add mapped point resultado[107]/q resultado_reg[107]/Q -type DFF DFF
add mapped point resultado[108]/q resultado_reg[108]/Q -type DFF DFF
add mapped point resultado[109]/q resultado_reg[109]/Q -type DFF DFF
add mapped point resultado[110]/q resultado_reg[110]/Q -type DFF DFF
add mapped point resultado[111]/q resultado_reg[111]/Q -type DFF DFF
add mapped point resultado[112]/q resultado_reg[112]/Q -type DFF DFF
add mapped point resultado[113]/q resultado_reg[113]/Q -type DFF DFF
add mapped point resultado[114]/q resultado_reg[114]/Q -type DFF DFF
add mapped point resultado[115]/q resultado_reg[115]/Q -type DFF DFF
add mapped point resultado[116]/q resultado_reg[116]/Q -type DFF DFF
add mapped point resultado[117]/q resultado_reg[117]/Q -type DFF DFF
add mapped point resultado[118]/q resultado_reg[118]/Q -type DFF DFF
add mapped point resultado[119]/q resultado_reg[119]/Q -type DFF DFF
add mapped point resultado[120]/q resultado_reg[120]/Q -type DFF DFF
add mapped point resultado[121]/q resultado_reg[121]/Q -type DFF DFF
add mapped point resultado[122]/q resultado_reg[122]/Q -type DFF DFF
add mapped point resultado[123]/q resultado_reg[123]/Q -type DFF DFF
add mapped point resultado[124]/q resultado_reg[124]/Q -type DFF DFF
add mapped point resultado[125]/q resultado_reg[125]/Q -type DFF DFF
add mapped point resultado[126]/q resultado_reg[126]/Q -type DFF DFF
add mapped point resultado[127]/q resultado_reg[127]/Q -type DFF DFF
add mapped point start_mult/q start_mult_reg/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
