
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr 11 2025 14:23:55 -03 (Apr 11 2025 17:23:55 UTC)

// Verification Directory fv/cla_16bits 

module carry(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__2398(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_97(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__5107(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_96(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__6260(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_95(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__4319(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_94(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__8428(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_93(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__5526(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_92(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__6783(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_91(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__3680(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_90(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__1617(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_89(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__2802(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_88(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__1705(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_87(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__5122(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_86(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__8246(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_85(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__7098(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_84(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__6131(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module carry_83(Gi, Pi, Cin, Ci);
  input Gi, Pi, Cin;
  output Ci;
  wire Gi, Pi, Cin;
  wire Ci;
  sky130_fd_sc_hd__a21o_1 g13__1881(.A1 (Pi), .A2 (Cin), .B1 (Gi), .X
       (Ci));
endmodule

module cla4x3(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30, P20,
     P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__5115(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__7482(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__4733(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__6161(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__9315(.A1 (P1), .A2 (G0), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__9945(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_104(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__2883(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__2346(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__1666(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__7410(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__6417(.A1 (P1), .A2 (G0), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__5477(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_103(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__2398(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__5107(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__6260(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__4319(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__8428(.A1 (P1), .A2 (G0), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__5526(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_102(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__6783(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__3680(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__1617(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__2802(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__1705(.A1 (P1), .A2 (G0), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__5122(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_101(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__8246(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__7098(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__6131(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__1881(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__5115(.A1 (G0), .A2 (P1), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__7482(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_100(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__4733(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__6161(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__9315(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__9945(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__2883(.A1 (G0), .A2 (P1), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__2346(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_99(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__1666(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__7410(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__6417(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__5477(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__2398(.A1 (G0), .A2 (P1), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__5107(.A (P0), .B (P1), .X (P10));
endmodule

module cla4x3_98(G3, G2, G1, G0, P3, P2, P1, P0, G30, G20, G10, P30,
     P20, P10);
  input G3, G2, G1, G0, P3, P2, P1, P0;
  output G30, G20, G10, P30, P20, P10;
  wire G3, G2, G1, G0, P3, P2, P1, P0;
  wire G30, G20, G10, P30, P20, P10;
  sky130_fd_sc_hd__a21o_1 g99__6260(.A1 (G20), .A2 (P3), .B1 (G3), .X
       (G30));
  sky130_fd_sc_hd__a21o_1 g100__4319(.A1 (G10), .A2 (P2), .B1 (G2), .X
       (G20));
  sky130_fd_sc_hd__and2_1 g101__8428(.A (P20), .B (P3), .X (P30));
  sky130_fd_sc_hd__and2_1 g102__5526(.A (P10), .B (P2), .X (P20));
  sky130_fd_sc_hd__a21o_1 g103__6783(.A1 (G0), .A2 (P1), .B1 (G1), .X
       (G10));
  sky130_fd_sc_hd__and2_1 g104__3680(.A (P0), .B (P1), .X (P10));
endmodule

module generate_i(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__1617(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__2802(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_119(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__1705(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_134(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__5122(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_118(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__8246(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_133(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__7098(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_117(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__6131(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_132(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__1881(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_116(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__5115(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_131(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__7482(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_115(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__4733(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_130(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__6161(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_114(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__9315(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_129(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__9945(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_113(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__2883(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_128(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__2346(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_112(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__1666(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_127(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__7410(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_111(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__6417(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_126(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__5477(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_110(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__2398(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_125(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__5107(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_109(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__6260(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_124(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__4319(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_108(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__8428(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_123(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__5526(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_107(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__6783(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_122(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__3680(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_106(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__1617(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_121(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__2802(.A (Bi), .B (Ai), .X (Pi));
endmodule

module generate_i_105(Ai, Bi, Gi);
  input Ai, Bi;
  output Gi;
  wire Ai, Bi;
  wire Gi;
  sky130_fd_sc_hd__and2_1 g11__1705(.A (Bi), .B (Ai), .X (Gi));
endmodule

module propagate_i_120(Ai, Bi, Pi);
  input Ai, Bi;
  output Pi;
  wire Ai, Bi;
  wire Pi;
  sky130_fd_sc_hd__xor2_1 g10__5122(.A (Bi), .B (Ai), .X (Pi));
endmodule

module soutput(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__8246(.A (Cant), .B (Pi), .X (Si));
endmodule

module soutput_149(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__7098(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_148(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__6131(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_147(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__1881(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_146(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__5115(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_145(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__7482(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_144(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__4733(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_143(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__6161(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_142(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__9315(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_141(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__9945(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_140(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__2883(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_139(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__2346(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_138(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__1666(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_137(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__7410(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_136(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__6417(.A (Pi), .B (Cant), .X (Si));
endmodule

module soutput_135(Pi, Cant, Si);
  input Pi, Cant;
  output Si;
  wire Pi, Cant;
  wire Si;
  sky130_fd_sc_hd__xor2_1 g10__5477(.A (Pi), .B (Cant), .X (Si));
endmodule

module cla_16bits(A, B, Cin, S, Cout);
  input [15:0] A, B;
  input Cin;
  output [15:0] S;
  output Cout;
  wire [15:0] A, B;
  wire Cin;
  wire [15:0] S;
  wire Cout;
  wire [15:0] G;
  wire [15:0] P;
  wire [15:0] C;
  wire G0100, G0200, G0300, G0400, G0500, G0504, G0600, G0604;
  wire G0700, G0704, G0800, G0900, G0908, G1000, G1008, G1100;
  wire G1108, G1200, G1300, G1312, G1400, G1412, G1500, G1512;
  wire P0100, P0200, P0300, P0400, P0500, P0504, P0600, P0604;
  wire P0700, P0704, P0800, P0900, P0908, P1000, P1008, P1100;
  wire P1108, P1200, P1300, P1312, P1400, P1412, P1500, P1512;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33;
  carry C0(.Gi (G[0]), .Pi (P[0]), .Cin (n_33), .Ci (C[0]));
  carry_97 C1(.Gi (G0100), .Pi (P0100), .Cin (n_33), .Ci (C[1]));
  carry_96 C2(.Gi (G0200), .Pi (P0200), .Cin (n_33), .Ci (C[2]));
  carry_95 C3(.Gi (G0300), .Pi (P0300), .Cin (n_33), .Ci (C[3]));
  carry_94 C4(.Gi (G0400), .Pi (P0400), .Cin (n_33), .Ci (C[4]));
  carry_93 C5(.Gi (G0500), .Pi (P0500), .Cin (n_33), .Ci (C[5]));
  carry_92 C6(.Gi (G0600), .Pi (P0600), .Cin (n_33), .Ci (C[6]));
  carry_91 C7(.Gi (G0700), .Pi (P0700), .Cin (n_33), .Ci (C[7]));
  carry_90 C8(.Gi (G0800), .Pi (P0800), .Cin (n_33), .Ci (C[8]));
  carry_89 C9(.Gi (G0900), .Pi (P0900), .Cin (n_33), .Ci (C[9]));
  carry_88 C10(.Gi (G1000), .Pi (P1000), .Cin (n_33), .Ci (C[10]));
  carry_87 C11(.Gi (G1100), .Pi (P1100), .Cin (n_33), .Ci (C[11]));
  carry_86 C12(.Gi (G1200), .Pi (P1200), .Cin (n_33), .Ci (C[12]));
  carry_85 C13(.Gi (G1300), .Pi (P1300), .Cin (n_33), .Ci (C[13]));
  carry_84 C14(.Gi (G1400), .Pi (P1400), .Cin (n_33), .Ci (C[14]));
  carry_83 C15(.Gi (G1500), .Pi (P1500), .Cin (n_33), .Ci (Cout));
  cla4x3 CLA1(.G3 (G[3]), .G2 (G[2]), .G1 (G[1]), .G0 (G[0]), .P3
       (P[3]), .P2 (P[2]), .P1 (P[1]), .P0 (P[0]), .G30 (G0300), .G20
       (G0200), .G10 (G0100), .P30 (P0300), .P20 (P0200), .P10 (P0100));
  cla4x3_104 CLA2(.G3 (G[7]), .G2 (G[6]), .G1 (G[5]), .G0 (G[4]), .P3
       (P[7]), .P2 (P[6]), .P1 (P[5]), .P0 (P[4]), .G30 (G0704), .G20
       (G0604), .G10 (G0504), .P30 (P0704), .P20 (P0604), .P10 (P0504));
  cla4x3_103 CLA3(.G3 (G[11]), .G2 (G[10]), .G1 (G[9]), .G0 (G[8]), .P3
       (P[11]), .P2 (P[10]), .P1 (P[9]), .P0 (P[8]), .G30 (G1108), .G20
       (G1008), .G10 (G0908), .P30 (P1108), .P20 (P1008), .P10 (P0908));
  cla4x3_102 CLA4(.G3 (G[15]), .G2 (G[14]), .G1 (G[13]), .G0 (G[12]),
       .P3 (P[15]), .P2 (P[14]), .P1 (P[13]), .P0 (P[12]), .G30
       (G1512), .G20 (G1412), .G10 (G1312), .P30 (P1512), .P20 (P1412),
       .P10 (P1312));
  cla4x3_101 CLA5(.G3 (G1512), .G2 (G1108), .G1 (G0704), .G0 (G0300),
       .P3 (P1512), .P2 (P1108), .P1 (P0704), .P0 (P0300), .G30
       (G1500), .G20 (G1100), .G10 (G0700), .P30 (P1500), .P20 (P1100),
       .P10 (P0700));
  cla4x3_100 CLA6(.G3 (G1412), .G2 (G1312), .G1 (G[12]), .G0 (G1100),
       .P3 (P1412), .P2 (P1312), .P1 (P[12]), .P0 (P1100), .G30
       (G1400), .G20 (G1300), .G10 (G1200), .P30 (P1400), .P20 (P1300),
       .P10 (P1200));
  cla4x3_99 CLA7(.G3 (G1008), .G2 (G0908), .G1 (G[8]), .G0 (G0700), .P3
       (P1008), .P2 (P0908), .P1 (P[8]), .P0 (P0700), .G30 (G1000),
       .G20 (G0900), .G10 (G0800), .P30 (P1000), .P20 (P0900), .P10
       (P0800));
  cla4x3_98 CLA8(.G3 (G0604), .G2 (G0504), .G1 (G[4]), .G0 (G0300), .P3
       (P0604), .P2 (P0504), .P1 (P[4]), .P0 (P0300), .G30 (G0600),
       .G20 (G0500), .G10 (G0400), .P30 (P0600), .P20 (P0500), .P10
       (P0400));
  generate_i \GENERATE_PROPAGATE[0].GENERATE (.Ai (n_32), .Bi (n_31),
       .Gi (G[0]));
  propagate_i \GENERATE_PROPAGATE[0].PROPAGATE (.Ai (n_32), .Bi (n_31),
       .Pi (P[0]));
  generate_i_119 \GENERATE_PROPAGATE[1].GENERATE (.Ai (n_30), .Bi
       (n_29), .Gi (G[1]));
  propagate_i_134 \GENERATE_PROPAGATE[1].PROPAGATE (.Ai (n_30), .Bi
       (n_29), .Pi (P[1]));
  generate_i_118 \GENERATE_PROPAGATE[2].GENERATE (.Ai (n_28), .Bi
       (n_27), .Gi (G[2]));
  propagate_i_133 \GENERATE_PROPAGATE[2].PROPAGATE (.Ai (n_28), .Bi
       (n_27), .Pi (P[2]));
  generate_i_117 \GENERATE_PROPAGATE[3].GENERATE (.Ai (n_26), .Bi
       (n_25), .Gi (G[3]));
  propagate_i_132 \GENERATE_PROPAGATE[3].PROPAGATE (.Ai (n_26), .Bi
       (n_25), .Pi (P[3]));
  generate_i_116 \GENERATE_PROPAGATE[4].GENERATE (.Ai (n_24), .Bi
       (n_23), .Gi (G[4]));
  propagate_i_131 \GENERATE_PROPAGATE[4].PROPAGATE (.Ai (n_24), .Bi
       (n_23), .Pi (P[4]));
  generate_i_115 \GENERATE_PROPAGATE[5].GENERATE (.Ai (n_22), .Bi
       (n_21), .Gi (G[5]));
  propagate_i_130 \GENERATE_PROPAGATE[5].PROPAGATE (.Ai (n_22), .Bi
       (n_21), .Pi (P[5]));
  generate_i_114 \GENERATE_PROPAGATE[6].GENERATE (.Ai (n_20), .Bi
       (n_19), .Gi (G[6]));
  propagate_i_129 \GENERATE_PROPAGATE[6].PROPAGATE (.Ai (n_20), .Bi
       (n_19), .Pi (P[6]));
  generate_i_113 \GENERATE_PROPAGATE[7].GENERATE (.Ai (n_18), .Bi
       (n_17), .Gi (G[7]));
  propagate_i_128 \GENERATE_PROPAGATE[7].PROPAGATE (.Ai (n_18), .Bi
       (n_17), .Pi (P[7]));
  generate_i_112 \GENERATE_PROPAGATE[8].GENERATE (.Ai (n_16), .Bi
       (n_15), .Gi (G[8]));
  propagate_i_127 \GENERATE_PROPAGATE[8].PROPAGATE (.Ai (n_16), .Bi
       (n_15), .Pi (P[8]));
  generate_i_111 \GENERATE_PROPAGATE[9].GENERATE (.Ai (n_14), .Bi
       (n_13), .Gi (G[9]));
  propagate_i_126 \GENERATE_PROPAGATE[9].PROPAGATE (.Ai (n_14), .Bi
       (n_13), .Pi (P[9]));
  generate_i_110 \GENERATE_PROPAGATE[10].GENERATE (.Ai (n_12), .Bi
       (n_11), .Gi (G[10]));
  propagate_i_125 \GENERATE_PROPAGATE[10].PROPAGATE (.Ai (n_12), .Bi
       (n_11), .Pi (P[10]));
  generate_i_109 \GENERATE_PROPAGATE[11].GENERATE (.Ai (n_10), .Bi
       (n_9), .Gi (G[11]));
  propagate_i_124 \GENERATE_PROPAGATE[11].PROPAGATE (.Ai (n_10), .Bi
       (n_9), .Pi (P[11]));
  generate_i_108 \GENERATE_PROPAGATE[12].GENERATE (.Ai (n_8), .Bi
       (n_7), .Gi (G[12]));
  propagate_i_123 \GENERATE_PROPAGATE[12].PROPAGATE (.Ai (n_8), .Bi
       (n_7), .Pi (P[12]));
  generate_i_107 \GENERATE_PROPAGATE[13].GENERATE (.Ai (n_6), .Bi
       (n_5), .Gi (G[13]));
  propagate_i_122 \GENERATE_PROPAGATE[13].PROPAGATE (.Ai (n_6), .Bi
       (n_5), .Pi (P[13]));
  generate_i_106 \GENERATE_PROPAGATE[14].GENERATE (.Ai (n_4), .Bi
       (n_3), .Gi (G[14]));
  propagate_i_121 \GENERATE_PROPAGATE[14].PROPAGATE (.Ai (n_4), .Bi
       (n_3), .Pi (P[14]));
  generate_i_105 \GENERATE_PROPAGATE[15].GENERATE (.Ai (n_2), .Bi
       (n_1), .Gi (G[15]));
  propagate_i_120 \GENERATE_PROPAGATE[15].PROPAGATE (.Ai (n_2), .Bi
       (n_1), .Pi (P[15]));
  soutput S0(.Pi (P[0]), .Cant (n_33), .Si (S[0]));
  soutput_149 S1(.Pi (P[1]), .Cant (C[0]), .Si (S[1]));
  soutput_148 S2(.Pi (P[2]), .Cant (C[1]), .Si (S[2]));
  soutput_147 S3(.Pi (P[3]), .Cant (C[2]), .Si (S[3]));
  soutput_146 S4(.Pi (P[4]), .Cant (C[3]), .Si (S[4]));
  soutput_145 S5(.Pi (P[5]), .Cant (C[4]), .Si (S[5]));
  soutput_144 S6(.Pi (P[6]), .Cant (C[5]), .Si (S[6]));
  soutput_143 S7(.Pi (P[7]), .Cant (C[6]), .Si (S[7]));
  soutput_142 S8(.Pi (P[8]), .Cant (C[7]), .Si (S[8]));
  soutput_141 S9(.Pi (P[9]), .Cant (C[8]), .Si (S[9]));
  soutput_140 S10(.Pi (P[10]), .Cant (C[9]), .Si (S[10]));
  soutput_139 S11(.Pi (P[11]), .Cant (C[10]), .Si (S[11]));
  soutput_138 S12(.Pi (P[12]), .Cant (C[11]), .Si (S[12]));
  soutput_137 S13(.Pi (P[13]), .Cant (C[12]), .Si (S[13]));
  soutput_136 S14(.Pi (P[14]), .Cant (C[13]), .Si (S[14]));
  soutput_135 S15(.Pi (P[15]), .Cant (C[14]), .Si (S[15]));
  sky130_fd_sc_hd__inv_2 g33(.A (n_0), .Y (n_33));
  sky130_fd_sc_hd__inv_2 g34(.A (Cin), .Y (n_0));
  sky130_fd_sc_hd__clkbuf_1 g15(.A (B[11]), .X (n_9));
  sky130_fd_sc_hd__clkbuf_1 g2(.A (B[12]), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g26(.A (B[2]), .X (n_27));
  sky130_fd_sc_hd__clkbuf_1 g5(.A (A[6]), .X (n_20));
  sky130_fd_sc_hd__clkbuf_1 g16(.A (B[4]), .X (n_23));
  sky130_fd_sc_hd__clkbuf_1 g21(.A (A[12]), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g30(.A (A[2]), .X (n_28));
  sky130_fd_sc_hd__clkbuf_1 g27(.A (A[11]), .X (n_10));
  sky130_fd_sc_hd__clkbuf_1 g23(.A (B[14]), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g14(.A (A[10]), .X (n_12));
  sky130_fd_sc_hd__clkbuf_1 g20(.A (B[13]), .X (n_5));
  sky130_fd_sc_hd__clkbuf_1 g28(.A (A[7]), .X (n_18));
  sky130_fd_sc_hd__clkbuf_1 g13(.A (B[3]), .X (n_25));
  sky130_fd_sc_hd__clkbuf_1 g29(.A (B[7]), .X (n_17));
  sky130_fd_sc_hd__clkbuf_1 g3(.A (A[9]), .X (n_14));
  sky130_fd_sc_hd__clkbuf_1 g22(.A (A[15]), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g8(.A (A[13]), .X (n_6));
  sky130_fd_sc_hd__clkbuf_1 g31(.A (B[10]), .X (n_11));
  sky130_fd_sc_hd__clkbuf_1 g12(.A (A[5]), .X (n_22));
  sky130_fd_sc_hd__clkbuf_1 g11(.A (B[9]), .X (n_13));
  sky130_fd_sc_hd__clkbuf_1 g7(.A (A[14]), .X (n_4));
  sky130_fd_sc_hd__clkbuf_1 g4(.A (B[8]), .X (n_15));
  sky130_fd_sc_hd__clkbuf_1 g10(.A (B[0]), .X (n_31));
  sky130_fd_sc_hd__clkbuf_1 g17(.A (A[4]), .X (n_24));
  sky130_fd_sc_hd__clkbuf_1 g32(.A (B[6]), .X (n_19));
  sky130_fd_sc_hd__clkbuf_1 g1(.A (A[1]), .X (n_30));
  sky130_fd_sc_hd__clkbuf_1 g19(.A (A[3]), .X (n_26));
  sky130_fd_sc_hd__clkbuf_1 g18(.A (B[5]), .X (n_21));
  sky130_fd_sc_hd__clkbuf_1 g6(.A (A[8]), .X (n_16));
  sky130_fd_sc_hd__clkbuf_1 g25(.A (A[0]), .X (n_32));
  sky130_fd_sc_hd__clkbuf_1 g9(.A (B[15]), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g24(.A (B[1]), .X (n_29));
endmodule

