
//input ports
add mapped point clock clock -type PI PI
add mapped point reset reset -type PI PI
add mapped point start start -type PI PI
add mapped point A[31] A[31] -type PI PI
add mapped point A[30] A[30] -type PI PI
add mapped point A[29] A[29] -type PI PI
add mapped point A[28] A[28] -type PI PI
add mapped point A[27] A[27] -type PI PI
add mapped point A[26] A[26] -type PI PI
add mapped point A[25] A[25] -type PI PI
add mapped point A[24] A[24] -type PI PI
add mapped point A[23] A[23] -type PI PI
add mapped point A[22] A[22] -type PI PI
add mapped point A[21] A[21] -type PI PI
add mapped point A[20] A[20] -type PI PI
add mapped point A[19] A[19] -type PI PI
add mapped point A[18] A[18] -type PI PI
add mapped point A[17] A[17] -type PI PI
add mapped point A[16] A[16] -type PI PI
add mapped point A[15] A[15] -type PI PI
add mapped point A[14] A[14] -type PI PI
add mapped point A[13] A[13] -type PI PI
add mapped point A[12] A[12] -type PI PI
add mapped point A[11] A[11] -type PI PI
add mapped point A[10] A[10] -type PI PI
add mapped point A[9] A[9] -type PI PI
add mapped point A[8] A[8] -type PI PI
add mapped point A[7] A[7] -type PI PI
add mapped point A[6] A[6] -type PI PI
add mapped point A[5] A[5] -type PI PI
add mapped point A[4] A[4] -type PI PI
add mapped point A[3] A[3] -type PI PI
add mapped point A[2] A[2] -type PI PI
add mapped point A[1] A[1] -type PI PI
add mapped point A[0] A[0] -type PI PI
add mapped point B[31] B[31] -type PI PI
add mapped point B[30] B[30] -type PI PI
add mapped point B[29] B[29] -type PI PI
add mapped point B[28] B[28] -type PI PI
add mapped point B[27] B[27] -type PI PI
add mapped point B[26] B[26] -type PI PI
add mapped point B[25] B[25] -type PI PI
add mapped point B[24] B[24] -type PI PI
add mapped point B[23] B[23] -type PI PI
add mapped point B[22] B[22] -type PI PI
add mapped point B[21] B[21] -type PI PI
add mapped point B[20] B[20] -type PI PI
add mapped point B[19] B[19] -type PI PI
add mapped point B[18] B[18] -type PI PI
add mapped point B[17] B[17] -type PI PI
add mapped point B[16] B[16] -type PI PI
add mapped point B[15] B[15] -type PI PI
add mapped point B[14] B[14] -type PI PI
add mapped point B[13] B[13] -type PI PI
add mapped point B[12] B[12] -type PI PI
add mapped point B[11] B[11] -type PI PI
add mapped point B[10] B[10] -type PI PI
add mapped point B[9] B[9] -type PI PI
add mapped point B[8] B[8] -type PI PI
add mapped point B[7] B[7] -type PI PI
add mapped point B[6] B[6] -type PI PI
add mapped point B[5] B[5] -type PI PI
add mapped point B[4] B[4] -type PI PI
add mapped point B[3] B[3] -type PI PI
add mapped point B[2] B[2] -type PI PI
add mapped point B[1] B[1] -type PI PI
add mapped point B[0] B[0] -type PI PI

//output ports
add mapped point end_mul end_mul -type PO PO
add mapped point produto[63] produto[63] -type PO PO
add mapped point produto[62] produto[62] -type PO PO
add mapped point produto[61] produto[61] -type PO PO
add mapped point produto[60] produto[60] -type PO PO
add mapped point produto[59] produto[59] -type PO PO
add mapped point produto[58] produto[58] -type PO PO
add mapped point produto[57] produto[57] -type PO PO
add mapped point produto[56] produto[56] -type PO PO
add mapped point produto[55] produto[55] -type PO PO
add mapped point produto[54] produto[54] -type PO PO
add mapped point produto[53] produto[53] -type PO PO
add mapped point produto[52] produto[52] -type PO PO
add mapped point produto[51] produto[51] -type PO PO
add mapped point produto[50] produto[50] -type PO PO
add mapped point produto[49] produto[49] -type PO PO
add mapped point produto[48] produto[48] -type PO PO
add mapped point produto[47] produto[47] -type PO PO
add mapped point produto[46] produto[46] -type PO PO
add mapped point produto[45] produto[45] -type PO PO
add mapped point produto[44] produto[44] -type PO PO
add mapped point produto[43] produto[43] -type PO PO
add mapped point produto[42] produto[42] -type PO PO
add mapped point produto[41] produto[41] -type PO PO
add mapped point produto[40] produto[40] -type PO PO
add mapped point produto[39] produto[39] -type PO PO
add mapped point produto[38] produto[38] -type PO PO
add mapped point produto[37] produto[37] -type PO PO
add mapped point produto[36] produto[36] -type PO PO
add mapped point produto[35] produto[35] -type PO PO
add mapped point produto[34] produto[34] -type PO PO
add mapped point produto[33] produto[33] -type PO PO
add mapped point produto[32] produto[32] -type PO PO
add mapped point produto[31] produto[31] -type PO PO
add mapped point produto[30] produto[30] -type PO PO
add mapped point produto[29] produto[29] -type PO PO
add mapped point produto[28] produto[28] -type PO PO
add mapped point produto[27] produto[27] -type PO PO
add mapped point produto[26] produto[26] -type PO PO
add mapped point produto[25] produto[25] -type PO PO
add mapped point produto[24] produto[24] -type PO PO
add mapped point produto[23] produto[23] -type PO PO
add mapped point produto[22] produto[22] -type PO PO
add mapped point produto[21] produto[21] -type PO PO
add mapped point produto[20] produto[20] -type PO PO
add mapped point produto[19] produto[19] -type PO PO
add mapped point produto[18] produto[18] -type PO PO
add mapped point produto[17] produto[17] -type PO PO
add mapped point produto[16] produto[16] -type PO PO
add mapped point produto[15] produto[15] -type PO PO
add mapped point produto[14] produto[14] -type PO PO
add mapped point produto[13] produto[13] -type PO PO
add mapped point produto[12] produto[12] -type PO PO
add mapped point produto[11] produto[11] -type PO PO
add mapped point produto[10] produto[10] -type PO PO
add mapped point produto[9] produto[9] -type PO PO
add mapped point produto[8] produto[8] -type PO PO
add mapped point produto[7] produto[7] -type PO PO
add mapped point produto[6] produto[6] -type PO PO
add mapped point produto[5] produto[5] -type PO PO
add mapped point produto[4] produto[4] -type PO PO
add mapped point produto[3] produto[3] -type PO PO
add mapped point produto[2] produto[2] -type PO PO
add mapped point produto[1] produto[1] -type PO PO
add mapped point produto[0] produto[0] -type PO PO

//inout ports




//Sequential Pins
add mapped point end_mul/q end_mul_reg/Q -type DFF DFF
add mapped point produto[0]/q produto_reg[0]/Q -type DFF DFF
add mapped point produto[1]/q produto_reg[1]/Q -type DFF DFF
add mapped point produto[2]/q produto_reg[2]/Q -type DFF DFF
add mapped point produto[3]/q produto_reg[3]/Q -type DFF DFF
add mapped point produto[4]/q produto_reg[4]/Q -type DFF DFF
add mapped point produto[5]/q produto_reg[5]/Q -type DFF DFF
add mapped point produto[6]/q produto_reg[6]/Q -type DFF DFF
add mapped point produto[7]/q produto_reg[7]/Q -type DFF DFF
add mapped point produto[8]/q produto_reg[8]/Q -type DFF DFF
add mapped point produto[9]/q produto_reg[9]/Q -type DFF DFF
add mapped point produto[10]/q produto_reg[10]/Q -type DFF DFF
add mapped point produto[11]/q produto_reg[11]/Q -type DFF DFF
add mapped point produto[12]/q produto_reg[12]/Q -type DFF DFF
add mapped point produto[13]/q produto_reg[13]/Q -type DFF DFF
add mapped point produto[14]/q produto_reg[14]/Q -type DFF DFF
add mapped point produto[15]/q produto_reg[15]/Q -type DFF DFF
add mapped point produto[16]/q produto_reg[16]/Q -type DFF DFF
add mapped point produto[17]/q produto_reg[17]/Q -type DFF DFF
add mapped point produto[18]/q produto_reg[18]/Q -type DFF DFF
add mapped point produto[19]/q produto_reg[19]/Q -type DFF DFF
add mapped point produto[20]/q produto_reg[20]/Q -type DFF DFF
add mapped point produto[21]/q produto_reg[21]/Q -type DFF DFF
add mapped point produto[22]/q produto_reg[22]/Q -type DFF DFF
add mapped point produto[23]/q produto_reg[23]/Q -type DFF DFF
add mapped point produto[24]/q produto_reg[24]/Q -type DFF DFF
add mapped point produto[25]/q produto_reg[25]/Q -type DFF DFF
add mapped point produto[26]/q produto_reg[26]/Q -type DFF DFF
add mapped point produto[27]/q produto_reg[27]/Q -type DFF DFF
add mapped point produto[28]/q produto_reg[28]/Q -type DFF DFF
add mapped point produto[29]/q produto_reg[29]/Q -type DFF DFF
add mapped point produto[30]/q produto_reg[30]/Q -type DFF DFF
add mapped point produto[31]/q produto_reg[31]/Q -type DFF DFF
add mapped point produto[32]/q produto_reg[32]/Q -type DFF DFF
add mapped point produto[33]/q produto_reg[33]/Q -type DFF DFF
add mapped point produto[34]/q produto_reg[34]/Q -type DFF DFF
add mapped point produto[35]/q produto_reg[35]/Q -type DFF DFF
add mapped point produto[36]/q produto_reg[36]/Q -type DFF DFF
add mapped point produto[37]/q produto_reg[37]/Q -type DFF DFF
add mapped point produto[38]/q produto_reg[38]/Q -type DFF DFF
add mapped point produto[39]/q produto_reg[39]/Q -type DFF DFF
add mapped point produto[40]/q produto_reg[40]/Q -type DFF DFF
add mapped point produto[41]/q produto_reg[41]/Q -type DFF DFF
add mapped point produto[42]/q produto_reg[42]/Q -type DFF DFF
add mapped point produto[43]/q produto_reg[43]/Q -type DFF DFF
add mapped point produto[44]/q produto_reg[44]/Q -type DFF DFF
add mapped point produto[45]/q produto_reg[45]/Q -type DFF DFF
add mapped point produto[46]/q produto_reg[46]/Q -type DFF DFF
add mapped point produto[47]/q produto_reg[47]/Q -type DFF DFF
add mapped point produto[48]/q produto_reg[48]/Q -type DFF DFF
add mapped point produto[49]/q produto_reg[49]/Q -type DFF DFF
add mapped point produto[50]/q produto_reg[50]/Q -type DFF DFF
add mapped point produto[51]/q produto_reg[51]/Q -type DFF DFF
add mapped point produto[52]/q produto_reg[52]/Q -type DFF DFF
add mapped point produto[53]/q produto_reg[53]/Q -type DFF DFF
add mapped point produto[54]/q produto_reg[54]/Q -type DFF DFF
add mapped point produto[55]/q produto_reg[55]/Q -type DFF DFF
add mapped point produto[56]/q produto_reg[56]/Q -type DFF DFF
add mapped point produto[57]/q produto_reg[57]/Q -type DFF DFF
add mapped point produto[58]/q produto_reg[58]/Q -type DFF DFF
add mapped point produto[59]/q produto_reg[59]/Q -type DFF DFF
add mapped point produto[60]/q produto_reg[60]/Q -type DFF DFF
add mapped point produto[61]/q produto_reg[61]/Q -type DFF DFF
add mapped point produto[62]/q produto_reg[62]/Q -type DFF DFF
add mapped point produto[63]/q produto_reg[63]/Q -type DFF DFF
add mapped point regP[0]/q regP_reg[0]/Q -type DFF DFF
add mapped point regP[1]/q regP_reg[1]/Q -type DFF DFF
add mapped point regP[2]/q regP_reg[2]/Q -type DFF DFF
add mapped point regP[3]/q regP_reg[3]/Q -type DFF DFF
add mapped point regP[4]/q regP_reg[4]/Q -type DFF DFF
add mapped point regP[5]/q regP_reg[5]/Q -type DFF DFF
add mapped point regP[6]/q regP_reg[6]/Q -type DFF DFF
add mapped point regP[7]/q regP_reg[7]/Q -type DFF DFF
add mapped point regP[8]/q regP_reg[8]/Q -type DFF DFF
add mapped point regP[9]/q regP_reg[9]/Q -type DFF DFF
add mapped point regP[10]/q regP_reg[10]/Q -type DFF DFF
add mapped point regP[11]/q regP_reg[11]/Q -type DFF DFF
add mapped point regP[12]/q regP_reg[12]/Q -type DFF DFF
add mapped point regP[13]/q regP_reg[13]/Q -type DFF DFF
add mapped point regP[14]/q regP_reg[14]/Q -type DFF DFF
add mapped point regP[15]/q regP_reg[15]/Q -type DFF DFF
add mapped point regP[16]/q regP_reg[16]/Q -type DFF DFF
add mapped point regP[17]/q regP_reg[17]/Q -type DFF DFF
add mapped point regP[18]/q regP_reg[18]/Q -type DFF DFF
add mapped point regP[19]/q regP_reg[19]/Q -type DFF DFF
add mapped point regP[20]/q regP_reg[20]/Q -type DFF DFF
add mapped point regP[21]/q regP_reg[21]/Q -type DFF DFF
add mapped point regP[22]/q regP_reg[22]/Q -type DFF DFF
add mapped point regP[23]/q regP_reg[23]/Q -type DFF DFF
add mapped point regP[24]/q regP_reg[24]/Q -type DFF DFF
add mapped point regP[25]/q regP_reg[25]/Q -type DFF DFF
add mapped point regP[26]/q regP_reg[26]/Q -type DFF DFF
add mapped point regP[27]/q regP_reg[27]/Q -type DFF DFF
add mapped point regP[28]/q regP_reg[28]/Q -type DFF DFF
add mapped point regP[29]/q regP_reg[29]/Q -type DFF DFF
add mapped point regP[30]/q regP_reg[30]/Q -type DFF DFF
add mapped point regP[31]/q regP_reg[31]/Q -type DFF DFF
add mapped point cont[0]/q cont_reg[0]/Q -type DFF DFF
add mapped point cont[1]/q cont_reg[1]/Q -type DFF DFF
add mapped point cont[2]/q cont_reg[2]/Q -type DFF DFF
add mapped point cont[3]/q cont_reg[3]/Q -type DFF DFF
add mapped point cont[4]/q cont_reg[4]/Q -type DFF DFF
add mapped point regP[32]/q regP_reg[32]/Q -type DFF DFF
add mapped point regP[33]/q regP_reg[33]/Q -type DFF DFF
add mapped point regP[34]/q regP_reg[34]/Q -type DFF DFF
add mapped point regP[35]/q regP_reg[35]/Q -type DFF DFF
add mapped point regP[36]/q regP_reg[36]/Q -type DFF DFF
add mapped point regP[37]/q regP_reg[37]/Q -type DFF DFF
add mapped point regP[38]/q regP_reg[38]/Q -type DFF DFF
add mapped point regP[39]/q regP_reg[39]/Q -type DFF DFF
add mapped point regP[40]/q regP_reg[40]/Q -type DFF DFF
add mapped point regP[41]/q regP_reg[41]/Q -type DFF DFF
add mapped point regP[42]/q regP_reg[42]/Q -type DFF DFF
add mapped point regP[43]/q regP_reg[43]/Q -type DFF DFF
add mapped point regP[44]/q regP_reg[44]/Q -type DFF DFF
add mapped point regP[45]/q regP_reg[45]/Q -type DFF DFF
add mapped point regP[46]/q regP_reg[46]/Q -type DFF DFF
add mapped point regP[47]/q regP_reg[47]/Q -type DFF DFF
add mapped point regP[48]/q regP_reg[48]/Q -type DFF DFF
add mapped point regP[49]/q regP_reg[49]/Q -type DFF DFF
add mapped point regP[50]/q regP_reg[50]/Q -type DFF DFF
add mapped point regP[51]/q regP_reg[51]/Q -type DFF DFF
add mapped point regP[52]/q regP_reg[52]/Q -type DFF DFF
add mapped point regP[53]/q regP_reg[53]/Q -type DFF DFF
add mapped point regP[54]/q regP_reg[54]/Q -type DFF DFF
add mapped point regP[55]/q regP_reg[55]/Q -type DFF DFF
add mapped point regP[56]/q regP_reg[56]/Q -type DFF DFF
add mapped point regP[57]/q regP_reg[57]/Q -type DFF DFF
add mapped point regP[58]/q regP_reg[58]/Q -type DFF DFF
add mapped point regP[59]/q regP_reg[59]/Q -type DFF DFF
add mapped point regP[60]/q regP_reg[60]/Q -type DFF DFF
add mapped point regP[61]/q regP_reg[61]/Q -type DFF DFF
add mapped point regP[62]/q regP_reg[62]/Q -type DFF DFF
add mapped point regP[63]/q regP_reg[63]/Q -type DFF DFF
add mapped point regP[64]/q regP_reg[64]/Q -type DFF DFF
add mapped point state[0]/q state_reg[0]/Q -type DFF DFF
add mapped point state[1]/q state_reg[1]/Q -type DFF DFF



//Black Boxes



//Empty Modules as Blackboxes
