
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr 14 2025 15:06:01 -03 (Apr 14 2025 18:06:01 UTC)

// Verification Directory fv/signal_32bits 

module signal_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire addinc_add_7_30_n_0, addinc_add_7_30_n_1, addinc_add_7_30_n_2,
       addinc_add_7_30_n_3, addinc_add_7_30_n_4, addinc_add_7_30_n_5,
       addinc_add_7_30_n_6, addinc_add_7_30_n_7;
  wire addinc_add_7_30_n_8, addinc_add_7_30_n_9, addinc_add_7_30_n_10,
       addinc_add_7_30_n_11, addinc_add_7_30_n_12,
       addinc_add_7_30_n_13, addinc_add_7_30_n_14, addinc_add_7_30_n_15;
  wire addinc_add_7_30_n_16, addinc_add_7_30_n_17,
       addinc_add_7_30_n_18, addinc_add_7_30_n_19,
       addinc_add_7_30_n_20, addinc_add_7_30_n_21,
       addinc_add_7_30_n_22, addinc_add_7_30_n_23;
  wire addinc_add_7_30_n_24, addinc_add_7_30_n_25,
       addinc_add_7_30_n_26, addinc_add_7_30_n_27,
       addinc_add_7_30_n_28, addinc_add_7_30_n_29,
       addinc_add_7_30_n_30, addinc_add_7_30_n_31;
  wire addinc_add_7_30_n_32, addinc_add_7_30_n_33,
       addinc_add_7_30_n_34, addinc_add_7_30_n_35,
       addinc_add_7_30_n_36, addinc_add_7_30_n_37,
       addinc_add_7_30_n_38, addinc_add_7_30_n_39;
  wire addinc_add_7_30_n_40, addinc_add_7_30_n_41,
       addinc_add_7_30_n_42, addinc_add_7_30_n_43,
       addinc_add_7_30_n_44, addinc_add_7_30_n_45,
       addinc_add_7_30_n_46, addinc_add_7_30_n_47;
  wire addinc_add_7_30_n_48, addinc_add_7_30_n_49,
       addinc_add_7_30_n_50, addinc_add_7_30_n_51,
       addinc_add_7_30_n_52, addinc_add_7_30_n_53,
       addinc_add_7_30_n_54, addinc_add_7_30_n_55;
  wire addinc_add_7_30_n_56, addinc_add_7_30_n_57,
       addinc_add_7_30_n_58, addinc_add_7_30_n_59,
       addinc_add_7_30_n_60, addinc_add_7_30_n_61,
       addinc_add_7_30_n_62, addinc_add_7_30_n_63;
  wire addinc_add_7_30_n_64, addinc_add_7_30_n_65,
       addinc_add_7_30_n_66, addinc_add_7_30_n_67,
       addinc_add_7_30_n_68, addinc_add_7_30_n_69,
       addinc_add_7_30_n_70, addinc_add_7_30_n_71;
  wire addinc_add_7_30_n_72, addinc_add_7_30_n_73,
       addinc_add_7_30_n_74, addinc_add_7_30_n_75,
       addinc_add_7_30_n_76, addinc_add_7_30_n_77,
       addinc_add_7_30_n_78, addinc_add_7_30_n_79;
  wire addinc_add_7_30_n_80, addinc_add_7_30_n_81,
       addinc_add_7_30_n_82, addinc_add_7_30_n_83,
       addinc_add_7_30_n_84, addinc_add_7_30_n_85,
       addinc_add_7_30_n_86, addinc_add_7_30_n_87;
  wire addinc_add_7_30_n_88, addinc_add_7_30_n_89,
       addinc_add_7_30_n_90, addinc_add_7_30_n_91,
       addinc_add_7_30_n_92, addinc_add_7_30_n_93,
       addinc_add_7_30_n_94, addinc_add_7_30_n_95;
  wire addinc_add_7_30_n_96, addinc_add_7_30_n_97,
       addinc_add_7_30_n_98, addinc_add_7_30_n_99,
       addinc_add_7_30_n_100, addinc_add_7_30_n_101,
       addinc_add_7_30_n_102, addinc_add_7_30_n_103;
  wire addinc_add_7_30_n_104, addinc_add_7_30_n_105,
       addinc_add_7_30_n_106, addinc_add_7_30_n_107,
       addinc_add_7_30_n_108, addinc_add_7_30_n_109,
       addinc_add_7_30_n_110, addinc_add_7_30_n_111;
  wire addinc_add_7_30_n_112, addinc_add_7_30_n_113,
       addinc_add_7_30_n_114, addinc_add_7_30_n_115,
       addinc_add_7_30_n_116, addinc_add_7_30_n_117,
       addinc_add_7_30_n_118, addinc_add_7_30_n_119;
  wire addinc_add_7_30_n_120, addinc_add_7_30_n_121,
       addinc_add_7_30_n_122, addinc_add_7_30_n_123,
       addinc_add_7_30_n_124, addinc_add_7_30_n_125,
       addinc_add_7_30_n_126, addinc_add_7_30_n_127;
  wire addinc_add_7_30_n_128, addinc_add_7_30_n_129,
       addinc_add_7_30_n_130, addinc_add_7_30_n_131,
       addinc_add_7_30_n_132, addinc_add_7_30_n_133,
       addinc_add_7_30_n_134, addinc_add_7_30_n_135;
  wire addinc_add_7_30_n_136, addinc_add_7_30_n_137,
       addinc_add_7_30_n_138, addinc_add_7_30_n_139,
       addinc_add_7_30_n_140, addinc_add_7_30_n_141,
       addinc_add_7_30_n_142, addinc_add_7_30_n_143;
  wire addinc_add_7_30_n_144, addinc_add_7_30_n_145,
       addinc_add_7_30_n_147, addinc_add_7_30_n_148,
       addinc_add_7_30_n_149, addinc_add_7_30_n_150,
       addinc_add_7_30_n_151, addinc_add_7_30_n_152;
  wire addinc_add_7_30_n_153, addinc_add_7_30_n_154,
       addinc_add_7_30_n_155, addinc_add_7_30_n_156,
       addinc_add_7_30_n_157, addinc_add_7_30_n_158,
       addinc_add_7_30_n_159, addinc_add_7_30_n_161;
  wire addinc_add_7_30_n_162, addinc_add_7_30_n_163,
       addinc_add_7_30_n_165, addinc_add_7_30_n_166,
       addinc_add_7_30_n_168, addinc_add_7_30_n_169,
       addinc_add_7_30_n_170, addinc_add_7_30_n_172;
  wire addinc_add_7_30_n_173, addinc_add_7_30_n_174,
       addinc_add_7_30_n_175, addinc_add_7_30_n_176,
       addinc_add_7_30_n_177, addinc_add_7_30_n_181,
       addinc_add_7_30_n_182, addinc_add_7_30_n_183;
  wire addinc_add_7_30_n_184, addinc_add_7_30_n_185,
       addinc_add_7_30_n_189, addinc_add_7_30_n_190,
       addinc_add_7_30_n_192, addinc_add_7_30_n_193,
       addinc_add_7_30_n_194, addinc_add_7_30_n_196;
  wire addinc_add_7_30_n_200, addinc_add_7_30_n_201,
       addinc_add_7_30_n_202, addinc_add_7_30_n_203,
       addinc_add_7_30_n_204, addinc_add_7_30_n_205,
       addinc_add_7_30_n_206, addinc_add_7_30_n_207;
  wire addinc_add_7_30_n_208, addinc_add_7_30_n_213,
       addinc_add_7_30_n_214, addinc_add_7_30_n_215,
       addinc_add_7_30_n_217, addinc_add_7_30_n_218,
       addinc_add_7_30_n_219, addinc_add_7_30_n_220;
  wire addinc_add_7_30_n_224, addinc_add_7_30_n_225,
       addinc_add_7_30_n_226, addinc_add_7_30_n_230,
       addinc_add_7_30_n_231, addinc_add_7_30_n_235, n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_25;
  wire n_26, n_27, n_28, n_29, n_30, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_45, n_46, n_47, n_48, n_49;
  wire n_50, n_51, n_52, n_53, n_54, n_55, n_56, n_57;
  wire n_58, n_59, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74;
  sky130_fd_sc_hd__inv_1 g24(.A (n_13), .Y (n_74));
  sky130_fd_sc_hd__inv_1 g18(.A (n_28), .Y (n_73));
  sky130_fd_sc_hd__inv_1 g16(.A (n_48), .Y (n_72));
  sky130_fd_sc_hd__inv_1 g75(.A (n_5), .Y (n_71));
  sky130_fd_sc_hd__inv_1 g77(.A (n_52), .Y (n_70));
  sky130_fd_sc_hd__inv_2 g21(.A (n_41), .Y (n_69));
  sky130_fd_sc_hd__inv_1 g27(.A (n_51), .Y (n_68));
  sky130_fd_sc_hd__inv_1 g79(.A (n_47), .Y (n_67));
  sky130_fd_sc_hd__inv_1 g49(.A (n_36), .Y (n_66));
  sky130_fd_sc_hd__inv_2 g52(.A (n_20), .Y (n_65));
  sky130_fd_sc_hd__clkbuf_1 g85(.A (B[29]), .X (n_64));
  sky130_fd_sc_hd__clkbuf_1 g45(.A (A[26]), .X (n_63));
  sky130_fd_sc_hd__clkbuf_1 g29(.A (A[10]), .X (n_62));
  sky130_fd_sc_hd__clkbuf_1 g65(.A (B[7]), .X (n_61));
  sky130_fd_sc_hd__clkbuf_1 g84(.A (B[6]), .X (n_60));
  sky130_fd_sc_hd__clkbuf_1 g26(.A (A[8]), .X (n_59));
  sky130_fd_sc_hd__clkbuf_1 g66(.A (B[4]), .X (n_58));
  sky130_fd_sc_hd__clkbuf_1 g44(.A (A[25]), .X (n_57));
  sky130_fd_sc_hd__clkbuf_1 g68(.A (B[1]), .X (n_56));
  sky130_fd_sc_hd__buf_6 g69(.A (B[0]), .X (n_55));
  sky130_fd_sc_hd__clkbuf_1 g23(.A (A[6]), .X (n_54));
  sky130_fd_sc_hd__clkbuf_1 g62(.A (B[11]), .X (n_53));
  sky130_fd_sc_hd__inv_2 g78(.A (B[5]), .Y (n_52));
  sky130_fd_sc_hd__inv_2 g28(.A (A[9]), .Y (n_51));
  sky130_fd_sc_hd__clkbuf_1 g43(.A (A[24]), .X (n_50));
  sky130_fd_sc_hd__clkbuf_1 g81(.A (B[28]), .X (n_49));
  sky130_fd_sc_hd__clkinv_1 g17(.A (A[2]), .Y (n_48));
  sky130_fd_sc_hd__inv_2 g80(.A (B[2]), .Y (n_47));
  sky130_fd_sc_hd__clkbuf_1 g42(.A (A[23]), .X (n_46));
  sky130_fd_sc_hd__clkbuf_1 g15(.A (A[1]), .X (n_45));
  sky130_fd_sc_hd__clkbuf_1 g13(.A (B[31]), .X (n_44));
  sky130_fd_sc_hd__buf_8 g14(.A (A[0]), .X (n_43));
  sky130_fd_sc_hd__clkbuf_1 g41(.A (A[22]), .X (n_42));
  sky130_fd_sc_hd__inv_2 g22(.A (A[5]), .Y (n_41));
  sky130_fd_sc_hd__clkbuf_1 g33(.A (B[30]), .X (n_40));
  sky130_fd_sc_hd__clkbuf_1 g20(.A (A[4]), .X (n_39));
  sky130_fd_sc_hd__clkbuf_1 g40(.A (A[21]), .X (n_38));
  sky130_fd_sc_hd__clkbuf_1 g58(.A (B[19]), .X (n_37));
  sky130_fd_sc_hd__inv_2 g50(.A (B[3]), .Y (n_36));
  sky130_fd_sc_hd__clkbuf_1 g51(.A (A[31]), .X (n_35));
  sky130_fd_sc_hd__clkbuf_1 g39(.A (A[20]), .X (n_34));
  sky130_fd_sc_hd__clkbuf_1 g70(.A (B[27]), .X (n_33));
  sky130_fd_sc_hd__clkbuf_1 g34(.A (A[15]), .X (n_32));
  sky130_fd_sc_hd__clkbuf_1 g38(.A (A[19]), .X (n_31));
  sky130_fd_sc_hd__clkbuf_1 g55(.A (B[25]), .X (n_30));
  sky130_fd_sc_hd__clkbuf_1 g71(.A (B[24]), .X (n_29));
  sky130_fd_sc_hd__clkinv_1 g19(.A (A[3]), .Y (n_28));
  sky130_fd_sc_hd__clkbuf_1 g67(.A (A[30]), .X (n_27));
  sky130_fd_sc_hd__clkbuf_1 g37(.A (A[18]), .X (n_26));
  sky130_fd_sc_hd__clkbuf_1 g56(.A (B[23]), .X (n_25));
  sky130_fd_sc_hd__clkbuf_1 g57(.A (B[22]), .X (n_24));
  sky130_fd_sc_hd__clkbuf_1 g36(.A (A[17]), .X (n_23));
  sky130_fd_sc_hd__clkbuf_1 g82(.A (B[21]), .X (n_22));
  sky130_fd_sc_hd__clkbuf_1 g72(.A (B[20]), .X (n_21));
  sky130_fd_sc_hd__inv_2 g53(.A (Cin), .Y (n_20));
  sky130_fd_sc_hd__clkbuf_1 g48(.A (A[29]), .X (n_19));
  sky130_fd_sc_hd__clkbuf_1 g35(.A (A[16]), .X (n_18));
  sky130_fd_sc_hd__clkbuf_1 g59(.A (B[18]), .X (n_17));
  sky130_fd_sc_hd__clkbuf_1 g54(.A (B[26]), .X (n_16));
  sky130_fd_sc_hd__clkbuf_1 g73(.A (B[17]), .X (n_15));
  sky130_fd_sc_hd__clkbuf_1 g60(.A (B[16]), .X (n_14));
  sky130_fd_sc_hd__clkinv_1 g25(.A (A[7]), .Y (n_13));
  sky130_fd_sc_hd__clkbuf_1 g47(.A (A[28]), .X (n_12));
  sky130_fd_sc_hd__clkbuf_1 g12(.A (A[14]), .X (n_11));
  sky130_fd_sc_hd__clkbuf_1 g61(.A (B[15]), .X (n_10));
  sky130_fd_sc_hd__clkbuf_1 g86(.A (B[14]), .X (n_9));
  sky130_fd_sc_hd__clkbuf_1 g32(.A (A[13]), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g83(.A (B[13]), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g74(.A (B[12]), .X (n_6));
  sky130_fd_sc_hd__inv_2 g76(.A (B[9]), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g46(.A (A[27]), .X (n_4));
  sky130_fd_sc_hd__clkbuf_1 g31(.A (A[12]), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g63(.A (B[10]), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g30(.A (A[11]), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g64(.A (B[8]), .X (n_0));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1165__2398(.A1_N
       (addinc_add_7_30_n_125), .A2_N (addinc_add_7_30_n_235), .B1
       (addinc_add_7_30_n_125), .B2 (addinc_add_7_30_n_235), .X
       (S[31]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1166__5107(.A1_N
       (addinc_add_7_30_n_126), .A2_N (addinc_add_7_30_n_231), .B1
       (addinc_add_7_30_n_126), .B2 (addinc_add_7_30_n_231), .X
       (S[23]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1167__6260(.A1_N
       (addinc_add_7_30_n_105), .A2_N (addinc_add_7_30_n_230), .B1
       (addinc_add_7_30_n_105), .B2 (addinc_add_7_30_n_230), .X
       (S[27]));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1168__4319(.A1
       (addinc_add_7_30_n_67), .A2 (addinc_add_7_30_n_225), .B1
       (addinc_add_7_30_n_80), .Y (addinc_add_7_30_n_235));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1169__8428(.A1_N
       (addinc_add_7_30_n_118), .A2_N (addinc_add_7_30_n_226), .B1
       (addinc_add_7_30_n_118), .B2 (addinc_add_7_30_n_226), .X
       (S[29]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1170__5526(.A1_N
       (addinc_add_7_30_n_110), .A2_N (addinc_add_7_30_n_225), .B1
       (addinc_add_7_30_n_110), .B2 (addinc_add_7_30_n_225), .X
       (S[30]));
  sky130_fd_sc_hd__o211ai_1 addinc_add_7_30_g1171__6783(.A1
       (addinc_add_7_30_n_70), .A2 (addinc_add_7_30_n_154), .B1
       (addinc_add_7_30_n_51), .C1 (addinc_add_7_30_n_224), .Y (Cout));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1172__3680(.A1
       (addinc_add_7_30_n_27), .A2 (addinc_add_7_30_n_219), .B1
       (addinc_add_7_30_n_71), .Y (addinc_add_7_30_n_231));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1173__1617(.A1
       (addinc_add_7_30_n_30), .A2 (addinc_add_7_30_n_217), .B1
       (addinc_add_7_30_n_78), .Y (addinc_add_7_30_n_230));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1174__2802(.A1_N
       (addinc_add_7_30_n_124), .A2_N (addinc_add_7_30_n_219), .B1
       (addinc_add_7_30_n_124), .B2 (addinc_add_7_30_n_219), .X
       (S[22]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1175__1705(.A1_N
       (addinc_add_7_30_n_121), .A2_N (addinc_add_7_30_n_218), .B1
       (addinc_add_7_30_n_121), .B2 (addinc_add_7_30_n_218), .X
       (S[19]));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1176__5122(.A1_N
       (addinc_add_7_30_n_104), .A2_N (addinc_add_7_30_n_217), .B1
       (addinc_add_7_30_n_104), .B2 (addinc_add_7_30_n_217), .X
       (S[26]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1177__8246(.A
       (addinc_add_7_30_n_220), .B (addinc_add_7_30_n_75), .Y
       (addinc_add_7_30_n_226));
  sky130_fd_sc_hd__a31oi_1 addinc_add_7_30_g1178__7098(.A1
       (addinc_add_7_30_n_213), .A2 (addinc_add_7_30_n_31), .A3
       (addinc_add_7_30_n_79), .B1 (addinc_add_7_30_n_140), .Y
       (addinc_add_7_30_n_225));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1179__6131(.A_N
       (addinc_add_7_30_n_220), .B (addinc_add_7_30_n_130), .Y
       (addinc_add_7_30_n_224));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1180__1881(.A1_N
       (addinc_add_7_30_n_109), .A2_N (addinc_add_7_30_n_215), .B1
       (addinc_add_7_30_n_109), .B2 (addinc_add_7_30_n_215), .X
       (S[21]));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1181__5115(.A1_N
       (addinc_add_7_30_n_106), .A2_N (addinc_add_7_30_n_213), .B1
       (addinc_add_7_30_n_106), .B2 (addinc_add_7_30_n_213), .X
       (S[28]));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1182__7482(.A1_N
       (addinc_add_7_30_n_103), .A2_N (addinc_add_7_30_n_214), .B1
       (addinc_add_7_30_n_103), .B2 (addinc_add_7_30_n_214), .X
       (S[25]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1183__4733(.A
       (addinc_add_7_30_n_213), .B (addinc_add_7_30_n_79), .Y
       (addinc_add_7_30_n_220));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1184__6161(.A1
       (addinc_add_7_30_n_208), .A2 (addinc_add_7_30_n_60), .B1
       (addinc_add_7_30_n_136), .Y (addinc_add_7_30_n_219));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1185__9315(.A1
       (addinc_add_7_30_n_68), .A2 (addinc_add_7_30_n_205), .B1
       (addinc_add_7_30_n_81), .Y (addinc_add_7_30_n_218));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1186__9945(.A1
       (addinc_add_7_30_n_207), .A2 (addinc_add_7_30_n_25), .B1
       (addinc_add_7_30_n_141), .Y (addinc_add_7_30_n_217));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1187__2883(.A1_N
       (addinc_add_7_30_n_120), .A2_N (addinc_add_7_30_n_205), .B1
       (addinc_add_7_30_n_120), .B2 (addinc_add_7_30_n_205), .X
       (S[18]));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1188__2346(.A_N
       (addinc_add_7_30_n_208), .B (addinc_add_7_30_n_40), .Y
       (addinc_add_7_30_n_215));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1189__1666(.A_N
       (addinc_add_7_30_n_207), .B (addinc_add_7_30_n_39), .Y
       (addinc_add_7_30_n_214));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1190__7410(.A
       (addinc_add_7_30_n_206), .B (addinc_add_7_30_n_156), .Y
       (addinc_add_7_30_n_213));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1191__6417(.A1_N
       (addinc_add_7_30_n_127), .A2_N (addinc_add_7_30_n_203), .B1
       (addinc_add_7_30_n_127), .B2 (addinc_add_7_30_n_203), .X
       (S[24]));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1192__5477(.A1_N
       (addinc_add_7_30_n_123), .A2_N (addinc_add_7_30_n_201), .B1
       (addinc_add_7_30_n_123), .B2 (addinc_add_7_30_n_201), .X
       (S[20]));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1193__2398(.A1_N
       (addinc_add_7_30_n_119), .A2_N (addinc_add_7_30_n_204), .B1
       (addinc_add_7_30_n_119), .B2 (addinc_add_7_30_n_204), .X
       (S[17]));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1194__5107(.A1_N
       (addinc_add_7_30_n_108), .A2_N (addinc_add_7_30_n_200), .B1
       (addinc_add_7_30_n_108), .B2 (addinc_add_7_30_n_200), .X
       (S[15]));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1195__6260(.A
       (addinc_add_7_30_n_41), .B (addinc_add_7_30_n_201), .Y
       (addinc_add_7_30_n_208));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1196__4319(.A
       (addinc_add_7_30_n_33), .B (addinc_add_7_30_n_203), .Y
       (addinc_add_7_30_n_207));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1197__8428(.A
       (addinc_add_7_30_n_202), .B (addinc_add_7_30_n_128), .Y
       (addinc_add_7_30_n_206));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1198__5526(.A1
       (addinc_add_7_30_n_0), .A2 (addinc_add_7_30_n_62), .B1
       (addinc_add_7_30_n_138), .Y (addinc_add_7_30_n_205));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1199__6783(.A_N
       (addinc_add_7_30_n_0), .B (addinc_add_7_30_n_42), .Y
       (addinc_add_7_30_n_204));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1200(.A
       (addinc_add_7_30_n_202), .Y (addinc_add_7_30_n_203));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1201__3680(.A
       (addinc_add_7_30_n_196), .B (addinc_add_7_30_n_162), .Y
       (addinc_add_7_30_n_202));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1202__1617(.A1
       (addinc_add_7_30_n_194), .A2 (addinc_add_7_30_n_133), .B1
       (addinc_add_7_30_n_158), .Y (addinc_add_7_30_n_201));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1203__2802(.A1
       (addinc_add_7_30_n_29), .A2 (addinc_add_7_30_n_193), .B1
       (addinc_add_7_30_n_36), .Y (addinc_add_7_30_n_200));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1204__1705(.A
       (addinc_add_7_30_n_112), .B (addinc_add_7_30_n_194), .X (S[16]));
  sky130_fd_sc_hd__xnor2_1 addinc_add_7_30_g1205__5122(.A
       (addinc_add_7_30_n_111), .B (addinc_add_7_30_n_193), .Y (S[14]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1206__8246(.A
       (addinc_add_7_30_n_116), .B (addinc_add_7_30_n_192), .X (S[11]));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1208__7098(.A
       (addinc_add_7_30_n_194), .B (addinc_add_7_30_n_133), .C
       (addinc_add_7_30_n_134), .Y (addinc_add_7_30_n_196));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1209__6131(.A
       (addinc_add_7_30_n_98), .B (addinc_add_7_30_n_190), .X (S[13]));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1211__1881(.A
       (addinc_add_7_30_n_189), .B (addinc_add_7_30_n_157), .Y
       (addinc_add_7_30_n_194));
  sky130_fd_sc_hd__o21a_1 addinc_add_7_30_g1212__5115(.A1
       (addinc_add_7_30_n_28), .A2 (addinc_add_7_30_n_185), .B1
       (addinc_add_7_30_n_132), .X (addinc_add_7_30_n_193));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1213__7482(.A1
       (addinc_add_7_30_n_65), .A2 (addinc_add_7_30_n_184), .B1
       (addinc_add_7_30_n_76), .Y (addinc_add_7_30_n_192));
  sky130_fd_sc_hd__xnor2_1 addinc_add_7_30_g1214__4733(.A
       (addinc_add_7_30_n_113), .B (addinc_add_7_30_n_184), .Y (S[10]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1215__6161(.A
       (addinc_add_7_30_n_185), .B (addinc_add_7_30_n_84), .Y
       (addinc_add_7_30_n_190));
  sky130_fd_sc_hd__nand3_2 addinc_add_7_30_g1216__9315(.A
       (addinc_add_7_30_n_181), .B (addinc_add_7_30_n_129), .C
       (addinc_add_7_30_n_90), .Y (addinc_add_7_30_n_189));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1217__9945(.A
       (addinc_add_7_30_n_115), .B (addinc_add_7_30_n_181), .X (S[12]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1218__2883(.A
       (addinc_add_7_30_n_94), .B (addinc_add_7_30_n_183), .X (S[9]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1219__2346(.A
       (addinc_add_7_30_n_95), .B (addinc_add_7_30_n_182), .X (S[7]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1220__1666(.A
       (addinc_add_7_30_n_181), .B (addinc_add_7_30_n_90), .Y
       (addinc_add_7_30_n_185));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1221__7410(.A1
       (addinc_add_7_30_n_177), .A2 (addinc_add_7_30_n_64), .B1
       (addinc_add_7_30_n_144), .Y (addinc_add_7_30_n_184));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1222__6417(.A_N
       (addinc_add_7_30_n_177), .B (addinc_add_7_30_n_72), .Y
       (addinc_add_7_30_n_183));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1223__5477(.A1
       (addinc_add_7_30_n_34), .A2 (addinc_add_7_30_n_175), .B1
       (addinc_add_7_30_n_35), .Y (addinc_add_7_30_n_182));
  sky130_fd_sc_hd__nand3_2 addinc_add_7_30_g1224__2398(.A
       (addinc_add_7_30_n_176), .B (addinc_add_7_30_n_155), .C
       (addinc_add_7_30_n_89), .Y (addinc_add_7_30_n_181));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1225__5107(.A
       (addinc_add_7_30_n_100), .B (addinc_add_7_30_n_173), .X (S[8]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1226__6260(.A
       (addinc_add_7_30_n_99), .B (addinc_add_7_30_n_175), .X (S[6]));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1227__4319(.A
       (addinc_add_7_30_n_114), .B (addinc_add_7_30_n_174), .X (S[5]));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1228__8428(.A
       (addinc_add_7_30_n_73), .B (addinc_add_7_30_n_173), .Y
       (addinc_add_7_30_n_177));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1229__5526(.A
       (addinc_add_7_30_n_172), .B (addinc_add_7_30_n_131), .Y
       (addinc_add_7_30_n_176));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1230__6783(.A1
       (addinc_add_7_30_n_168), .A2 (addinc_add_7_30_n_107), .B1
       (addinc_add_7_30_n_143), .Y (addinc_add_7_30_n_175));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1231__3680(.A1
       (addinc_add_7_30_n_77), .A2 (addinc_add_7_30_n_169), .B1
       (addinc_add_7_30_n_74), .Y (addinc_add_7_30_n_174));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1232(.A
       (addinc_add_7_30_n_172), .Y (addinc_add_7_30_n_173));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1233__1617(.A
       (addinc_add_7_30_n_170), .B (addinc_add_7_30_n_148), .Y
       (addinc_add_7_30_n_172));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1234__2802(.A
       (addinc_add_7_30_n_102), .B (addinc_add_7_30_n_168), .X (S[4]));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1235__1705(.A
       (addinc_add_7_30_n_168), .B (addinc_add_7_30_n_122), .C
       (addinc_add_7_30_n_107), .Y (addinc_add_7_30_n_170));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1236(.A
       (addinc_add_7_30_n_168), .Y (addinc_add_7_30_n_169));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1237__5122(.A
       (addinc_add_7_30_n_166), .B (addinc_add_7_30_n_53), .Y
       (addinc_add_7_30_n_168));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1238__8246(.A
       (addinc_add_7_30_n_101), .B (addinc_add_7_30_n_165), .X (S[3]));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1239__7098(.A
       (addinc_add_7_30_n_165), .B (addinc_add_7_30_n_56), .Y
       (addinc_add_7_30_n_166));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1240__6131(.A
       (addinc_add_7_30_n_163), .B (addinc_add_7_30_n_86), .Y
       (addinc_add_7_30_n_165));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1241__1881(.A
       (addinc_add_7_30_n_96), .B (addinc_add_7_30_n_161), .X (S[2]));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1242__5115(.A
       (addinc_add_7_30_n_161), .B (addinc_add_7_30_n_58), .Y
       (addinc_add_7_30_n_163));
  sky130_fd_sc_hd__a221oi_1 addinc_add_7_30_g1243__7482(.A1
       (addinc_add_7_30_n_149), .A2 (addinc_add_7_30_n_45), .B1
       (addinc_add_7_30_n_158), .B2 (addinc_add_7_30_n_134), .C1
       (addinc_add_7_30_n_46), .Y (addinc_add_7_30_n_162));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1244__4733(.A
       (addinc_add_7_30_n_159), .B (addinc_add_7_30_n_50), .Y
       (addinc_add_7_30_n_161));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1245__6161(.A
       (addinc_add_7_30_n_97), .B (addinc_add_7_30_n_147), .X (S[1]));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1246__9315(.A
       (addinc_add_7_30_n_147), .B (addinc_add_7_30_n_49), .Y
       (addinc_add_7_30_n_159));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1247__9945(.A1
       (addinc_add_7_30_n_38), .A2 (addinc_add_7_30_n_151), .B1
       (addinc_add_7_30_n_88), .Y (addinc_add_7_30_n_158));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1248__2883(.A1
       (addinc_add_7_30_n_150), .A2 (addinc_add_7_30_n_44), .B1_N
       (addinc_add_7_30_n_54), .Y (addinc_add_7_30_n_157));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1249__2346(.A1
       (addinc_add_7_30_n_153), .A2 (addinc_add_7_30_n_82), .B1_N
       (addinc_add_7_30_n_92), .Y (addinc_add_7_30_n_156));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1250__1666(.A
       (addinc_add_7_30_n_152), .B (addinc_add_7_30_n_83), .Y
       (addinc_add_7_30_n_155));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1251__7410(.A1
       (addinc_add_7_30_n_140), .A2 (addinc_add_7_30_n_66), .B1_N
       (addinc_add_7_30_n_80), .Y (addinc_add_7_30_n_154));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1252__6417(.A1
       (addinc_add_7_30_n_30), .A2 (addinc_add_7_30_n_142), .B1
       (addinc_add_7_30_n_78), .Y (addinc_add_7_30_n_153));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1253__5477(.A
       (addinc_add_7_30_n_145), .B (addinc_add_7_30_n_76), .Y
       (addinc_add_7_30_n_152));
  sky130_fd_sc_hd__o21a_1 addinc_add_7_30_g1254__2398(.A1
       (addinc_add_7_30_n_68), .A2 (addinc_add_7_30_n_139), .B1
       (addinc_add_7_30_n_81), .X (addinc_add_7_30_n_151));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1255__5107(.A1
       (addinc_add_7_30_n_29), .A2 (addinc_add_7_30_n_132), .B1
       (addinc_add_7_30_n_36), .Y (addinc_add_7_30_n_150));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1256__6260(.A1
       (addinc_add_7_30_n_27), .A2 (addinc_add_7_30_n_137), .B1
       (addinc_add_7_30_n_71), .Y (addinc_add_7_30_n_149));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1257__4319(.A1
       (addinc_add_7_30_n_143), .A2 (addinc_add_7_30_n_122), .B1
       (addinc_add_7_30_n_135), .Y (addinc_add_7_30_n_148));
  sky130_fd_sc_hd__o2bb2ai_2 addinc_add_7_30_g1258__8428(.A1_N (n_43),
       .A2_N (n_55), .B1 (addinc_add_7_30_n_1), .B2
       (addinc_add_7_30_n_59), .Y (addinc_add_7_30_n_147));
  sky130_fd_sc_hd__xnor2_1 addinc_add_7_30_g1259__5526(.A
       (addinc_add_7_30_n_1), .B (addinc_add_7_30_n_93), .Y (S[0]));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1260__6783(.A_N
       (addinc_add_7_30_n_65), .B (addinc_add_7_30_n_144), .Y
       (addinc_add_7_30_n_145));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1261(.A
       (addinc_add_7_30_n_141), .Y (addinc_add_7_30_n_142));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1262(.A
       (addinc_add_7_30_n_138), .Y (addinc_add_7_30_n_139));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1263(.A
       (addinc_add_7_30_n_136), .Y (addinc_add_7_30_n_137));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1264__3680(.A1
       (addinc_add_7_30_n_35), .A2 (addinc_add_7_30_n_69), .B1
       (addinc_add_7_30_n_48), .Y (addinc_add_7_30_n_135));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1265__1617(.A
       (addinc_add_7_30_n_117), .B (addinc_add_7_30_n_91), .Y
       (addinc_add_7_30_n_144));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1266__2802(.A1
       (addinc_add_7_30_n_37), .A2 (addinc_add_7_30_n_74), .B1
       (addinc_add_7_30_n_57), .Y (addinc_add_7_30_n_143));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1267__1705(.A1
       (addinc_add_7_30_n_26), .A2 (addinc_add_7_30_n_39), .B1
       (addinc_add_7_30_n_87), .Y (addinc_add_7_30_n_141));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1268__5122(.A1
       (addinc_add_7_30_n_75), .A2 (addinc_add_7_30_n_32), .B1
       (addinc_add_7_30_n_47), .Y (addinc_add_7_30_n_140));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1269__8246(.A1
       (addinc_add_7_30_n_63), .A2 (addinc_add_7_30_n_42), .B1
       (addinc_add_7_30_n_52), .Y (addinc_add_7_30_n_138));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1270__7098(.A1
       (addinc_add_7_30_n_61), .A2 (addinc_add_7_30_n_40), .B1
       (addinc_add_7_30_n_85), .Y (addinc_add_7_30_n_136));
  sky130_fd_sc_hd__nor4bb_1 addinc_add_7_30_g1271__6131(.A
       (addinc_add_7_30_n_73), .B (addinc_add_7_30_n_65), .C_N
       (addinc_add_7_30_n_64), .D_N (addinc_add_7_30_n_83), .Y
       (addinc_add_7_30_n_131));
  sky130_fd_sc_hd__nor3_1 addinc_add_7_30_g1272__1881(.A
       (addinc_add_7_30_n_70), .B (addinc_add_7_30_n_67), .C
       (addinc_add_7_30_n_32), .Y (addinc_add_7_30_n_130));
  sky130_fd_sc_hd__nor3b_1 addinc_add_7_30_g1273__5115(.A
       (addinc_add_7_30_n_28), .B (addinc_add_7_30_n_29), .C_N
       (addinc_add_7_30_n_44), .Y (addinc_add_7_30_n_129));
  sky130_fd_sc_hd__nor4b_1 addinc_add_7_30_g1274__7482(.A
       (addinc_add_7_30_n_33), .B (addinc_add_7_30_n_26), .C
       (addinc_add_7_30_n_30), .D_N (addinc_add_7_30_n_82), .Y
       (addinc_add_7_30_n_128));
  sky130_fd_sc_hd__nor4b_1 addinc_add_7_30_g1275__4733(.A
       (addinc_add_7_30_n_41), .B (addinc_add_7_30_n_61), .C
       (addinc_add_7_30_n_27), .D_N (addinc_add_7_30_n_45), .Y
       (addinc_add_7_30_n_134));
  sky130_fd_sc_hd__nor4_1 addinc_add_7_30_g1276__6161(.A
       (addinc_add_7_30_n_43), .B (addinc_add_7_30_n_63), .C
       (addinc_add_7_30_n_68), .D (addinc_add_7_30_n_38), .Y
       (addinc_add_7_30_n_133));
  sky130_fd_sc_hd__o21a_1 addinc_add_7_30_g1277__9315(.A1
       (addinc_add_7_30_n_28), .A2 (addinc_add_7_30_n_84), .B1
       (addinc_add_7_30_n_55), .X (addinc_add_7_30_n_132));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1278__9945(.A_N
       (addinc_add_7_30_n_72), .B (addinc_add_7_30_n_64), .Y
       (addinc_add_7_30_n_117));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1279__2883(.A
       (addinc_add_7_30_n_33), .B_N (addinc_add_7_30_n_39), .Y
       (addinc_add_7_30_n_127));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1280__2346(.A
       (addinc_add_7_30_n_89), .B (addinc_add_7_30_n_83), .X
       (addinc_add_7_30_n_116));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1281__1666(.A_N
       (addinc_add_7_30_n_46), .B (addinc_add_7_30_n_45), .Y
       (addinc_add_7_30_n_126));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1282__7410(.A
       (addinc_add_7_30_n_84), .B (addinc_add_7_30_n_90), .X
       (addinc_add_7_30_n_115));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1283__6417(.A_N
       (addinc_add_7_30_n_70), .B (addinc_add_7_30_n_51), .Y
       (addinc_add_7_30_n_125));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1284__5477(.A
       (addinc_add_7_30_n_27), .B_N (addinc_add_7_30_n_71), .Y
       (addinc_add_7_30_n_124));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1285__2398(.A
       (addinc_add_7_30_n_37), .B_N (addinc_add_7_30_n_57), .Y
       (addinc_add_7_30_n_114));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1286__5107(.A
       (addinc_add_7_30_n_41), .B_N (addinc_add_7_30_n_40), .Y
       (addinc_add_7_30_n_123));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1287__6260(.A
       (addinc_add_7_30_n_34), .B (addinc_add_7_30_n_69), .Y
       (addinc_add_7_30_n_122));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1288__4319(.A_N
       (addinc_add_7_30_n_38), .B (addinc_add_7_30_n_88), .Y
       (addinc_add_7_30_n_121));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1289__8428(.A
       (addinc_add_7_30_n_68), .B_N (addinc_add_7_30_n_81), .Y
       (addinc_add_7_30_n_120));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1290__5526(.A
       (addinc_add_7_30_n_52), .B (addinc_add_7_30_n_62), .Y
       (addinc_add_7_30_n_119));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1291__6783(.A
       (addinc_add_7_30_n_47), .B (addinc_add_7_30_n_31), .Y
       (addinc_add_7_30_n_118));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1292__3680(.A
       (addinc_add_7_30_n_65), .B_N (addinc_add_7_30_n_76), .Y
       (addinc_add_7_30_n_113));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1293__1617(.A
       (addinc_add_7_30_n_43), .B_N (addinc_add_7_30_n_42), .Y
       (addinc_add_7_30_n_112));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1294__2802(.A
       (addinc_add_7_30_n_29), .B_N (addinc_add_7_30_n_36), .Y
       (addinc_add_7_30_n_111));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1295__1705(.A
       (addinc_add_7_30_n_80), .B (addinc_add_7_30_n_66), .X
       (addinc_add_7_30_n_110));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1296__5122(.A
       (addinc_add_7_30_n_85), .B (addinc_add_7_30_n_60), .Y
       (addinc_add_7_30_n_109));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1297__8246(.A
       (addinc_add_7_30_n_77), .B_N (addinc_add_7_30_n_74), .Y
       (addinc_add_7_30_n_102));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1298__7098(.A
       (addinc_add_7_30_n_53), .B (addinc_add_7_30_n_56), .X
       (addinc_add_7_30_n_101));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1299__6131(.A_N
       (addinc_add_7_30_n_73), .B (addinc_add_7_30_n_72), .Y
       (addinc_add_7_30_n_100));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1300__1881(.A_N
       (addinc_add_7_30_n_34), .B (addinc_add_7_30_n_35), .Y
       (addinc_add_7_30_n_99));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1301__5115(.A
       (addinc_add_7_30_n_28), .B_N (addinc_add_7_30_n_55), .Y
       (addinc_add_7_30_n_98));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1302__7482(.A
       (addinc_add_7_30_n_50), .B (addinc_add_7_30_n_49), .X
       (addinc_add_7_30_n_97));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1303__4733(.A
       (addinc_add_7_30_n_86), .B (addinc_add_7_30_n_58), .X
       (addinc_add_7_30_n_96));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1304__6161(.A
       (addinc_add_7_30_n_54), .B (addinc_add_7_30_n_44), .Y
       (addinc_add_7_30_n_108));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1305__9315(.A
       (addinc_add_7_30_n_77), .B (addinc_add_7_30_n_37), .Y
       (addinc_add_7_30_n_107));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1306__9945(.A
       (addinc_add_7_30_n_69), .B_N (addinc_add_7_30_n_48), .Y
       (addinc_add_7_30_n_95));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1307__2883(.A
       (addinc_add_7_30_n_75), .B (addinc_add_7_30_n_79), .Y
       (addinc_add_7_30_n_106));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1308__2346(.A
       (addinc_add_7_30_n_92), .B (addinc_add_7_30_n_82), .Y
       (addinc_add_7_30_n_105));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1309__1666(.A
       (addinc_add_7_30_n_91), .B (addinc_add_7_30_n_64), .X
       (addinc_add_7_30_n_94));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1310__7410(.A
       (addinc_add_7_30_n_30), .B_N (addinc_add_7_30_n_78), .Y
       (addinc_add_7_30_n_104));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1311__6417(.A
       (addinc_add_7_30_n_87), .B (addinc_add_7_30_n_25), .Y
       (addinc_add_7_30_n_103));
  sky130_fd_sc_hd__xor2_1 addinc_add_7_30_g1312__5477(.A (n_55), .B
       (n_43), .X (addinc_add_7_30_n_93));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1313(.A
       (addinc_add_7_30_n_67), .Y (addinc_add_7_30_n_66));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1314(.A
       (addinc_add_7_30_n_63), .Y (addinc_add_7_30_n_62));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1315(.A
       (addinc_add_7_30_n_61), .Y (addinc_add_7_30_n_60));
  sky130_fd_sc_hd__nor2_4 addinc_add_7_30_g1316__2398(.A (n_43), .B
       (n_55), .Y (addinc_add_7_30_n_59));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1317__5107(.A (n_33), .B
       (n_4), .Y (addinc_add_7_30_n_92));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1318__6260(.A (n_71), .B
       (n_68), .Y (addinc_add_7_30_n_91));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1319__4319(.A (n_3), .B
       (n_6), .X (addinc_add_7_30_n_90));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1320__8428(.A (n_53), .B
       (n_1), .Y (addinc_add_7_30_n_89));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1321__5526(.A (n_37), .B
       (n_31), .Y (addinc_add_7_30_n_88));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1322__6783(.A (n_30), .B
       (n_57), .Y (addinc_add_7_30_n_87));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1323__3680(.A (n_67), .B
       (n_72), .Y (addinc_add_7_30_n_86));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1324__1617(.A
       (addinc_add_7_30_n_23), .B (addinc_add_7_30_n_12), .Y
       (addinc_add_7_30_n_85));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1325__2802(.A (n_6), .B
       (n_3), .Y (addinc_add_7_30_n_84));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1326__1705(.A (n_1), .B
       (n_53), .X (addinc_add_7_30_n_83));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1327__5122(.A (n_4), .B
       (n_33), .X (addinc_add_7_30_n_82));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1328__8246(.A
       (addinc_add_7_30_n_19), .B (addinc_add_7_30_n_10), .Y
       (addinc_add_7_30_n_81));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1329__7098(.A (n_40), .B
       (n_27), .Y (addinc_add_7_30_n_80));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1330__6131(.A (n_12), .B
       (n_49), .X (addinc_add_7_30_n_79));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1331__1881(.A (n_16), .B
       (n_63), .Y (addinc_add_7_30_n_78));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1332__5115(.A (n_39), .B
       (n_58), .Y (addinc_add_7_30_n_77));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1333__7482(.A
       (addinc_add_7_30_n_20), .B (addinc_add_7_30_n_8), .Y
       (addinc_add_7_30_n_76));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1334__4733(.A (n_49), .B
       (n_12), .Y (addinc_add_7_30_n_75));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1335__6161(.A (n_58), .B
       (n_39), .Y (addinc_add_7_30_n_74));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1336__9315(.A
       (addinc_add_7_30_n_15), .B (addinc_add_7_30_n_9), .Y
       (addinc_add_7_30_n_73));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1337__9945(.A (n_0), .B
       (n_59), .Y (addinc_add_7_30_n_72));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1338__2883(.A
       (addinc_add_7_30_n_22), .B (addinc_add_7_30_n_17), .Y
       (addinc_add_7_30_n_71));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1339__2346(.A (n_35), .B
       (n_44), .Y (addinc_add_7_30_n_70));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1340__1666(.A (n_74), .B
       (n_61), .Y (addinc_add_7_30_n_69));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1341__7410(.A (n_26), .B
       (n_17), .Y (addinc_add_7_30_n_68));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1342__6417(.A (n_27), .B
       (n_40), .Y (addinc_add_7_30_n_67));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1343__5477(.A (n_62), .B
       (n_2), .Y (addinc_add_7_30_n_65));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1344__2398(.A (n_68), .B
       (n_71), .X (addinc_add_7_30_n_64));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1345__5107(.A (n_23), .B
       (n_15), .Y (addinc_add_7_30_n_63));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1346__6260(.A (n_38), .B
       (n_22), .Y (addinc_add_7_30_n_61));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1347(.A
       (addinc_add_7_30_n_32), .Y (addinc_add_7_30_n_31));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1348(.A
       (addinc_add_7_30_n_26), .Y (addinc_add_7_30_n_25));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1349__4319(.A (n_72), .B
       (n_67), .X (addinc_add_7_30_n_58));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1350__8428(.A
       (addinc_add_7_30_n_3), .B (addinc_add_7_30_n_13), .Y
       (addinc_add_7_30_n_57));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1351__5526(.A (n_73), .B
       (n_66), .X (addinc_add_7_30_n_56));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1352__6783(.A
       (addinc_add_7_30_n_18), .B (addinc_add_7_30_n_24), .Y
       (addinc_add_7_30_n_55));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1353__3680(.A (n_10), .B
       (n_32), .Y (addinc_add_7_30_n_54));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1354__1617(.A (n_66), .B
       (n_73), .Y (addinc_add_7_30_n_53));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1355__2802(.A
       (addinc_add_7_30_n_6), .B (addinc_add_7_30_n_5), .Y
       (addinc_add_7_30_n_52));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1356__1705(.A (n_44), .B
       (n_35), .Y (addinc_add_7_30_n_51));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1357__5122(.A (n_56), .B
       (n_45), .Y (addinc_add_7_30_n_50));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1358__8246(.A
       (addinc_add_7_30_n_11), .B (addinc_add_7_30_n_4), .Y
       (addinc_add_7_30_n_49));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1359__7098(.A
       (addinc_add_7_30_n_7), .B (addinc_add_7_30_n_16), .Y
       (addinc_add_7_30_n_48));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1360__6131(.A (n_64), .B
       (n_19), .Y (addinc_add_7_30_n_47));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1361__1881(.A (n_25), .B
       (n_46), .X (addinc_add_7_30_n_46));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1362__5115(.A (n_46), .B
       (n_25), .X (addinc_add_7_30_n_45));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g1363__7482(.A (n_32), .B
       (n_10), .X (addinc_add_7_30_n_44));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1364__4733(.A (n_18), .B
       (n_14), .Y (addinc_add_7_30_n_43));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1365__6161(.A (n_14), .B
       (n_18), .Y (addinc_add_7_30_n_42));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1366__9315(.A (n_34), .B
       (n_21), .Y (addinc_add_7_30_n_41));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1367__9945(.A (n_21), .B
       (n_34), .Y (addinc_add_7_30_n_40));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1368__2883(.A (n_29), .B
       (n_50), .Y (addinc_add_7_30_n_39));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1369__2346(.A (n_31), .B
       (n_37), .Y (addinc_add_7_30_n_38));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1370__1666(.A (n_69), .B
       (n_70), .Y (addinc_add_7_30_n_37));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1371__7410(.A
       (addinc_add_7_30_n_2), .B (addinc_add_7_30_n_14), .Y
       (addinc_add_7_30_n_36));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1372__6417(.A (n_60), .B
       (addinc_add_7_30_n_21), .Y (addinc_add_7_30_n_35));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1373__5477(.A (n_54), .B
       (n_60), .Y (addinc_add_7_30_n_34));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1374__2398(.A (n_50), .B
       (n_29), .Y (addinc_add_7_30_n_33));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1375__5107(.A (n_19), .B
       (n_64), .Y (addinc_add_7_30_n_32));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1376__6260(.A (n_63), .B
       (n_16), .Y (addinc_add_7_30_n_30));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1377__4319(.A (n_11), .B
       (n_9), .Y (addinc_add_7_30_n_29));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1378__8428(.A (n_8), .B
       (n_7), .Y (addinc_add_7_30_n_28));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1379__5526(.A (n_42), .B
       (n_24), .Y (addinc_add_7_30_n_27));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1380__6783(.A (n_57), .B
       (n_30), .Y (addinc_add_7_30_n_26));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1381(.A (n_8), .X
       (addinc_add_7_30_n_24));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1382(.A (n_22), .X
       (addinc_add_7_30_n_23));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1383(.A (n_24), .X
       (addinc_add_7_30_n_22));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1384(.A (n_54), .X
       (addinc_add_7_30_n_21));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1385(.A (n_2), .X
       (addinc_add_7_30_n_20));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1386(.A (n_17), .X
       (addinc_add_7_30_n_19));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1387(.A (n_7), .X
       (addinc_add_7_30_n_18));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1388(.A (n_42), .X
       (addinc_add_7_30_n_17));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1389(.A (n_74), .X
       (addinc_add_7_30_n_16));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1390(.A (n_59), .X
       (addinc_add_7_30_n_15));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1391(.A (n_11), .X
       (addinc_add_7_30_n_14));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1392(.A (n_69), .X
       (addinc_add_7_30_n_13));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1394(.A (n_65), .Y
       (addinc_add_7_30_n_1));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1395(.A (n_38), .X
       (addinc_add_7_30_n_12));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1396(.A (n_45), .Y
       (addinc_add_7_30_n_11));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1397(.A (n_26), .X
       (addinc_add_7_30_n_10));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1398(.A (n_0), .X
       (addinc_add_7_30_n_9));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1399(.A (n_62), .X
       (addinc_add_7_30_n_8));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1400(.A (n_61), .X
       (addinc_add_7_30_n_7));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1401(.A (n_15), .X
       (addinc_add_7_30_n_6));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1402(.A (n_23), .X
       (addinc_add_7_30_n_5));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1403(.A (n_56), .Y
       (addinc_add_7_30_n_4));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1404(.A (n_70), .X
       (addinc_add_7_30_n_3));
  sky130_fd_sc_hd__clkbuf_1 addinc_add_7_30_g1405(.A (n_9), .X
       (addinc_add_7_30_n_2));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g2__3680(.A
       (addinc_add_7_30_n_43), .B_N (addinc_add_7_30_n_194), .Y
       (addinc_add_7_30_n_0));
endmodule

